### ISSUE TITLE
Removing lena.jpg

### ISSUE THREAD

**Issue by diadochos** [kornia/kornia#1019]
Hi, thank you for providing the very convenient library!

### Issue: The [Gaussian Blur example](https://kornia.readthedocs.io/en/latest/tutorials/gaussian_blur.html) uses the "Lena" image as an example.

Recently, I learned that there is a movement to remove the image from the community: [LOSING LENA](https://www.losinglena.com/) which I believe the great developers of this library can also agree to support in this library.

To this end, I'd like to suggest the following changes:
1. Remove `kornia/tutorials/data/lena.jpg`.
1. Change the example code `kornia/tutorials/gaussian_blur.py` to use `kornia/tutorials/data/bennett_aden.png` instead of `lena.jpg`.
1. Change the source code generating [this page](https://kornia.readthedocs.io/en/latest/tutorials/gaussian_blur.html) to use `bennett_aden.png` instead of `lena.jpg`.

I'd be happy to write a PR, but I could not figure out what file to change for the last item, i.e., which file to change to edit `https://kornia.readthedocs.io/en/latest/tutorials/gaussian_blur.html`. Could someone kindly guide me to the right place to start?

**Comment by edgarriba** [comment]
@diadochos thanks for reporting this. We definitely join this movement.

In fact, we are on the process to move all the tutorials to a separate repo/page in notebook/colab format
https://github.com/kornia/tutorials / https://kornia-tutorials.readthedocs.io/

Maybe you could help on that and send a PR there ? I can remove myself later from main repo the existing tutorial.

Do you have in mind what could be a good image reference replacement ? :)

**Comment by diadochos** [comment]
Hi @edgarriba, thanks for the prompt answer! I'm glad to hear that.

> Do you have in mind what could be a good image reference replacement ? :)

I know of this cute cat :cat: picture that is in the public domain:
https://publicdomainq.net/kitten-cat-animal-0022136/
Otherwise, I think the `bennett_aden.png` that is already in the data folder could be a substitution.

> Maybe you could help on that and send a PR there?

Certainly. Will it do if I pick up the notebook from the existing tutorial, modify it, and send a PR to this repo?

**Comment by edgarriba** [comment]
sure we can use Benett's - unless @bigcmos has any objection.
Bennet was such an inspiration in early `torchgeometry` days :)

>  Certainly. Will it do if I pick up the notebook from the existing tutorial, modify it, and send a PR to this repo?
Yeap, slightly modify the existing one adding a bit of polishing. Take as a reference the other notebooks in the new repo.

**Comment by diadochos** [comment]
Hi @edgarriba, I've filed a PR above as I could find some time today. Please kindly take a look at your convenience.
