### ISSUE TITLE
you basically stole your logo from gtk.org

### ISSUE THREAD

**Issue by nzjrs** [kornia/kornia#1027]
https://gtk.org/

**Comment by ducha-aiki** [comment]
Hi,

Thank you for bringing our attention to the issue of logo similarity, which we were not aware of (although we would appreciate a more polite tone).

Our logo is color-modified version of Arraiy logo (check here https://www.linkedin.com/company/arraiy/about/), founded in 2016 where kornia was initially born under the name torchgeometry (https://pypi.org/project/torchgeometry/#history) as a side project.
Specifically, as the idea of the kornia is OpenCV in PyTorch, we choose colors to be similar to OpenCV (so red, green and blue) and leave the shape of our parent company as is.
As Ubuntu users we, of course, know and appreciate GTK, but never seen its website, nor logo.
Now, indeed, although without any malicious intent, kornia logo is similar to GTK one and we will think how to change it to avoid any confusion.
--

Best, Dmytro,  on behalf of kornia team.
