### ISSUE TITLE
gray_to_(rgb,bgr)

### ISSUE THREAD

**Issue by ethanrublee** [kornia/kornia#1028]
## 🚀 Feature
I have a grayscale image, and I'd like to use it with the augmentation functions which only support 3 channel images.

I'm looking for the equivalent of ``cv2.cvtColor(cv2.COLOR_GRAY2BGR, gray)``.

**Comment by shijianjian** [comment]
Kornia.color.gray_to_rgb.

**Comment by ethanrublee** [comment]
This doesn't exist as far as I can tell, am I missing something?

**Comment by shijianjian** [comment]
You are right. Sorry I did not aware that we don't have it. XD. Are you interested in sending a PR?
