### ISSUE TITLE
Bug in Examples DepthWarperApp

### ISSUE THREAD

**Issue by lg93lggt** [kornia/kornia#1093]
## To Reproduce

1. in function load_data , create_pinhole is not defined, so I change it to dgm.geometry.PinholeCamera
    intrinsics44 = np.eye(4)
    intrinsics44[:3, :3] = intrinsics
    extrinsics44 = np.eye(4)
    extrinsics44[:3] = extrinsics
    camera = dgm.geometry.PinholeCamera(intrinsics, extrinsics, height, width)
    //#CHANGE
    //# camera = create_pinhole(intrinsics, extrinsics, height, width)
2.No compute_homographies in warpper , so:
    warper.compute_projection_matrix(cam_ref)
    //# warper.compute_homographies(cam_ref)

**Comment by edgarriba** [comment]
@lg93lggt what the error you get ?
