### ISSUE TITLE
`_params` not accesible in VideoSequential

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1101]
## 🐛 Bug

In kornia `0.5.4` the member `_params` is not accessible anymore from `K.augmentation.VideoSequential`.

See: https://github.com/PyTorchLightning/lightning-flash/pull/405/checks?check_run_id=2808981288

```bash
AttributeError: 'VideoSequential' object has no attribute '_params'
```

**Comment by shijianjian** [comment]
The API inheritance changed so that the model saved previously can not be loaded into the newer version. This should not be a bug in our side. 

Meanwhile, I would say to use state_dict instead. It might be more persistent among versions. Could you try state_dict?
