### ISSUE TITLE
Unifying kernel_size argument in `kornia.filters`

### ISSUE THREAD

**Issue by justanhduc** [kornia/kornia#1109]
## 🚀 Feature
Currently some functions in the `filters` module take a tuple as `kernel_size` argument, but some accept only `int`. I would like to unify all these functions to `Union[Tuple[int, int], int]`.

## Motivation

This would make the API more uniform and inline with Pytorch.

## Pitch

```
filtered_img = kornia.median_blur(img, 3)  # Currently it would raise an error.
```

**Comment by edgarriba** [comment]
@justanhduc I only see one blocker here. Torchscript doesn't support properly `Union` types yet. So I would add this feature request in the backlog until this feature is added in pytorch. See: https://github.com/pytorch/pytorch/pull/53180 and https://github.com/pytorch/pytorch/issues/41412
