### ISSUE TITLE
[Feature request] Add `depth_to_disparity` and `disparity_to_depth` methods in `StereoCamera` class

### ISSUE THREAD

**Issue by copaah** [kornia/kornia#1122]
## 🚀 Feature

Two methods to convert between disparity and depth maps. This should be batched and be general, i.e. the normal conversion
`depth = (baseline * focal length) / disparity)` doesn't work for different focal lengths.

## Motivation

Some downstream tasks in 3D vision uses depth maps rather than point clouds or disparity maps. 

## Pitch

Add two new methods:
* `disparity_to_depth`
* `depth_to_disparity`

To the `StereoCamera` class. Both methods should take as input a tensor of shape `(B, H, W, 1)` and return the same shape. Core logic should be separated into its own function and there should be extensive tests. Tests can utilize already added test data in the `test_stereo.py` module.

**Comment by ankitajais20** [comment]
@copaah is this feature request to add depth_to_disparity and disparity_to_depth methods in StereoCamera class #1122 already implemented? I would like to work on implementing this, if not.

**Comment by edgarriba** [comment]
@ankitajais20 I don't think it's implemented yet - feel free to go for it. Join our slack in case you need any help or guidance from our mentors.

**Comment by copaah** [comment]
@ankitajais20 I started working on it, but got a little sidetracked. Feel free to take over!

**Comment by copaah** [comment]
@ankitajais20 

Do you still want to contribute to this? I can supervise you if you have any questions - just ping me here or on slack.

**Comment by nitaifingerhut** [comment]
I can also guide you through this or maybe do it myself if I'll find the time

**Comment by johnnv1** [comment]
Closing in favor of #1962
