### ISSUE TITLE
Why input of rgb_to_lab and output of lab_to_rgb are not the same?

### ISSUE THREAD

**Issue by hminle** [kornia/kornia#1140]
Hi Kornia team,

I test `rbg_to_lab` and `lab_to_rgb` with these lines of code:
![image](https://user-images.githubusercontent.com/16201681/124204068-31d1df80-daac-11eb-8a27-a45df132d842.png)

The `input` and `output_rgb` are supposed to be the same, but it is not the case.
I checked the document but did not see any special preprocessing method for input/output of those conversion functions.

So why they are not the same?

Thanks.

**Comment by shijianjian** [comment]
After a quick glancing, I suspect it is related to those ```clamp``` functions.

@cceyda, can you take a look?

**Comment by cceyda** [comment]
Yes @shijianjian it is because of clipping done during `lab_to_rgb`. This is according to conversion standarts [[ref](https://www.w3.org/Graphics/Color/srgb)]
![image](https://user-images.githubusercontent.com/15624271/124231313-110c9700-db4b-11eb-9f83-ec09bde6d28a.png)

@hminle you can check our test for this exact thing [here](https://github.com/kornia/kornia/blob/25cb90b1775fa2244790cd8f46c6120f68106c6e/test/color/test_lab.py#L88) precision is within 1e-4. Let me know if this answers your question 😄

**Comment by edgarriba** [comment]
@cceyda @shijianjian should we have `clip==False` in `lab_to_rgb` ?

**Comment by cceyda** [comment]
@edgarriba This might lead to some problems if someone tries to save an image or pass it onto another (kornia) function that expects things in 0,1 range. Imo `clip=True` is a safer default.

**Comment by hminle** [comment]
> here

Hi @cceyda ,
I think this test could not solve my issue.
In the test, it converts `data` which is in `Lab` space to `RGB` space first, then does the conversion from `RGB` back to `Lab` again.

But if you do like this: first, initiate `data` in `RGB` space, convert it to `Lab`, then convert back to `RGB`, you will see the problem. (You can see my screenshot as an example)

For the function `kornia.color.rgb_to_lab`, its input is RGB in the range 0-1, but its output is `Lab` space, which has `L` channel in the range 0-100, and `a & b` channel in the range of -100 to 100.

![image](https://user-images.githubusercontent.com/16201681/124289772-ac3c4700-db20-11eb-92c2-22fba20af448.png)

**Comment by hminle** [comment]
Hi @cceyda ,

I found another test that solve the issue:
https://github.com/kornia/kornia/blob/25cb90b1775fa2244790cd8f46c6120f68106c6e/test/color/test_lab.py#L230

When I print them out, I see they are the same, but the `torch.allclose` cannot make it `True`
![image](https://user-images.githubusercontent.com/16201681/124291674-cecf5f80-db22-11eb-993c-a90aa1a1f48a.png)
