### ISSUE TITLE
Kornia Warnings Suppression won't work

### ISSUE THREAD

**Issue by stasbel** [kornia/kornia#1152]
## To Reproduce

```python3
import warnings
warnings.simplefilter('ignore')
import kornia
# DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
```

## Expected behavior

GaussianBlue warning would be suppressed.

## Environment

 - PyTorch Version: `1.7.1`
 - OS: `Linux`
 - How you installed PyTorch: `pip`
 - Python version: `3.8.10`

## Additional context

...

**Comment by shijianjian** [comment]
Can you try:
```python
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning) 
```

**Comment by stasbel** [comment]
Exactly the same result. I have already tried bunch of stuff, none of warnings filtering strategy seems to work.

**Comment by shijianjian** [comment]
This warning should be wrapped into ```__init__``` and indeed remember that I have fixed it already. Not sure why it is here.

A possible reason is that they logged in different loggers, so that we cannot catch it properly. Still, I haven't find a good solution for that. Will fix it in the code instead.

**Comment by shijianjian** [comment]
The deprecation warning has been moved inside the function in #1139 already. Please check out the master. I will close this issue for now.
