### ISSUE TITLE
[Feature request] Add 3D-SSIM

### ISSUE THREAD

**Issue by wendy-xiaozong** [kornia/kornia#1158]
## 🚀 Feature
3D-SSIM

## Motivation
SSIM and SSIMLoss are currently only supported in 2D in kornia. While it is common in medical imaging to compute SSIM on 3D volumes. In addition, 3D-SSIM is useful for video.

## Pitch
Adding 3D-SSIM

## Alternatives
N/A

## Additional context
N/A

**Comment by edgarriba** [comment]
@wendy-xiaozong that would be a nice feature. Do you have any implementation reference ?

**Comment by wendy-xiaozong** [comment]
Hey @edgarriba,

I did find a paper on 3D-SSIM ([3D-SSIM FOR VIDEO QUALITY ASSESSMENT](https://ieeexplore.ieee.org/document/6466936)) from the same author of the SSIM paper. To compute it, it appears that they are simply converting the 2D blocks to 3D.

I would be very happy to implement it because I need to use it anyway.

**Comment by shijianjian** [comment]
I found there are already some implementations on that topic, like [this](https://github.com/jinh0park/pytorch-ssim-3D). Probably, we can test against [scipy](https://stackoverflow.com/questions/53933528/ssim-for-3d-image-volume).

I do not have the access to the full paper now, but @wendy-xiaozong can you evaluate those implementations? It looks like the paper you mentioned has some more advanced features.

**Comment by wendy-xiaozong** [comment]
Hey @shijianjian, Thanks for finding those references! I will evaluate the 3D SSIM code with scipy.

For the paper I mentioned, I find [a pdf version](https://www.researchgate.net/profile/Kai-Zeng-9/publication/261386970_3D-SSIM_for_video_quality_assessment/links/5c9cebfd45851506d730632f/3D-SSIM-for-video-quality-assessment.pdf) online. So, they also use a width-adapted exponential weighting function applied upon sorted 3D block index instead of averaging it. But I cannot find the source code, although they did say in the paper there is a Matlab implementation online. I will just leave that alone.

**Comment by shijianjian** [comment]
Thanks for the paper. While I think we should have a proper design generic API that allows different weighting method. Please go for a PR if you are willing to do so!

**Comment by pri1311** [comment]
I could give this a shot.

**Comment by wendy-xiaozong** [comment]
Hi Priya, I found MONAI has implemented the 3D SSIM loss recently. It might be another good reference to start with: https://docs.monai.io/en/stable/losses.html#monai.losses.ssim_loss.SSIMLoss

Good luck!

Jueqi

**Comment by pri1311** [comment]
I like how Monai has only one exposed wrapper for both 2D and 3D data. Do we want to follow the same? Or have a different  SSIM3DLoss class?

**Comment by edgarriba** [comment]
I would start with different, later we think of merging if makes sense for us
