### ISSUE TITLE
Doesn't kornia.augmentation produce output tensor in range (0,1)?

### ISSUE THREAD

**Issue by ferric123** [kornia/kornia#1163]
```python
extra_aug = nn.Sequential(
    kornia.augmentation.ColorJitter(p=0.4, brightness=0.4, contrast=0.4, saturation=0.2, hue=0.1, return_transform=False),
    #kornia.augmentation.Normalize(mean=0.5*torch.ones(3), std=torch.ones(3), p=1.0, return_transform=False),
    kornia.augmentation.RandomSolarize(0.1, 0.1, p=0.3, return_transform=False),
    #kornia.augmentation.Normalize(mean=0.5*torch.ones(3), std=torch.ones(3), p=1.0, return_transform=False),
    kornia.augmentation.RandomEqualize(p=0.2, return_transform=False),
 )
```

I took these for data augmentation, but I got this following error message:
xxx/kornia/augmentation/augmentation.py", line 1793, in apply_transform
return equalize(input),
 xxxxx/kornia/enhance/adjust.py", line 675, in _scale_channel raise ValueError(f"Values in the input tensor must greater or equal to 0.0. Found {min_.item()}.")
ValueError: Values in the input tensor must greater or equal to 0.0. Found -2.3047420978546143.

**Comment by shijianjian** [comment]
Can you check if your input is in [0, 1]? I cannot reproduce with the input of

```python
x = torch.randn((2, 3, 10, 10))
x = (x - x.min()) / (x.max() - x.min())
```

**Comment by ferric123** [comment]
My input is in [0, 1], but now I get where the issue comes from: it's caused by kornia.augmentation.RandomEqualize(p=0.2, return_transform=False). Everything went fine after removing this augmentation...

**Comment by shijianjian** [comment]
Operators like ```RandomEqualize``` can only accept input ranges [0, 1], so you have to make sure ```Normalize``` operation happens lastly.

**Comment by edgarriba** [comment]
@ferric123 is it solved ?
