### ISSUE TITLE
Random horizontal and vertical flips doesn't work with bbox

### ISSUE THREAD

**Issue by hal-314** [kornia/kornia#1165]
## 🐛 Bug

Random{Horizontal/Vertical}Flip for Transform2D and Transform3D doesn't work. See image attached.

EDIT: RandomRotation always shows the same behavior. RandomCrop, CenterCrop, RandomResizedCrop, RandomErasing and RandomPerspective are fine (checked 2D version).

## To Reproduce

!wget https://tinypng.com/images/social/website.jpg -O panda.jpg
```python
from kornia import augmentation as K

tfm= K.AugmentationSequential(
    K.RandomVerticalFlip(p=1.)
    data_keys=["input", "bbox"]),
    return_transform=False,
    same_on_batch=False
)


img = cv2.imread("panda.jpg", cv2.IMREAD_COLOR)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
h, w = img.shape[:2]

image= image_to_tensor(img).float() / 255.

bbox = torch.tensor([[[355,10],[660,10],[660,250],[355,250]]])
tfm(image, bbox.float())
```
Original image:
![image](https://user-images.githubusercontent.com/22135069/126617395-e0b93f15-3d7f-43e6-9bf3-bcc75cbdefbe.png)

Transformed image:
![image](https://user-images.githubusercontent.com/22135069/126616611-fba60fc4-588e-4708-b841-dc2274b0f1b9.png)

Original box (in xyxy): tensor([[355.,  10., 660., 250.]])
Transformed box (in xyxy): tensor([[ 355., -246.,  660.,   -6.]])

## Expected behavior

![image](https://user-images.githubusercontent.com/22135069/126616504-1d050e18-dd02-4952-b41d-421dc71e9b88.png)

Correct transformed box (in xyxy): tensor([[355., 260., 660., 500.]])
## Environment

pytorch 1.8.1
Kornia 0.5.6

## Addition comments
Shortly, I'll make a PR

**Comment by edgarriba** [comment]
@hal-314 please, make sure to add some tests in PR that fixes the issue

**Comment by shijianjian** [comment]
Closed by #1166

**Comment by hal-314** [comment]
@shijianjian Could you reopen the issue or create a separated issue for RandomRotation bug. #1166 fixed random flip cases, not rotation.

**Comment by edgarriba** [comment]
@shijianjian

**Comment by johnnv1** [comment]
I can't tell since which release, but this is working on 0.6.12 😄
