### ISSUE TITLE
[docs] Missing range of Lab image in rgb_to_lab conversion

### ISSUE THREAD

**Issue by vadimkantorov** [kornia/kornia#1167]
`rgb_to_hsv` specified output range, but `rgb_to_lab` does not

**Comment by edgarriba** [comment]
@vadimkantorov we are aware of it - @cceyda is working on that part I believe.

**Comment by shijianjian** [comment]
Hi, thanks for reporting. Are you willing to go for a PR to improve the docs?

**Comment by SravanChittupalli** [comment]
@edgarriba @shijianjian  Can you assign this to me? I will go for the PR to improve the docs.

**Comment by edgarriba** [comment]
@SravanChittupalli done - thanks !
