### ISSUE TITLE
Got kernel_size error when i resize my images with antialias=True

### ISSUE THREAD

**Issue by Daiver** [kornia/kornia#1179]
## 🐛 Bug

Hi! When i tried to run `kornia.resize` with antialias=True i faced with following error

```
TypeError: kernel_size must be an odd positive integer. Got 6
```

It seems to me that something wrong with kernel size selection heuristic `ks = int(2.0 * 2 * sigmas[0] + 1), int(2.0 * 2 * sigmas[1] + 1)` (kornia/geometry/transform/affwrap.py line 588). My input image size is `(512, 1536)` and i want to resize it to `(384, 1152)`, downsampling factor (line 576) is `1.3333333` which leads to kernel size 6. 

Btw, if i change heuristic to "true 3 sigma" (`ks = int(3.0 * 2 * sigmas[0] + 1), int(3.0 * 2 * sigmas[1] + 1)`) everything works fine. 

Please feel free to ask additional information. Thank you in advance! 

## To Reproduce

Just run minimum example

```python
images = torch.zeros((1, 3, 512, 1536))
target_size = (384, 1152)
kornia.resize(images, target_size, antialias=True)
# TypeError: kernel_size must be an odd positive integer. Got 6
```
## Expected behavior

Result of regular `kornia.resize` followed by appropriate gaussian filter.

## Environment

```
PyTorch version: 1.9.0+cu102
CUDA used to build PyTorch: 10.2
OS: Ubuntu 20.04.2 LTS (x86_64)
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0] (64-bit runtime)
Is CUDA available: True
Versions of relevant libraries:
[pip3] numpy==1.21.0
[pip3] torch==1.9.0
kornia==0.5.6
```

**Comment by shijianjian** [comment]
@ducha-aiki Can you take a look?

**Comment by ducha-aiki** [comment]
Hi,

Sure, will check today.

**Comment by ducha-aiki** [comment]
@Daiver thanks for the catch!

**Comment by Daiver** [comment]
@ducha-aiki thank you for quick fix!
