### ISSUE TITLE
kernel size in resize is not odd

### ISSUE THREAD

**Issue by zjhthu** [kornia/kornia#1182]
## 🐛 Bug

The [kernel size in the resize function](https://github.com/kornia/kornia/blob/master/kornia/geometry/transform/affwarp.py#L588) can be not odd, and thus result in an error in the following  gaussian_blur2d. 

A quick fix can be `ks = int(2 * sigmas[0]) * 2 + 1 , int( 2 * sigmas[1]) * 2 + 1`

**Comment by shijianjian** [comment]
Probably related to #1179. 

/cc @ducha-aiki

**Comment by ducha-aiki** [comment]
Fixed with #1183
