### ISSUE TITLE
[Feature] Add padding equal to None option for SSIM to match the original MATLAB implementation

### ISSUE THREAD

**Issue by wendy-xiaozong** [kornia/kornia#1204]
## 🚀 Feature
Add padding equal to None option for SSIM  to match the original MATLAB implementation

## Motivation
I am comparing `kornia` and `skimage` for computing SSIM. I find that there is always a slight difference between the two results. I read the code and found that the differences come from `kornia` using the reflect padding in the gaussian weighting function to keep the size of the image the same, while `skimage` doesn't use padding here. I also check [the MATLAB implementation](http://www.cns.nyu.edu/~lcv/ssim/ssim_index.m) of SSIM from the original authors, they also don't use padding. 

When I remove the reflect padding in `kornia`, the SSIM would return a more similar result with `skimage`.  So I think it would be better if we can add an option in the SSIM in `kornia` to be able to remove padding. 

The related colab link is as following: https://colab.research.google.com/drive/1JCDQn_OWbm52hyDadKiU1UpwB3glGY5f?usp=sharing

A lot of thanks for this wonderful project!

**Comment by edgarriba** [comment]
@wendy-xiaozong thanks for reporting this. I believe we need to modify this part of the code in `filter2d`
https://github.com/kornia/kornia/blob/f56eec6a8f2dddfbb9a918f979a9f7e83b289ec1/kornia/filters/filter.py#L96-L98

Any thoughts here @ducha-aiki ? possibly we need to a `apply_padding` param

**Comment by ducha-aiki** [comment]
I believe, that can be done a bit simpler - pass padding type to the SSIM and then crop out the part of "valid" convolution.

**Comment by edgarriba** [comment]
Definitely-go ahead
