### ISSUE TITLE
Inverse of Extract Tensor Patches

### ISSUE THREAD

**Issue by isaaccorley** [kornia/kornia#1297]
## 🚀 Feature

A `kornia.contrib.CombineTensorPatches` module which performs the inverse of `kornia.contrib.ExtractTensorPatches`

## Motivation

In remote sensing it's common to work with imagery which can be relatively large in shape (e.g. 3000x3000+). Therefore during training/inference images are broken into patches. After feeding to the model, it's necessary to combine the patches back to a single image.

## Pitch

A `kornia.contrib.CombineTensorPatches` which performs the inverse of `kornia.contrib.ExtractTensorPatches`, assuming a stride ~~of 1~~ the same as the window size.

## Alternatives

We could implement this functionality in our own library, however we feel that it is general-purpose enough to belong in Kornia.

## Additional context

I implemented something similar [here](https://github.com/isaaccorley/torchgeo/blob/514ef025240c44bbba597fd1849006b7beb4fa5e/torchgeo/transforms/transforms.py#L154-L206) although using `einops` and with some custom pieces for handling our data structures.

We would like to use such functionality in `torchgeo`, a PyTorch domain library for geospatial data - https://github.com/microsoft/torchgeo.

@adamjstewart @calebrob6

**Comment by shijianjian** [comment]
I have a naive implementation in:
https://github.com/kornia/kornia/blob/9f4b0bf7ff87ab424569049a1d9635784aa957d5/kornia/augmentation/container/patch.py#L193-L220

**Comment by edgarriba** [comment]
@shijianjian possibly it's worth to expose. Like better the name in torchgeo

**Comment by isaaccorley** [comment]
@shijianjian This is great! Seems like it could easily be in its own Module if it forced `grid_size` to not be optional and removed this:

```python
if grid_size is None: 
   grid_size = self.grid_size 
```

**Comment by edgarriba** [comment]
@isaaccorley feel free to give it a shoot with a PR

**Comment by edgarriba** [comment]
@shijianjian can we close this?
