### ISSUE TITLE
color.rgb_to_hsv can't be converted to simplified onnx model

### ISSUE THREAD

**Issue by simetin** [kornia/kornia#1327]
### Describe the bug

I've created a simple NN that simply convert RGB to HSV using the color.rgb_to_hsv() function. When I try to convert the model to Onnx and then simplify it (or convert it to blob format using this converter: [http://blobconverter.luxonis.com](http://blobconverter.luxonis.com)) I get this error message: This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (3) of operator (CumSum) in node (CumSum_4) is invalid.

### Reproduction steps

```bash
Use this code to reproduced the error:


import torch
from torch import nn

import kornia

import onnx
from onnxsim import simplify

class rgb2hsv(nn.Module):
    def forward(self, image):

        hsv_tensor = kornia.color.rgb_to_hsv(image)

        return hsv_tensor

X = torch.ones((1, 3, 300, 300), dtype=torch.float32)
torch.onnx.export(
    rgb2hsv(),
    (X), # Dummy input for shape
    "model.onnx",
    opset_version=12,
    do_constant_folding=True,
)


onnx_model = onnx.load("model.onnx")
model_simpified, check = simplify(onnx_model)
onnx.save(model_simpified, "model_simplified.onnx
```
```


### Expected behavior

Expecting the model to convert correctly

### Environment

```shell
- PyTorch Version (e.g., 1.0): 1.9.1
- OS (e.g., Linux): MacOS
- How you installed PyTorch (`conda`, `pip`, source): Pip
- Build command you used (if compiling from source): NA
- Python version: 3.8
- CUDA/cuDNN version: NA
- GPU models and configuration: NA
- Any other relevant information: NA
```

**Comment by edgarriba** [comment]
@simetin thanks for reporting. Ping to @Luxonis-Brandon - Not sure if it's a kornia or directly pytorch limitation ?

**Comment by Luxonis-Brandon** [comment]
Great question @edgarriba .  This is where I start to lose know-how.  I think either @tersekmatija and/or @PINTO0309 might know here.  I think I recall this before though with PyTorch.  Don't recall what the workaround is though (and/or if I'm recalling this correctly).

**Comment by simetin** [comment]
With the default function rgb_to_hsv function I get this error when I try to convert to Onnx model: 
```
  if len(image.shape) < 3 or image.shape[-3] != 3:
Traceback (most recent call last):
  File "nn_rgb2hsv.py", line 29, in <module>
    model_simpified, check = simplify(onnx_model)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 492, in simplify
    model = fixed_point(model, infer_shapes_and_optimize, constant_folding)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 393, in fixed_point
    x = func_b(x)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 482, in constant_folding
    res = forward_for_node_outputs(model,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 229, in forward_for_node_outputs
    res = forward(model,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onnxsim/onnx_simplifier.py", line 197, in forward
    sess = rt.InferenceSession(model.SerializeToString(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 324, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in _create_inference_session
```


If I take the source code and remove this if statement I don't get any error when I convert to Onnx only when I try to simplify it or convert it to blob format.

**Comment by cceyda** [comment]
I'm not familiar with onnx but it might be `image.shape[-3]`  do negative indexes cause problems?

**Comment by tersekmatija** [comment]
Hey, so looking at OpenVINO documentation, CumSum operator only supports tensors of numeric inputs: https://docs.openvinotoolkit.org/latest/openvino_docs_ops_arithmetic_CumSum_3.html

Looking at this two lines [here](https://github.com/kornia/kornia/blob/c04b5890f4fa95d29d2213f07eef3cfc58a7d191/kornia/color/hsv.py#L39-L40):
```
    maxc_mask = image == maxc.unsqueeze(-3)
    _, max_indices = ((maxc_mask.cumsum(-3) == 1) & maxc_mask).max(-3)
```
you can see that CumSum is executed on a tensor of booleans. I am assuming that it's not automatically converted to 0s and 1s like you would expect, and results in the given error.

Can you maybe try copying the function and changing the type of the `maxc_mask` to a numeric type before calling the CumSum, and then exporting this new function?

**Comment by PINTO0309** [comment]
My workaround for now. There are causes for errors in both kornia and onnx-simplifier. Thus, it removes the error sources for both kornia and onnx-simplifier.

- kornia
  - myriad_compilier fails due to the fact that CumSum is set to a negative axis. Exporting to ONNX and converting to OpenVINO IR can be done without problems. Therefore, I have created an approximation logic that does not make heavy use of boolean masks.

- onnx-simplifier
  - An error occurs when performing an internal optimization operation. The last two lines of logic are essentially unnecessary, but I left them in to illustrate that there is an option to disable the optimization logic of onnx-simplifier. model.onnx and model_non-opt.onnx will generate the exact same file.

```python
import torch
from torch import nn
import kornia

import onnx
from onnxsim import simplify

class rgb2hsv(nn.Module):
    def forward(self, image):
        hsv_tensor = kornia.color.rgb_to_hsv(image)
        return hsv_tensor

class rgb2hsv_custom(nn.Module):
    def forward(self, image, epsilon=1e-10):
        assert(image.shape[1] == 3)
        r, g, b = image[:, 0], image[:, 1], image[:, 2]
        max_rgb, argmax_rgb = image.max(1)
        min_rgb, argmin_rgb = image.min(1)
        max_min = max_rgb - min_rgb + epsilon
        h1 = 60.0 * (g - r) / max_min + 60.0
        h2 = 60.0 * (b - g) / max_min + 180.0
        h3 = 60.0 * (r - b) / max_min + 300.0
        h = torch.stack((h2, h3, h1), dim=0).gather(dim=0, index=argmin_rgb.unsqueeze(0)).squeeze(0)
        s = max_min / (max_rgb + epsilon)
        v = max_rgb
        return torch.stack((h, s, v), dim=1)

X = torch.ones((1, 3, 300, 300), dtype=torch.float32)

torch.onnx.export(
    rgb2hsv_custom(),
    (X),
    "model.onnx",
    opset_version=12,
    do_constant_folding=True,
)
onnx_model = onnx.load("model.onnx")
model_simpified, check = simplify(onnx_model, perform_optimization=False)
onnx.save(model_simpified, "model_non-opt.onnx")
```
Note that I have not firmly verified that the RGB to HSV conversion custom logic works correctly. This procedure does not dare to optimize ONNX and will produce a very redundant model. Therefore, if you do not like it, please ignore it.

- ONNX
![Screenshot 2021-09-28 11:18:32](https://user-images.githubusercontent.com/33194443/135011701-e7755303-ba9a-4e2a-83ef-8faea5033f9c.png)

- OpenVINO
![Screenshot 2021-09-28 11:20:12](https://user-images.githubusercontent.com/33194443/135011843-4822a723-466d-44ae-928a-679bd58ec920.png)

- Blob
[model.blob.tar.gz](https://github.com/kornia/kornia/files/7240492/model.blob.tar.gz)


By the way, I don't know what kind of tool **`kornia`** is.

**Comment by edgarriba** [comment]
@simetin thanks so much for the detailed answer. Kornia is a re-implementation of opencv using native torch tensors meant for training deep nets.

Please, check https://github.com/kornia/kornia/pull/1329 - I adapted your rgb2hsv functionality with few tweaks to fit our conventions (batched and assuming 0..2pi inputs, etc). Maybe we could switch the conversation there (there's one failing test)

Besides, what's this good looking tool you use for the visualization of the graph ?

**Comment by PINTO0309** [comment]
@edgarriba 
>Besides, what's this good looking tool you use for the visualization of the graph ?

It is a tool called Netron.
https://netron.app/

**Comment by simetin** [comment]
The answer of @PINTO0309 is working great ! A big thank you for your time. I believe this issue can be close.

**Comment by edgarriba** [comment]
@simetin let's keep it open until we merge #1329. We need to create a proper mechanism to test from kornia side that after we export to onnx, later is will be usable. Because in this case, the exporter was was working and later you found that error.

**Comment by simetin** [comment]
@PINTO0309 the Hue is way bigger than it's supposed to be (e.g. 437.84 instead of 0.3962). Any possible typo ?

**Comment by PINTO0309** [comment]
@simetin Test according to the final implementation #1329 of the maintainer.
```python
import torch
from torch import nn
import math
from pprint import pprint
import numpy as np
np.set_printoptions(precision=15, suppress=True)

class rgb2hsv_custom(nn.Module):
    def forward(self, image, eps=1e-10):
        image = image * 255.  # hack because we assume [0/1] input
        r, g, b = image[..., 0, :, :], image[..., 1, :, :], image[..., 2, :, :]
        max_rgb, argmax_rgb = image.max(-3)
        min_rgb, argmin_rgb = image.min(-3)
        max_min = max_rgb - min_rgb + eps
        h1 = 60.0 * (g - r) / max_min + 60.0
        h2 = 60.0 * (b - g) / max_min + 180.0
        h3 = 60.0 * (r - b) / max_min + 300.0
        h = torch.stack((h2, h3, h1), dim=-3).gather(dim=-3, index=argmin_rgb.unsqueeze(-3)).squeeze(-3)
        h = h * (2. * math.pi / 360)  # hack because we return 0/2pi output
        s = max_min / (max_rgb + eps)
        v = max_rgb / 255  # hack because we return 0/1
        return torch.stack((h, s, v), dim=-3)

rgb2hsv = rgb2hsv_custom()

print('image shape: (C,H,W) = (3,2,2)')

RGB1 = torch.tensor(
    [
        [
            [0,0],
            [0,0]
        ],
        [
            [0,0],
            [0,0]
        ],
        [
            [0,0],
            [0,0]
        ]
    ]
)
print('========== RGB1:')
pprint(rgb2hsv(RGB1).to('cpu').detach().numpy())
RGB2 = torch.tensor(
    [
        [
            [255,255],
            [255,255]
        ],
        [
            [255,255],
            [255,255]
        ],
        [
            [255,255],
            [255,255]
        ]
    ]
)
print('========== RGB2:')
pprint(rgb2hsv(RGB2).to('cpu').detach().numpy())
RGB3 = torch.tensor(
    [
        [
            [255,255],
            [255,255]
        ],
        [
            [0,0],
            [0,0]
        ],
        [
            [0,0],
            [0,0]
        ]
    ]
)
print('========== RGB3:')
pprint(rgb2hsv(RGB3).to('cpu').detach().numpy())
RGB4 = torch.tensor(
    [
        [
            [128,128],
            [128,128]
        ],
        [
            [0,0],
            [0,0]
        ],
        [
            [1,1],
            [1,1]
        ]
    ]
)
print('========== RGB4:')
pprint(rgb2hsv(RGB4).to('cpu').detach().numpy())
RGB5 = torch.tensor(
    [
        [
            [1,1],
            [1,1]
        ],
        [
            [255,255],
            [255,255]
        ],
        [
            [254,254],
            [254,254]
        ]
    ]
)
print('========== RGB5:')
pprint(rgb2hsv(RGB5).to('cpu').detach().numpy())
```
```
image shape: (C,H,W) = (3,2,2)
========== RGB1:
array([[[3.1415927, 3.1415927],
        [3.1415927, 3.1415927]],

       [[1.       , 1.       ],
        [1.       , 1.       ]],

       [[0.       , 0.       ],
        [0.       , 0.       ]]], dtype=float32)
========== RGB2:
array([[[  3.1415927        ,   3.1415927        ],
        [  3.1415927        ,   3.1415927        ]],

       [[  0.000000000000002,   0.000000000000002],
        [  0.000000000000002,   0.000000000000002]],

       [[255.               , 255.               ],
        [255.               , 255.               ]]], dtype=float32)
========== RGB3:
array([[[  6.2831855,   6.2831855],
        [  6.2831855,   6.2831855]],

       [[  1.       ,   1.       ],
        [  1.       ,   1.       ]],

       [[255.       , 255.       ],
        [255.       , 255.       ]]], dtype=float32)
========== RGB4:
array([[[  6.275004,   6.275004],
        [  6.275004,   6.275004]],

       [[  1.      ,   1.      ],
        [  1.      ,   1.      ]],

       [[128.      , 128.      ],
        [128.      , 128.      ]]], dtype=float32)
========== RGB5:
array([[[  3.1374698 ,   3.1374698 ],
        [  3.1374698 ,   3.1374698 ]],

       [[  0.99607843,   0.99607843],
        [  0.99607843,   0.99607843]],

       [[255.        , 255.        ],
        [255.        , 255.        ]]], dtype=float32)
```

**Comment by edgarriba** [comment]
> @simetin There are various definitions of the H, S, and V value ranges. Therefore, I just gave you an example last time. Test according to the final implementation #1329 of the maintainer.
> 
> ```python
> import torch
> from torch import nn
> import math
> from pprint import pprint
> import numpy as np
> np.set_printoptions(precision=15, suppress=True)
> 
> class rgb2hsv_custom(nn.Module):
>     def forward(self, image, eps=1e-10):
>         image = image * 255.  # hack because we assume [0/1] input
>         r, g, b = image[..., 0, :, :], image[..., 1, :, :], image[..., 2, :, :]
>         max_rgb, argmax_rgb = image.max(-3)
>         min_rgb, argmin_rgb = image.min(-3)
>         max_min = max_rgb - min_rgb + eps
>         h1 = 60.0 * (g - r) / max_min + 60.0
>         h2 = 60.0 * (b - g) / max_min + 180.0
>         h3 = 60.0 * (r - b) / max_min + 300.0
>         h = torch.stack((h2, h3, h1), dim=-3).gather(dim=-3, index=argmin_rgb.unsqueeze(-3)).squeeze(-3)
>         h = h * (2. * math.pi / 360)  # hack because we return 0/2pi output
>         s = max_min / (max_rgb + eps)
>         v = max_rgb / 255  # hack because we return 0/1
>         return torch.stack((h, s, v), dim=-3)
> 
> rgb2hsv = rgb2hsv_custom()
> 
> print('image shape: (C,H,W) = (3,2,2)')
> 
> RGB1 = torch.tensor(
>     [
>         [
>             [0,0],
>             [0,0]
>         ],
>         [
>             [0,0],
>             [0,0]
>         ],
>         [
>             [0,0],
>             [0,0]
>         ]
>     ]
> )
> print('========== RGB1:')
> pprint(rgb2hsv(RGB1).to('cpu').detach().numpy())
> RGB2 = torch.tensor(
>     [
>         [
>             [255,255],
>             [255,255]
>         ],
>         [
>             [255,255],
>             [255,255]
>         ],
>         [
>             [255,255],
>             [255,255]
>         ]
>     ]
> )
> print('========== RGB2:')
> pprint(rgb2hsv(RGB2).to('cpu').detach().numpy())
> RGB3 = torch.tensor(
>     [
>         [
>             [255,255],
>             [255,255]
>         ],
>         [
>             [0,0],
>             [0,0]
>         ],
>         [
>             [0,0],
>             [0,0]
>         ]
>     ]
> )
> print('========== RGB3:')
> pprint(rgb2hsv(RGB3).to('cpu').detach().numpy())
> RGB4 = torch.tensor(
>     [
>         [
>             [128,128],
>             [128,128]
>         ],
>         [
>             [0,0],
>             [0,0]
>         ],
>         [
>             [1,1],
>             [1,1]
>         ]
>     ]
> )
> print('========== RGB4:')
> pprint(rgb2hsv(RGB4).to('cpu').detach().numpy())
> RGB5 = torch.tensor(
>     [
>         [
>             [1,1],
>             [1,1]
>         ],
>         [
>             [255,255],
>             [255,255]
>         ],
>         [
>             [254,254],
>             [254,254]
>         ]
>     ]
> )
> print('========== RGB5:')
> pprint(rgb2hsv(RGB5).to('cpu').detach().numpy())
> ```
> 
> ```
> image shape: (C,H,W) = (3,2,2)
> ========== RGB1:
> array([[[3.1415927, 3.1415927],
>         [3.1415927, 3.1415927]],
> 
>        [[1.       , 1.       ],
>         [1.       , 1.       ]],
> 
>        [[0.       , 0.       ],
>         [0.       , 0.       ]]], dtype=float32)
> ========== RGB2:
> array([[[  3.1415927        ,   3.1415927        ],
>         [  3.1415927        ,   3.1415927        ]],
> 
>        [[  0.000000000000002,   0.000000000000002],
>         [  0.000000000000002,   0.000000000000002]],
> 
>        [[255.               , 255.               ],
>         [255.               , 255.               ]]], dtype=float32)
> ========== RGB3:
> array([[[  6.2831855,   6.2831855],
>         [  6.2831855,   6.2831855]],
> 
>        [[  1.       ,   1.       ],
>         [  1.       ,   1.       ]],
> 
>        [[255.       , 255.       ],
>         [255.       , 255.       ]]], dtype=float32)
> ========== RGB4:
> array([[[  6.275004,   6.275004],
>         [  6.275004,   6.275004]],
> 
>        [[  1.      ,   1.      ],
>         [  1.      ,   1.      ]],
> 
>        [[128.      , 128.      ],
>         [128.      , 128.      ]]], dtype=float32)
> ========== RGB5:
> array([[[  3.1374698 ,   3.1374698 ],
>         [  3.1374698 ,   3.1374698 ]],
> 
>        [[  0.99607843,   0.99607843],
>         [  0.99607843,   0.99607843]],
> 
>        [[255.        , 255.        ],
>         [255.        , 255.        ]]], dtype=float32)
> ```

@PINTO0309 I think that there are still some inconsistencies with opencv - which is what we take as reference for now.
