### ISSUE TITLE
RuntimeError: linalg_solve: For batch 0: U(8,8) is zero, singular U.

### ISSUE THREAD

**Issue by ShiyangZhang** [kornia/kornia#1404]
### Describe the bug

got a runtime error when I test warp_perspective

### Reproduction steps

run
```bash


def test_warp_perspective()        :
    import kornia as K
    import torch

    input = torch.zeros(1,3,1000,1000).cuda()

    print(input.shape)

    h, w = 64, 128  # destination size
    points_src = torch.tensor([[
    [100., 100.], [200., 100.], [200., 200.], [100., 100.],
    ]])

    # points_src = torch.tensor([[
    # [125., 150.], [562., 40.], [562., 282.], [54., 328.],
    # ]])

    points_dst = torch.tensor([[
        [0., 0.], [w - 1., 0.], [w - 1., h - 1.], [0., h - 1.],
    ]])
    print(points_src, points_dst)
    # compute perspective transform
    M: torch.tensor = K.get_perspective_transform(points_src, points_dst)

    print(input.shape, M)
    # warp the original image by the found transform
    img_warp: torch.tensor = K.warp_perspective(input, M.cuda(), dsize=(h, w))
    print(img_warp.shape)

if __name__ == "__main__":
    test_warp_perspective()


```

Traceback (most recent call last):
  File "test.py", line 229, in <module>
    test_warp_perspective()
  File "test.py", line 214, in test_warp_perspective
    M: torch.tensor = K.get_perspective_transform(points_src, points_dst)
  File "/usr/local/lib/python3.6/dist-packages/kornia/geometry/transform/imgwarp.py", line 259, in get_perspective_transform
    X, _ = _torch_solve_cast(b, A)
  File "/usr/local/lib/python3.6/dist-packages/kornia/utils/helpers.py", line 100, in _torch_solve_cast
    out = solve(A.to(dtype), input.to(dtype))
RuntimeError: linalg_solve: For batch 0: U(8,8) is zero, singular U.
```
```

### Expected behavior

no RuntimeError

### Environment

```shell
>>> torch.__version__
'1.9.1+cu102'
>>> kornia.__version__
'0.5.11'
```
```


### Additional context

_No response_

**Comment by ShiyangZhang** [comment]
my mistake. points_src = torch.tensor([[
    [100., 100.], [200., 100.], [200., 200.], [100., 200.],
    ]])

**Comment by shijianjian** [comment]
Ah, I have checked the code. It will convert the dtypes automatically to ```float32``` and ```float64```. Then I am confused that why floating points worked but not integers.

@edgarriba I did not get it. How could floating points effect on collinear points?

https://github.com/kornia/kornia/blob/1686165ef37f0b6b55290933fa6d64d7137712c7/kornia/utils/helpers.py#L88-L102
