### ISSUE TITLE
Deprecation warning when using %matplotlib widget

### ISSUE THREAD

**Issue by paloha** [kornia/kornia#1425]
### Describe the bug

This is rather weird problem. I am using `%matplotlib widget` in Jupyter Lab. All works well until I import `kornia`.
Then an annoying deprecation warning starts appearing and must be suppressed with `warnings.`  It would not be so much of a problem if it is clear it comes from kornia. But it is not at all clear and I thought I had some problems with my packages. I have described the issue in the `ipympl` project if you are interested. If not, just close the issue. Thx
https://github.com/matplotlib/ipympl/issues/236#issuecomment-949951663

### Reproduction steps

```bash
1. All steps are detailed in https://github.com/matplotlib/ipympl/issues/236#issuecomment-949951663
```

### Expected behavior

Either no warning or message it comes from kornia.

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- Kornia Version: 0.6.0 installed via pip
- PyTorch Version (e.g., 1.0): 1.10
- OS (e.g., Linux): Ubuntu
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source): -
- Python version: 3.8.10
- CUDA/cuDNN version: -
- GPU models and configuration: -
- Any other relevant information:
```

**Comment by johnnv1** [comment]
@paloha this still occurs in the lasts versions of kornia?

**Comment by paloha** [comment]
@johnnv1 Hello there. I've tested it just now and there is no more weird warnings.

```
PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 22 2023, 10:22:35)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-100-generic-x86_64-with-glibc2.29
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
```
