### ISSUE TITLE
[Feature request] Debayer and decimation in single step

### ISSUE THREAD

**Issue by copaah** [kornia/kornia#1444]
## 🚀 Feature

A common image signal processing (ISP) step in most camera pipelines are to use a bayer filter to get color images from raw pixel values. Kornia already has conversions from bayer to color images. In computer vision it is often necessary to downscale images for computational reasons or because it yields improved results (e.g. in stereo pipelines it can be considered a regularization technique). The straightforward ISP is then to do `Bayer Image -> Color Image -> Resized Color Image`.

This ISP pipeline, however, has redundant computational steps and erodes the raw signal by successive interpolation steps.

A better approach is to do debayering and resizing/decimation in one step.

Consider the standard `rggb` pattern:

-------
R   | G1
G2 | B
-------

A fast and simple approach to get downsampled color images is to simply extract the three color channels directly to a downscaled color image:

-----
R (G1+G2)/2 B
-----

This can be very effeciently implemented in pytorch and as an additional benefit, this contains the full raw signal in the red and blue channels and only slightly erodes it in the green channel.

## Motivation

To enable more research into how ISPs affect computer vision, Kornia can implement simple and easy to use functionality for common ISP steps.

## Pitch

In the `kornia.color` module implement one function:

```
def rgb_to_raw_2x2_downscaled(image: torch.Tensor, cfa: CFA) -> torch.Tensor
```
That will return the downscaled color image from the raw bayer image.

## Alternatives

N/A

## Additional context

See following papers for more info:

* https://ieeexplore.ieee.org/abstract/document/9385089
* https://hal.archives-ouvertes.fr/hal-00683233/document

I can contribute this functionality or supervise anyone who wants to contribute.

**Comment by edgarriba** [comment]
@copaah check https://github.com/kornia/kornia/blob/master/kornia/color/raw.py /cc @oskarflordal @cceyda

**Comment by oskarflordal** [comment]
Yes, it should be straight forward and fairly common thing to do, I suppose. The function is essentially taking the BG generated here
https://github.com/kornia/kornia/blob/master/kornia/color/raw.py#L64
and adding the two green samples from here https://github.com/kornia/kornia/blob/master/kornia/color/raw.py#L144
and stacking the 3 channels together.

**Comment by copaah** [comment]
@oskarflordal 

Yes, exactly. This is also what the ROS Image Pipeline does [here](https://github.com/ros-perception/image_pipeline/blob/71d537a50bf4e7769af513f4a3d3df0d188cfa05/image_proc/src/nodelets/crop_decimate.cpp#L120).

Should be a very easy PR.
