### ISSUE TITLE
[Code health] Streamline PinholeCamera and StereoCamera modules

### ISSUE THREAD

**Issue by copaah** [kornia/kornia#1447]
## 🚀 Feature
Ideally the `StereoCamera` class should be initialized by two `PinholeCamera`s instead of two `torch.Tensor`. This will be a breaking change to the `StereoCamera` API and I suspect that the `PinholeCamera` might have to change a little as well.

This ticket is to track this work.

Ideally the test code should also be aligned such that the `test_pinhole.py` and `test_stereo.py` can share pytest fixtures for focal lengths, principal points and other camera parameters.

## Motivation

Improve the API for `StereoCamera` and general improvement of code health.

## Pitch

I would like to see the `StereoCamera` initializer signature to be changed to:

```

class StereoCamera:
    def __init__(self, rectified_left_camera: PinholeCamera, rectified_right_camera: PinholeCamera):
```

And associated required changes to both the `StereoCamera` and `PinholeCamera` implementation.

## Alternatives

Leave as is.

**Comment by johnnv1** [comment]
@edgarriba @cjpurackal

**Comment by edgarriba** [comment]
the existing PinholeCamera is gonna be deprecated soon in favour of [`kornia.sensors.CameraModel`](https://kornia.readthedocs.io/en/latest/sensors.camera.html#kornia.sensors.camera.CameraModel). When that happens   and there's interest we can reopen this ticket.
