### ISSUE TITLE
TrivialAugment and RandAugment

### ISSUE THREAD

**Issue by gau-nernst** [kornia/kornia#1499]
## 🚀 Feature

Implement TrivialAugment and RandAugment

Links to papers:

- TrivialAugment: https://arxiv.org/abs/2103.10158
- RandAugment: https://arxiv.org/abs/1909.13719

## Motivation

I saw that AutoAugment has already been added here https://github.com/kornia/kornia/issues/549. It will be great if Kornia can support RandAugment and TrivialAugment also.

Recently the torchvision team also used TrivialAugment to achieve better results for their ResNet models ([blog](https://pytorch.org/blog/how-to-train-state-of-the-art-models-using-torchvision-latest-primitives/)). Supporting these augmentations will help others train better models with Kornia also.

## Pitch

torchvision's implementation can be found here https://github.com/pytorch/vision/blob/main/torchvision/transforms/autoaugment.py. We can port the code over to Kornia?

I'm not very familiar with the Kornia library. There might be some differentiability issues?

## Additional context

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by edgarriba** [comment]
@gau-nernst the [`AugmentationSequential`](https://kornia.readthedocs.io/en/latest/augmentation.container.html#kornia.augmentation.container.AugmentationSequential) already supports the feature to apply randomly groups of augmentations. The missing feature here is that we don't have defined fixed policies for open-source datasets, however, its relative simple to create your own ones. If needed, we can resume an old Pr that @shijianjian started around this topic.

**Comment by shijianjian** [comment]
@miquelmarti will give a hand to this. Probably start with TrivialAugment, which is intuitive.

**Comment by edgarriba** [comment]
this was already merged:
- https://kornia.readthedocs.io/en/latest/augmentation.auto.html#kornia.augmentation.auto.RandAugment
- https://kornia.readthedocs.io/en/latest/augmentation.auto.html#kornia.augmentation.auto.TrivialAugment

**Comment by ds2268** [comment]
@edgarriba: Can you also use RandAugment and TrivialAugment with keypoints and bbox as metadata for transform? Does kornia also compute the transform matrix automatically for these 2 approaches (similar to "basic" transforms)?
