### ISSUE TITLE
Deprecate return_transform in augmentations

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#1502]
We initially keep the `return_transform` for inverting the augmentation. While we implemented the `inverse` function now, I would suggest to deprecate the `return_transform` by moving to:
```python
class RandomAug(...):
    @property
    def transformation_matrix(self):
        return self._transform_mat
```

This can also make the codebase cleaner for handling the output.

**Comment by jramapuram** [comment]
@shijianjian : `return_transform` seems to return the identity matrix for numerous transforms (eg: ColorJitter). Is this expected?

**Comment by edgarriba** [comment]
@jramapuram for intensity transformations there’s no transformation at all, that’s why you get the identity
