### ISSUE TITLE
Restructuring of the augmentation package

### ISSUE THREAD

**Issue by twsl** [kornia/kornia#1514]
## 🚀 Feature

This would introduce a cleaner interface making it much easier to work on a single thing.

## Motivation

I struggled a lot when I first went into the source code of kornia, especially the augmentation and as someone coming from other languages than python it is still weird to see multiple classes per file.
Moreover I think files with more than thousand lines might indicate bad style.

## Pitch

Reorder files into `2d` and `3d` subfolders which allows to easily spot, whats supported.
Outsource each class into a single file wherever it is possible and makes sense.
To not break too much, the external interface of augmentation should not change.

## Alternatives

Keep as is.

## Additional context

cc @shijianjian 
______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by edgarriba** [comment]
Sounds good to me. I would also consider to separate between what's core, containers and the actual implementation of the augmentations.

**Comment by harsh2ai** [comment]
Sounds great will try contributing to tutorials

**Comment by twsl** [comment]
To be discussed:
- merge box, gaussian and motion blur into one file?
- merge crop, center crop and resized crop into one file?
- introduce mix, intensity and geometric subfolders for 2d?

**Comment by shijianjian** [comment]
> To be discussed:
> 
> * merge box, gaussian and motion blur into one file?
> * merge crop, center crop and resized crop into one file?
> * introduce mix, intensity and geometric subfolders for 2d?

Not sure on the first two. But I think we probably introduce mix subfolder (mix_2d, and mix_3d?)

**Comment by twsl** [comment]
@shijianjian and I agreed on:
- one augmentation class per file, unless its a non-random variation that probably just inherits from the random class
- subfolders based on the parent for mix, geometric, intensity
