### ISSUE TITLE
[DOCS] Points clipping

### ISSUE THREAD

**Issue by bhack** [kornia/kornia#154]
When we use use Transform points i.e. from 3d points to the camera plane it is not possible to do visibility clipping after https://github.com/arraiyopensource/kornia/blob/master/kornia/geometry/linalg.py#L212 caused by clipping ambiguities in the return values after the internal embedded normalisation at that line. 

Also w could assume 0 values without clipping.

See http://medialab.di.unipi.it/web/IUM/Waterloo/node51.html. 

See also https://computergraphics.stackexchange.com/questions/5922/why-does-opengl-perform-clipping-in-clip-coordinates

https://gamedev.stackexchange.com/questions/65789/why-is-clip-space-always-referred-to-as-homogeneous-clip-space

Clipping in
http://www.unchainedgeometry.com/jbloom/pdf/homog-coords.pdf

_**UPDATE**_

add to docs a reference note saying that some points might not be project onto the image plane. The user must be responsible for filtering out those points. Verify nans/infs.

**Comment by bhack** [comment]
Check also https://github.com/opencv/opencv/issues/14703

**Comment by edgarriba** [comment]
@bhack what's the decision for this ?

**Comment by bhack** [comment]
In Tensorflow design it is responsibility of the user to filter 3d points to avoid Inf/Nan. See https://github.com/tensorflow/graphics/issues/17

**Comment by edgarriba** [comment]
ok, right. Let's just update our docs to behave similar.
