### ISSUE TITLE
An error occurred when the mask parameter passed to the LoFTR module

### ISSUE THREAD

**Issue by loucadgarbon** [kornia/kornia#1578]
### Describe the bug

When passing in the mask0 and mask1 parameters, an error raise:  
RuntimeError: The size of tensor a (4096) must match the size of tensor b (262144) at non-singleton dimension 1

### Reproduction steps

```bash
import kornia as K
import torch
model = K.feature.LoFTR("outdoor")
img1 = torch.rand(1, 1, 512, 512)
img2 = torch.rand(1, 1, 512, 512)
mask1 = torch.rand(1, 512, 512)
mask2 = torch.rand(1, 512, 512)
input = {"image0": img1, "image1": img2, "mask0":mask1, "mask1":mask2}
out = model(input)
```

### Expected behavior

The program should run normally

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- PyTorch Version (e.g., 1.10.2):
- OS (e.g., Windows10):
- How you installed PyTorch (pip):
- Python version: 3.8.12
- CUDA/cuDNN version: CUDA11.6 cuDNN
- GPU models and configuration: 
- Any other relevant information:
```


### Additional context

_No response_

**Comment by edgarriba** [comment]
does this error throw the exact where it crashes ?

**Comment by edgarriba** [comment]
@ducha-aiki
