### ISSUE TITLE
kornia.augmentation.resize does not have antialias flag, unlike kornia.geometry.transform.resize

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#1587]
### Describe the bug

Check 
https://kornia.readthedocs.io/en/latest/_modules/kornia/augmentation/_2d/geometric/resize.html#Resize

versus 
https://kornia.readthedocs.io/en/latest/geometry.transform.html#kornia.geometry.transform.Resize

**Comment by Tanmay06** [comment]
Hi, I've raised a draft pull request #1687. Please, have a look at it and let me know if any changes are required. Thanks.
