### ISSUE TITLE
Add `adjust_log` to kornia.enhance

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1618]
## 🚀 Feature

We would like to have a consistent functionality against scitkit-image `adjust_log`

See: https://scikit-image.org/docs/stable/api/skimage.exposure.html#adjust-log

## Motivation

Useful for image manipulation and  to compose complex augmentations 

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by dobosevych** [comment]
Demo:
https://colab.research.google.com/drive/1OZhHLoJri2wStYnXoFwWSupsT1--m4Ks?authuser=1#scrollTo=RKH_kUd5fxii

**Comment by dobosevych** [comment]
I think this one could be closed
