### ISSUE TITLE
Add `adjust_sigmoid` to kornia.enhance

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1619]
We would like to have a consistent functionality against scitkit-image `adjust_sigmoid`

See: https://scikit-image.org/docs/stable/api/skimage.exposure.html#adjust-sigmoid

## Motivation

Useful for image manipulation and  to compose complex augmentations 

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by dobosevych** [comment]
Whether already exists such implementation or it should be created from scratch? Can you point to module where to add such implementation?

**Comment by edgarriba** [comment]
@dobosevych the idea is to write from scratch following scimitar implementation and place it here https://github.com/kornia/kornia/blob/master/kornia/enhance/adjust.py

**Comment by Beluuuuuuga** [comment]
@edgarriba 
I would like to make a contribuion. All I need to do is add the function, add the docstring for the function, and add the test? I couldn't figure out how to add an image, do I need to add an image for an example?

**Comment by edgarriba** [comment]
@Beluuuuuuga you are right -- adding the images to docs is optional but recommended (if we want to keep a healthy documentation). We do that through the following python script: https://github.com/kornia/kornia/blob/master/docs/generate_example_images.py (it's a bit messy -- open to make it better)

**Comment by dobosevych** [comment]
I made some tests and plan to do PR on Saturday
https://colab.research.google.com/drive/1OZhHLoJri2wStYnXoFwWSupsT1--m4Ks?authuser=1#scrollTo=Ka7IamUGEdKJ

**Comment by dobosevych** [comment]
Added initial implementation

**Comment by dobosevych** [comment]
Demo:
https://colab.research.google.com/drive/1OZhHLoJri2wStYnXoFwWSupsT1--m4Ks?authuser=1#scrollTo=RKH_kUd5fxii

**Comment by edgarriba** [comment]
@dobosevych could you later send this colab PR here? https://github.com/kornia/tutorials/tree/master/source

I'd like also starting to introduce this is the examples: https://github.com/kornia/kornia-rs
