### ISSUE TITLE
`test_one_hot` will fail when upgrading to pytest >= 7.0.0

### ISSUE THREAD

**Issue by NickleDave** [kornia/kornia#1621]
### Describe the bug

Hi kornia devs,

Just giving you a heads up that one of your tests will fail if/when you change your dev requirements to use "pytest >= 7.0.0".
https://github.com/kornia/kornia/blob/e65fe6c54ada355cf0d9a0ebe4e607acc02e79a7/test/utils/test_one_hot.py#L7

Because of this issue:
https://github.com/pytest-dev/pytest/pull/9061

I know this because I "adapted" (copied :innocent:) `one_hot` and its test for my own library, but I am currently living dangerously and don't have my dev environment pinned, so I got the latest pytest on CI, which is where I caught the fail:
https://github.com/NickleDave/vak/runs/5525156494?check_suite_focus=true
```console
_________________________________ test_onehot __________________________________

    def test_onehot():
        num_classes = 4
        labels = torch.zeros(2, 2, 1, dtype=torch.int64)
        labels[0, 0, 0] = 0
        labels[0, 1, 0] = 1
        labels[1, 0, 0] = 2
        labels[1, 1, 0] = 3
    
        # convert labels to one hot tensor
        one_hot = F.one_hot(labels, num_classes)
    
>       assert pytest.approx(one_hot[0, labels[0, 0, 0], 0, 0].item(), 1.0)
E       AssertionError: approx() is not supported in a boolean context.
E       Did you mean: `assert a == approx(b)`?
```

I think the fix is just to rewrite as the error message suggests, e.g.,:

`assert 1.0 == pytest.approx(one_hot[0, labels[0, 0, 0], 0, 0].item())`

as I did for my tests here:
https://github.com/NickleDave/vak/pull/465
(fix worked locally, waiting for the CI to run)

So the whole fix for that unit test would be just:
```
    assert 1.0 == pytest.approx(one_hot[0, labels[0, 0, 0], 0, 0].item())
    assert 1.0 == pytest.approx(one_hot[0, labels[0, 1, 0], 1, 0].item())
    assert 1.0 == pytest.approx(one_hot[1, labels[1, 0, 0], 0, 0].item())
    assert 1.0 == pytest.approx(one_hot[1, labels[1, 1, 0], 1, 0].item())
```

Happy to submit a PR to patch it up, or let you do it, but just thought I should let you know

**Comment by edgarriba** [comment]
Actually the best would just to use `assert_close` which already deals with tensors
https://github.com/kornia/kornia/blob/master/test/color/test_gray.py#L7

**Comment by johnnv1** [comment]
Done in #1786
