### ISSUE TITLE
Overblur strikes back

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#1622]
### Describe the bug

After using  latest kornia https://github.com/kornia/kornia/pull/1612 with smaller blur in resize, the custom image matching pipeline I am using started working MUCH worse.
 I cannot give any specific numbers, but it seems that image matching benefits from the more blur in resize.

cc @[scott-vsi](https://github.com/scott-vsi)

Probably the proper thing, to specify amount of AA blur based on application? Directly providing sigma is stupid, because it cannot work adaptively with different input/output sizes.

**Comment by edgarriba** [comment]
Are we moving to any action item before the release ? Possibly end of the week since most of all wanted PRs are in
