### ISSUE TITLE
Semantic Segmentation examples do not work with AugmentationSequential

### ISSUE THREAD

**Issue by carbocation** [kornia/kornia#1673]
## 🚀 Feature
It would be nice if the [semantic segmentation example](https://github.com/kornia/kornia-examples/blob/master/data_augmenation_segmentation.ipynb) worked with an AugmentationSequential pipeline, instead of requiring manual sequential application of operations.

## Motivation
It would be nice to use AugmentationSequential to construct a series of geometric augmentations that can be applied both to the input image and the mask in semantic segmentation. However, the `.params` trick demonstrated in the [semantic segmentation example](https://github.com/kornia/kornia-examples/blob/master/data_augmenation_segmentation.ipynb) does not work when k2 is wrapped with `K.augmentation.container.AugmentationSequential`. 

## Additional context
Currently, wrapping k2 in AugmentationSequential will result in ("AssertionError: The number of inputs must align with the number of data_keys. Got 2 and 1.")

**Comment by carbocation** [comment]
(Digging through more of the docs.) Alternatively, perhaps the task of only applying geometric transforms, but not those for intensity or color, is already solved by `AugmentationSequential` accepting `data_keys=["mask"]`? In that case, it may be worth showing an example of that in the semantic segmentation example.

**Comment by edgarriba** [comment]
@carbocation we are open to receive tutorials/examples contributions any time

**Comment by shijianjian** [comment]
`AugmentationSequential ` offers a syntax sugar for different data keys. The error you got is not a bug, since you need to use named parameter for params, like `aug(image, params=aug._params)`.

This `AugmentationSequentail` API is our new default that promoted [here](https://kornia.readthedocs.io/en/latest/applications/image_augmentations.html).
