### ISSUE TITLE
Make nearest neighbour interpolation the default for all mask data

### ISSUE THREAD

**Issue by JanSellner** [kornia/kornia#1676]
## 🚀 Feature
I am using the `RandomAffine` heavily in a segmentation task where I have (at least) one input image and the corresponding mask. I am using the transformation with the data_keys `input` and `mask`, respectively. It is possible to set a `resample` argument for the interpolation in `RandomAffine` but I noticed that this applies to both, the input image and the mask. However, I think a more sensible default would be to apply `bilinear` (the current default) only to `input` type and for `mask` type `nearest` should be the default. If the mask contains integer values (e.g. label ids) then the current default of `billinear` may produces different, new labels (due to the interpolation).

Currently, I am working around this issue by creating my own random affine transformation which basically overwrites the `apply_transform` method:
```python
class RandomAffineAutoInterpolation(K.RandomAffine):
    def apply_transform(
        self, input: Tensor, params: Dict[str, Tensor], transform: Optional[Tensor] = None
    ) -> Tensor:
        _, channels, height, width = input.shape
        transform = cast(Tensor, transform)

        # Label tensors must always use nearest interpolation
        if channels == 1:
            resample = 'nearest'
        else:
            resample = 'bilinear'
        
        return warp_affine(
            input,
            transform[:, :2, :],
            (height, width),
            resample,
            align_corners=self.flags["align_corners"],
            padding_mode=self.flags["padding_mode"].name.lower(),
        )
```
This works as long as the `mask` input has only 1 channel. A better solution would be to make this decision based on the data_key, but as far as I can see, this information is not available in this function.

I guess this problem also affects other functions but `RandomAffine` is the one where I noticed this issue. Maybe the resample argument should also be a dict (with `input` and `mask` as possible keys) to let the user change the default?

**Comment by edgarriba** [comment]
This makes sense to me. Could you file a PR to update the behavior ? /cc @shijianjian any opinions ?

**Comment by carbocation** [comment]
One class of error that seems to arise from this issue of masks not being set to nearest neighbors is that the number of classes in the mask can increase. In my case, when I run `RandomAffine` on a target that has values from 0-13, plus an `ignore_index` set to -100, I subsequently see numerous negative values (-99, -98, -97, etc). This manifests as an error during loss calculation, e.g.:

```
/opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/native/cuda/NLLLoss2d.cu:93: nll_loss2d_forward_kernel: block: [5,0,0], thread: [928,0,0] Assertion `t >= 0 && t < n_classes` failed.
```

I'm commenting here because I believe that this should be solved by the above referenced pull request.

**Comment by edgarriba** [comment]
Something to consider, is that when you apply geometric transformations, you might want to get the transformation matrix to build a mask of the final valid area to evaluate the loss
