### ISSUE TITLE
Implement kmeans

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1714]
## 🚀 Feature

Add a `kornia.contrib.kmeans` functionality that clusters batches of n-dimensional sets of features.

Reference: https://github.com/subhadarship/kmeans_pytorch/

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by avinashselvam** [comment]
Hi @edgarriba I've raised a draft PR for this issue containing the implementation. Will push tests soon.
