### ISSUE TITLE
[DOCS] missing docs for `normal_transform_pixel`

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#175]
function [`normal_transform_pixel`](https://github.com/arraiyopensource/kornia/blob/master/kornia/geometry/transform/imgwarp.py#L23) have missing docs and tests.

TODO:
- add function to docs: https://github.com/arraiyopensource/kornia/blob/master/docs/source/geometry.transform.rst
- create few unit tests
- potentially move the function to `kornia.geometry.conversions`

**Comment by ucalyptus** [comment]
PR  #315 based on this issue
