### ISSUE TITLE
Integrate `Sophus` api

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1756]
## 🚀 Feature

Implement  `kornia.geometry.liegroup` submdule based on [Sophus](https://github.com/strasdat/Sophus).

Initial implementation here: https://github.com/kornia/kornia/tree/liegroup-algebra/kornia/geometry/liegroup

## Motivation

write a python / pytorch / numpy agnostic api

## Alternatives

Existence of https://github.com/princeton-vl/lietorch

Drawbacks:
- last commit one year ago
- source code to complex and can be simplified

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by edgarriba** [comment]
Need to cross validate with Sophus results.

/cc @strasdat  can we somehow generate from c++ side a input/output to cross validate results ?

**Comment by cjpurackal** [comment]
closed via #1887
