### ISSUE TITLE
Typo in image_matching example

### ISSUE THREAD

**Issue by robmarkcole** [kornia/kornia#1766]
In https://kornia-tutorials.readthedocs.io/en/latest/image_matching.html there is
```
H, inliers = cv2.findFundamentalMat()
```
but this is confusing since the reader assumes this is returning the homography matrix.
More clear would be 
```
F, inliers = cv2.findFundamentalMat()
```

As a bonus the example could show the computation of H and its use to unwarp the image:
```
H, _ = cv2.findHomography(mkpts0, mkpts1, cv2.RANSAC, 5.0)
.
.
im_unwarped = cv2.warpPerspective(unwarped, H, shape)
```

Also suggested by @edgarriba 
```
pip install kornia_rs

def load_torch_image(fname):
    load_type = K.io.ImageLoadType.RGB32
    return K.io.load_image(fname, load_type)[None] / 255.
```

**Comment by johnnv1** [comment]
The typo seems to have already been fixed in the link 😄
