### ISSUE TITLE
Deprecate Python 3.6 support

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1770]
## 🚀 Feature

Deprecate python 3.6 -- support Python >= 3.7

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by johnnv1** [comment]
I think this can help:
```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
@@ -1,5 +1,5 @@
 default_language_version:
-  python: python3.8
+  python: python3.7
 
 ci:
   autofix_prs: true
@@ -45,7 +45,7 @@ repos:
     rev: v2.37.3
     hooks:
       - id: pyupgrade
-        args: [--py36-plus]
+        args: [--py37-plus]
 
   - repo: https://github.com/PyCQA/bandit
     rev: 1.7.4

diff --git a/pyproject.toml b/pyproject.toml
@@ -17,3 +17,4 @@ skip_glob = []
 skip = [
     "kornia/__init__.py"
 ]
+add_imports = ["from __future__ import annotations"]
```

and then just run:

```bash
$ pre-commit run -a
```

A previous result is:

```bash
$ git diff --shortstat
416 files changed, 2165 insertions(+), 1338 deletions(-)
```


With this, the `isort` will add 'from __future__ import annotations' at all files, and the `pyupgrade` will do all work. Probably the changes will be just the tying annotations.
