### ISSUE TITLE
Segmentation Aug with Labelme Json files？

### ISSUE THREAD

**Issue by monkeycc** [kornia/kornia#1772]
## 🚀 Feature

Segmentation Aug with Labelme Json files?
How would I now be able to save the augmented polygons back to json labelme annotations format?

Labelme Json  -  kornia  - output：   img json labelme annotations

## Additional context

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by edgarriba** [comment]
hi ! I'm not sure about the Labelme format but you can easily serialize the augmentation parameters by accessing `aug._params`
See: https://github.com/kornia/kornia/discussions/1745
