### ISSUE TITLE
[feature] Add `KORNIA_CHECK_SAME_DEVICES`

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1775]
actually this could be part of the new testing api
`KORNIA_CHECK_SAME_DEVICES`

https://github.com/kornia/kornia/blob/master/kornia/testing/__init__.py#L208

_Originally posted by @edgarriba in https://github.com/kornia/kornia/pull/1760#discussion_r911752967_

**Comment by MrShevan** [comment]
Is it still needed?) I read your comments in mentioned PR and it seemed to me that I could make improvements
