### ISSUE TITLE
Configure `rtol` and `atol` parameters to pass tests on the `losses` module

### ISSUE THREAD

**Issue by MrShevan** [kornia/kornia#1805]
## 🚀 Feature

When running tests using `float16` and `cuda` in `losses` module, errors occurs.

 `pytest test/losses -v --dtype=float16 --device=cuda`
 
 ```========================================================================================= short test summary info ==========================================================================================
FAILED test/losses/test_losses.py::TestDivergenceLoss::test_js_div_loss_2d[cuda-float16-input2-target2-0.346574] - AssertionError: Scalars are not close!
FAILED test/losses/test_losses.py::TestDivergenceLoss::test_js_div_loss_2d[cuda-float16-input3-target3-0.346574] - AssertionError: Scalars are not close!
FAILED test/losses/test_losses.py::TestDivergenceLoss::test_noncontiguous_js[cuda-float16-input2-target2-0.346574] - AssertionError: Scalars are not close!
FAILED test/losses/test_losses.py::TestDivergenceLoss::test_noncontiguous_js[cuda-float16-input3-target3-0.346574] - AssertionError: Scalars are not close!
FAILED test/losses/test_losses.py::TestTotalVariation::test_tv_on_4d[cuda-float16-input0-expected0] - AssertionError: Tensor-likes are not close!
FAILED test/losses/test_losses.py::TestTotalVariation::test_tv_on_4d[cuda-float16-input1-expected1] - AssertionError: Tensor-likes are not close!
```

If you use `float16`, these errors not occurs. It seems they are caused by the fact that the parameters `rtol` and `atol` are not configured.

Example of error description:
```
E       AssertionError: Tensor-likes are not close!
E
E       Mismatched elements: 1 / 3 (33.3%)
E       Greatest absolute difference: 0.001953125 at index 2 (up to 0.0001 allowed)
E       Greatest relative difference: 0.0008613264427217916 at index 2 (up to 0.0001 allowed)
```

I suggest choosing default thresholds for `rtol` and `atol` in testing api to pass all these tests.

### Environment

- PyTorch version: 1.10.1+cu113
- Python version: 3.6.9
- CUDA Version: 11.6

Open to PR :)

**Comment by edgarriba** [comment]
@MrShevan probably need a mechanism in the Test class that chooses the tolerance based on the precision ? 
I started this initiative some time ago but never had the chance to implement it across the library
https://github.com/kornia/kornia/blob/master/kornia/testing/__init__.py#L78

worth to explore adding that functionality there
