### ISSUE TITLE
[BUG] Bug in _compute_projection ?

### ISSUE THREAD

**Issue by krrish94** [kornia/kornia#181]
It seems to me that there is a bug in the `DepthWarper` class (in the `_compute_projection`) function.

https://github.com/arraiyopensource/kornia/blob/master/kornia/geometry/warp/depth_warper.py#L96

`z` is to be actually computed as `1. / flow[:, 3]` as opposed to `1. / flow[:,2]`. (Recall that `flow` is computed from `point`, which is ordered on Line 93 of the same script as `torch.FloatTensor([[[x], [y], [1.0], [invd]]])`. This indicates that the inverse depth will lie at index `flow[:,3]`, not `flow[:,2]`.

**Comment by edgarriba** [comment]
@krrish94 the DepthWarper class has to be refactored very soon. I'll work on that.

**Comment by edgarriba** [comment]
@krrish94 we recentyl introduced `kornia.perspective.project_points` which I believe that can be replaced by compute_projection. Actually, thinking to drop it out from the API.

https://kornia.readthedocs.io/en/latest/geometry.camera.perspective.html#kornia.geometry.camera.perspective.project_points

**Comment by krrish94** [comment]
Yes, that sounds about right.
