### ISSUE TITLE
upgrade `add_weighted` to accept weights as tensors

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1824]
We have a use case in for blurring aware of edge to use this function with weights as tensors

_Originally posted by @edgarriba in https://github.com/kornia/kornia/pull/1822#discussion_r945259365_

**Comment by edgarriba** [comment]
@nitaifingerhut

**Comment by nitaifingerhut** [comment]
thanks!

**Comment by nitaifingerhut** [comment]
do you want me to do it?

**Comment by edgarriba** [comment]
feel free to go for it

**Comment by nitaifingerhut** [comment]
@edgarriba hereby: https://github.com/kornia/kornia/pull/1827
