### ISSUE TITLE
Refactoring `ColorJitter` and `ColorJiggle` into smaller components

### ISSUE THREAD

**Issue by justanhduc** [kornia/kornia#1836]
## 🚀 Feature
`ColorJitter` and `ColorJiggle` currently are too packed. It is better to develop smaller components and rewrite these as compositions of smaller components.

## Motivation

Smaller components can be applied individually. For e.g., brightness and contrast jitterings are applicable to gray images, but currently they are under `ColorJitter` and `ColorJiggle` which are not applicable to gray images.

## Pitch

```
class BrightnessJitter(...):
    ...


class ContrastJitter(...):
    ...


class HueJitter(...):
    ...


class ColorJitter(nn.Sequential):
    def __init__(...):
        self.brightness_jitter = BrightnessJitter(...)
        self.contrast_jitter  = ContrastJitter(...)
        self.hue_jitter = HueJitter(...)
        ...

```

**Comment by edgarriba** [comment]
I like the names such `RandomBrightness` , `RandomContrast`, etc. it goes according with other ops in the module

**Comment by justanhduc** [comment]
@edgarriba I think I can work on a PR if it's not too urgent.

**Comment by edgarriba** [comment]
definitely!

**Comment by duc12111** [comment]
Hi @edgarriba, I wonder if this is a mistake 
https://github.com/kornia/kornia/blob/fac687ed482fdc0493a58931e881a751a20495ad/kornia/augmentation/base.py#L219 seems to create duplicate class name since https://github.com/kornia/kornia/blob/fac687ed482fdc0493a58931e881a751a20495ad/kornia/augmentation/base.py#L62 have already had class name

**Comment by shijianjian** [comment]
> Hi @edgarriba, I wonder if this is a mistake 
> 
> https://github.com/kornia/kornia/blob/fac687ed482fdc0493a58931e881a751a20495ad/kornia/augmentation/base.py#L219 seems to create duplicate class name since https://github.com/kornia/kornia/blob/fac687ed482fdc0493a58931e881a751a20495ad/kornia/augmentation/base.py#L62 have already had class name

Yes. It is a bug. Can you send a PR to fix it?

**Comment by edgarriba** [comment]
Good catch! Is anyone working on this current feature request? Will be very useful to have as separated 
components  `RandomBrightness`, `RandomContrast` , etc
