### ISSUE TITLE
Option to use pytorch CPU only

### ISSUE THREAD

**Issue by aekiratli** [kornia/kornia#1838]
## 🚀 Feature
It would be nice to have CPU version of kornia. Pytorch requirement comes with GPU enabled by default
This should reduce size of docker images.

**Comment by aekiratli** [comment]
```
FROM python:3.8.6
.
.
.
RUN pip install torch==1.12.1 --extra-index-url https://download.pytorch.org/whl/cpu
.
.
.
RUN pip install -r requirements.txt
```

For anyone who wants to lower the size of their docker image, you can manually install torch CPU version, it drastically reduces image

Log from `RUN pip install -r requirements.txt`
```
Collecting kornia==0.4.1
  Downloading kornia-0.4.1-py2.py3-none-any.whl (225 kB)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.8/site-packages (from kornia==0.4.1->-r requirements.txt (line 3)) (1.12.1+cpu)

```

**Comment by edgarriba** [comment]
In principle if you install first the cpu version of pytorch , Kornia will work fine. At least it does for our main testing infra 
https://github.com/kornia/kornia/blob/master/.github/workflows/tests_cpu.yml#L32
