### ISSUE TITLE
Implement Tutorial showcasing SOLD2

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#1856]
## 🚀 Feature

Similar to https://kornia-tutorials.readthedocs.io/en/latest/image_matching_adalam.html

## Additional context

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by johnnv1** [comment]
I would love to contribute to this tutorial 😄

**Comment by ducha-aiki** [comment]
Go ahead then! :)

**Comment by ogencoglu** [comment]
Is there a way to get the line segment probability outputs for each segment?
