### ISSUE TITLE
The example of image registration cannot run noramlly

### ISSUE THREAD

**Issue by Juddd** [kornia/kornia#1857]
I'm newer of kornia. As the title, [this example](https://kornia.readthedocs.io/en/latest/applications/image_registration.html#) in the official documentation cannot run normally. Could your me a right version?

ps：I'm in the newest version 0.67

**Comment by ducha-aiki** [comment]
What do you mean it cannot run normally?

If you click on the full version link:
>To reproduce the same results as in the showed video you can go through or full tutorial using Colab found [here](https://kornia-tutorials.readthedocs.io/en/latest/image_registration.html) .

and copy-paste the thing into Jupiter notebook (or just ipython) it works perfectly. 

I have just tried on my laptop and it works perfectly.

**Comment by ducha-aiki** [comment]
>or your library is not very good at doing this at the moment?
Please, don't start communication with insults. 

The problem with your example is that you have lot of "occlusions" in form of text.Gradient-based registration is a wrong method in this case.  I would recommend  you to use homography tracker https://kornia.readthedocs.io/en/latest/tracking.html#kornia.tracking.HomographyTracker or feature based matching instead

https://kornia-tutorials.readthedocs.io/en/latest/image_matching_adalam.html

**Comment by Juddd** [comment]
Sorry, I didn't mean to insult, I'm just not very good at expressing my meaning in English. I am Chinese. I'm currently using the opencv method of feature points, so I'd like to upgrade my project with kornia.

**Comment by ducha-aiki** [comment]
Then KetNet-HardNet-AdaLAM from kornia (https://kornia-tutorials.readthedocs.io/en/latest/image_matching_adalam.html) is the way to go

**Comment by edgarriba** [comment]
@ducha-aiki why the tutorial is partially broken ?

**Comment by ducha-aiki** [comment]
@edgarriba because it cannot run on weak readthedocs VM under time limit, 30 sec IIRC

**Comment by edgarriba** [comment]
We could try to migrate to the-pages

**Comment by johnnv1** [comment]
We have migrated our tutorials pages to https://kornia.github.io/tutorials/nbs/image_registration.html -- i believe it's working. Will close this issue for now, feel free to reopen it
