### ISSUE TITLE
Make pre-commit.ci PRs cancel previous tests to not waste CI time

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#1863]
## 🚀 Feature
Now the CI is done twice on essentially the same code.

## Motivation

Have CI-test be done twice faster 

References:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre

## Additional context

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by edgarriba** [comment]
@asottile is that possible ?

**Comment by asottile** [comment]
I had prototyped this and it was very fragile and didn't make a difference ~95%+ of the time so I scrapped it

**Comment by ducha-aiki** [comment]
@asottile for other libs - maybe, but our test-cpu suite take 30 min. We also don't have instances to run multiple PRs in parallel. So if someone is actively pushing is PR and pre-commit.ci pushes as well, it can block CI for half a day or more

**Comment by asottile** [comment]
oh you're talking about cancelling github actions not cancelling pre-commit.ci -- yeah that's easy just follow the github actions documentation

**Comment by edgarriba** [comment]
@asottile thanks for the answer. @ducha-aiki i can spend a bit of time on this today
