### ISSUE TITLE
Package includes test.geometry module

### ISSUE THREAD

**Issue by chris-morgan** [kornia/kornia#1864]
The package distribution includes `test.geometry`.

setup.py needs:

```diff,python
-        packages=find_packages(exclude=('docs', 'test', 'examples')),
+        packages=find_packages(exclude=('docs', 'test', 'test.*', 'examples')),
```

(Might as well go wildcard.)

**Comment by edgarriba** [comment]
Hi, can you send a PR with the fix?

**Comment by chris-morgan** [comment]
No, I’m not invested in this or interested in engaging further; just a drive-by bug report.

**Comment by johnnv1** [comment]
One suggestion I have is to move the entire setup to declarative metadata, it makes the setup clearer. Also, can use tools (pre-commit hook) to ensure the sanity (https://github.com/asottile/setup-cfg-fmt)

**Comment by edgarriba** [comment]
Sounds like a good idea. Recently played a bit with setup.cfg and makes everything more readable. Bit busy this days but I can try something unless anyone wants to volunteer before

**Comment by johnnv1** [comment]
I can do this in some moment this week
