### ISSUE TITLE
Filtering Operators tutorial

### ISSUE THREAD

**Issue by lappemic** [kornia/kornia#1872]
## 📚 Documentation

[53](https://github.com/kornia/kornia/issues/53)
Hugging space demo and embedded app

**Comment by lappemic** [comment]
The HF space is not available and running [here](https://huggingface.co/spaces/kornia/kornia-image-filtering). Many thanks to @NimaBoscarino for the starter guide and support! Please let me know, if i can improve the space and add more features since this was one of my first contributions and especially the first gradio app! 🍾 😄

**Comment by NimaBoscarino** [comment]
Yay thank you for doing this! I took a look at your space, and there's a small bug to fix: https://kornia.readthedocs.io/en/latest/filters.html#kornia.filters.blur_pool2d actually downsamples images, so it looks like all the images going through your space are being downsampled regardless of whether a user wants to use `blur_pool2d` or not 🤔

**Comment by lappemic** [comment]
Thanks Nima for this hint. I was not really aware of it. After digging a bit more in the kornia docs i realized, that also `max_blur_pool2d` is downsampling. This is why i decided to go for another approach in the space and now have deployed a single tab per filter option. Would be happy to hear your thoughts about this. Thanks again for the feedback!

**Comment by edgarriba** [comment]
the tabs widget looks really nice, feel free to add to ours docs similar to https://github.com/kornia/kornia/pull/1876/files

**Comment by NimaBoscarino** [comment]
@lappemic The easiest way to do it is to basically do it like this PR: https://github.com/kornia/kornia/pull/1871/files

That is:
1. Create a file at `docs/source/gradio/filtering_operators.html` that has the `<script>` and `<gradio>` snippets.
2. Embed it in [the "Blurring" section of the docs](https://github.com/kornia/kornia/blame/master/docs/source/filters.rst#L8)
