### ISSUE TITLE
Line Segment Homography Warping not working

### ISSUE THREAD

**Issue by johko** [kornia/kornia#1889]
### Describe the bug

Hi,
as part of the Docs'n Demo sprint I'm currently working on porting this tutorial: https://kornia-tutorials.readthedocs.io/en/latest/line_detection_and_matching_sold2.html to a HF space.

But I stumbled across some problems in the Homograpy part of the tutorial. 
When calling `ransac = K.geometry.RANSAC(model_type="homography_from_linesegments", inl_th=3.0)` I get the error that only the model types `homography` and `fundamental` are supported. 

And when using `homography` as model_type I get the error:
`ValueError: Invalid kp1 shape, we expect Nx2 Got: torch.Size([314, 2, 2])`

### Reproduction steps

```bash
Follow the aforementioned tutorial in the Homography part.
```

### Expected behavior

As shown in the tutorial, I expected the first image to be warped, aligned by found line segments.

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- PyTorch Version (e.g., 1.0): 1.12.1+cu102
- OS (e.g., Linux): Ubuntu 18.04.6 LTS
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.9.9
- CUDA/cuDNN version: 11.5.119
- GPU models and configuration:
- Any other relevant information:
```


### Additional context

_No response_

**Comment by edgarriba** [comment]
@johko are you using last version in master ? i see the existence of that option
https://github.com/kornia/kornia/blob/9bf43775fa2a9da56e543fa54de47e02b8c6de42/kornia/geometry/ransac.py#L41

/cc @ducha-aiki not usre is the case but we might want to use enums here since are less error prone

**Comment by ducha-aiki** [comment]
@johko it seems that you are using older version of kornia. Line matching was added only recently.

**Comment by johko** [comment]
Ah, okay. I'll try with the newer version then, I currently only used the pip provided one which probably was a bit older then.

Thank you for the quick reply :)
