### ISSUE TITLE
mypy problems

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#190]
Hi,

There are problems with typing, specifically:

1) kornia/feature/laf.py:96: error: "Tensor" has no attribute "contiguous"; maybe "is_contiguous"?
I am not the only one with such problem 
https://gitmemory.com/issue/pytorch/pytorch/21261/498439370

2) kornia/feature/laf.py:115: error: Unsupported operand types for - ("float" and "Tensor")

Pytorch works with floats just fine. I think, this should be added to mypy settings, or switched off for now

**Comment by edgarriba** [comment]
as 1, no clue.
as for 2, I hacked it in some places by wrapping floats to -> `torch.tensor(1.)`

**Comment by edgarriba** [comment]
@ducha-aiki is this still happening ?

**Comment by ducha-aiki** [comment]
Yes, both. I put `# type: ignore` on those lines

**Comment by edgarriba** [comment]
ok. I'll ask in pytorch slack.

**Comment by bhack** [comment]
For the 1st One is this useful?

https://github.com/pytorch/pytorch/commit/2e59a0a646883f6b20f2e0d0af9c795e629bc115

**Comment by edgarriba** [comment]
@ducha-aiki @lferraz we should revisit this to see the behaviour with last versions of pytorch. In, addition, I suggest to update mypy to be used within pytest using the plugin [pytest-mypy/](https://pypi.org/project/pytest-mypy/)

/cc @shijianjian
