### ISSUE TITLE
Remove unnecessary CI jobs

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia#1906]
From https://github.com/kornia/kornia/pull/1885#issuecomment-1254995760:

> in ".github/workflows/format.yml":
>    - The linter job, seems unnecessary since it is already provided for in the pre-commit hooks
>    - The pre-commit action is deprecated, and the pre-commit.ci (already configured at the repo) do the same job

**Comment by johnnv1** [comment]
Maybe these and some other commands can be removed from "Makefile"
 - make lint - will be covered by pre-commit
 - make mypy - will be covered by pre-commit
 - make autopep8 - i think the files have been formatted by black (also at pre-commit)

**Comment by ducha-aiki** [comment]
make lint and make mypy are quite useful - for doing a local check and then fixing things manually, rather than relying on pre-commit. Especially mypy - because of multiple possible typings.

**Comment by edgarriba** [comment]
agree here -- i would remove only autopep8 since we mostly use black for the same purpose

**Comment by johnnv1** [comment]
i don't get it, since we can run pre-commir locally and fix then manually too, but ok 😅
