### ISSUE TITLE
Remove pytest markers

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia#1907]
From https://github.com/kornia/kornia/pull/1885#discussion_r973668636

@edgarriba commented that pytest markers (jit, grad, nn) may no longer be in use and can be removed

**Comment by ducha-aiki** [comment]
@edgarriba I believe they are still useful. Correct me if I am wrong

**Comment by edgarriba** [comment]
we are currently not using -- but we could if we want to speed up the testing workflow @MrShevan any thoughts here ?

**Comment by ducha-aiki** [comment]
@edgarriba we don't use them online in CI, but I do use them in local testing.

**Comment by edgarriba** [comment]
oh, good to know -- then let's keep it if at least someone is using. Besides, i'd advocate to be somehow part of the ongoing effort `BaseTester` class from @MrShevan
