### ISSUE TITLE
report a documentaion bug

### ISSUE THREAD

**Issue by Juddd** [kornia/kornia#1909]
The code [here](https://kornia-tutorials.readthedocs.io/en/latest/line_detection_and_matching_sold2.html#example-of-homography-from-line-segment-correspondences-from-sold2) has a `model_type="homography_from_linesegments"`. But I will get error information like:
![image](https://user-images.githubusercontent.com/10048069/192146426-015ae786-fcbf-4efb-aa8a-bb8fea293ee8.png)

If I change the `"homography_from_linesegments"` into `"homography"` as the reminder, Then the following code:
```
H_ransac, correspondence_mask = ransac(
    matched_lines1.flip(dims=(2,)), matched_lines2.flip(dims=(2,))
)
```
![image](https://user-images.githubusercontent.com/10048069/192146504-dc100e14-6a3f-481c-bb97-26e3b94ab91d.png)

Hope to fix

**Comment by ducha-aiki** [comment]
@Juddd are you sure that you are running the latest version of kornia? homography from line segments has been added very recently

**Comment by Juddd** [comment]
@ducha-aiki Hi, my `kornia` is version 0.67 (installed via `conda install kornia`), is this not the latest version?

**Comment by ducha-aiki** [comment]
Yes, the homohraphy lines existing in the master branch so far. Perhaps we should draft some release

**Comment by Juddd** [comment]
@ducha-aiki Since this is not a bug, I'll turn this off. I hope you hurry up and get this example running successfully.

**Comment by Juddd** [comment]
@ducha-aiki May I know the approximate time of the new version?

**Comment by Juddd** [comment]
@ducha-aiki Can I get an approximate time, please? I want to use it in my project

**Comment by edgarriba** [comment]
soon this week: https://github.com/kornia/kornia/pull/1938

we are fixing small issues -- besides, to use in you project you can pip install directly from main
https://github.com/kornia/kornia#from-source-using-pip

```bash
pip install git+https://github.com/kornia/kornia
```
