### ISSUE TITLE
[Feat] Turn on JIT tests

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#192]
JIT tests have been temporaly disabled since recent torch version changed the API. This might require to take a look at it again. See https://github.com/arraiyopensource/kornia/pull/191

**Comment by edgarriba** [comment]
this is related to https://github.com/kornia/kornia/pull/261

**Comment by edgarriba** [comment]
@ducha-aiki notice that in last pytorch version 1.5 JIT seems more stable.

I quickly tested on last [release](https://github.com/kornia/kornia/blob/master/test/color/test_gray.py#L61-L66), and to me seems fine to start adding this quick tests case by case. I propose this test pattern,
```python
 def test_jit(self, device, dtype):
        batch_size, channels, height, width = 2, 3, 64, 64
        img = torch.ones(batch_size, channels, height, width).to(device, dtype)
        op = kornia.rgb_to_grayscale
        op_jit = kornia.jit.rgb_to_grayscale
        assert_allclose(op(img), op_jit(img))
```
/cc @shijianjian

**Comment by edgarriba** [comment]
The task would be to check which test have missing JIT test and implement:
```python
def test_jit(self, device, dtype):
        batch_size, channels, height, width = 2, 3, 64, 64
        img = torch.ones(batch_size, channels, height, width).to(device, dtype)
        op = kornia.rgb_to_grayscale
        op_jit = kornia.jit.rgb_to_grayscale
        assert_allclose(op(img), op_jit(img))
```
