### ISSUE TITLE
[FEAT] LAF improving

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#194]
Todo`s for after paper deadline:

- [ ] convert from OpenCV keypoints
- [ ] extract patches w/o for loop for images. The problem is that there can be different number of features per scale, so batch is not really the batch

https://github.com/arraiyopensource/kornia/pull/182

**Comment by edgarriba** [comment]
@ducha-aiki please update this with whatever is missing. Otherwise, close it.

**Comment by ducha-aiki** [comment]
Well, you are again the 1st.
Regarding the 2nd, I have thought a lot about it, but cannot find a way. 
Except, fixing the # of features per pyramid level, e.g. in proportion to resp. image area. 

But this requires benchmarking on, say Oxford Affine and HPatches, at least

**Comment by edgarriba** [comment]
ok, let's keep this ticket open until it's 2nd it's finished.
