### ISSUE TITLE
Implement sepia filter

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1944]
## 🚀 Feature

Add a sepia filter operator in `kornia.filters`

resource: https://stackoverflow.com/questions/23802725/using-numpy-to-apply-a-sepia-effect-to-a-3d-array

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by johnnv1** [comment]
Hi, I can work on this 😄

**Comment by edgarriba** [comment]
@johnnv1 sounds goods!

**Comment by edgarriba** [comment]
one consideration would be using `filter2d` instead and evaluate performance against `.dot()`
