### ISSUE TITLE
The latest pytorch nightly has removed torch.testing.assert_allclose

### ISSUE THREAD

**Issue by xuzhao9** [kornia/kornia#1981]
### Describe the bug

The latest PyTorch nightly has removed `torch.testing.assert_allclose`:
https://github.com/pytorch/pytorch/pull/87974

Kornia needs to update this code: https://github.com/kornia/kornia/blob/master/kornia/testing/__init__.py#L271

### Reproduction steps

```bash
`import kornia`
on the latest PyTorch nightly

error:
Traceback (most recent call last):
  File "/home/circleci/miniconda3/lib/python3.8/site-packages/kornia/testing/__init__.py", line 235, in <module>
    from torch.testing._core import _get_default_tolerance  # type: ignore
ModuleNotFoundError: No module named 'torch.testing._core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install.py", line 20, in <module>
    patch_dalle2()
  File "install.py", line 7, in patch_dalle2
    import dalle2_pytorch
  File "/home/circleci/miniconda3/lib/python3.8/site-packages/dalle2_pytorch/__init__.py", line 2, in <module>
    from dalle2_pytorch.dalle2_pytorch import DALLE2, DiffusionPriorNetwork, DiffusionPrior, Unet, Decoder
  File "/home/circleci/miniconda3/lib/python3.8/site-packages/dalle2_pytorch/dalle2_pytorch.py", line 20, in <module>
    from kornia.filters import gaussian_blur2d
  File "/home/circleci/miniconda3/lib/python3.8/site-packages/kornia/__init__.py", line 3, in <module>
    from . import filters
  File "/home/circleci/miniconda3/lib/python3.8/site-packages/kornia/filters/__init__.py", line 2, in <module>
    from .blur_pool import BlurPool2D, MaxBlurPool2D, blur_pool2d, edge_aware_blur_pool2d, max_blur_pool2d
  File "/home/circleci/miniconda3/lib/python3.8/site-packages/kornia/filters/blur_pool.py", line 7, in <module>
    from kornia.testing import KORNIA_CHECK, KORNIA_CHECK_SHAPE
  File "/home/circleci/miniconda3/lib/python3.8/site-packages/kornia/testing/__init__.py", line 254, in <module>
    from torch.testing import assert_allclose as _assert_close
ImportError: cannot import name 'assert_allclose' from 'torch.testing' (/home/circleci/miniconda3/lib/python3.8/site-packages/torch/testing/__init__.py)
```

### Expected behavior

successful return

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:
```


### Additional context

_No response_

**Comment by edgarriba** [comment]
@xuzhao9 thanks to report! we are aware of it. was recently pointed out in a conversation @johnnv1

**Comment by pmeier** [comment]
I actually authored the mitigation code in the `kornia` test suite. See #1031. The offending line here is

https://github.com/kornia/kornia/blob/a79fbcbc65810ff74328eb0a3ccd65db2fbf4284/kornia/testing/__init__.py#L235

Change this to 

```py
from torch.testing._comparison import default_tolerances
```

and you should be good again.

**Comment by edgarriba** [comment]
@pmeier do you think is safe to remove the try/catch block ? apparently this gives us also some headaches with mypy

**Comment by pmeier** [comment]
It will be after you bump the minimum dependency to `torch>=1.9`, but it seems that has not happened yet:

https://github.com/kornia/kornia/blob/b9f26e037eeebeb1230d38db7e638ee2817627a6/setup.cfg#L38-L40

**Comment by edgarriba** [comment]
@ducha-aiki @shijianjian opinions here?

**Comment by pmeier** [comment]
Plus, my patch from #1031 only broke, because I needed to import from a private namespace. See #1134 for details. When that is fixed as well you can use `torch.testing.assert_close` without any workarounds I think.
