### ISSUE TITLE
[FEAT/DOC] Add __repr__ to nn.Module

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#199]
The most of modules are lacking very useful `__repr__` function. I am leaving this issue open until we catch-up. 

- [ ] create list of missing `__repr__` s 
- [ ] fix all the old functions
- [ ] add some test to lint to require `__repr__` existence

**Comment by edgarriba** [comment]
@ducha-aiki what info do you want to output ?

**Comment by ducha-aiki** [comment]
It depends on the Module. E.g. for  CornerHarris, it would be the k, for GaussianBlur - kernel size and sigma, etc.

**Comment by edgarriba** [comment]
@shijianjian consider this with nn module

**Comment by edgarriba** [comment]
continue here https://github.com/kornia/kornia/pull/774
