### ISSUE TITLE
Implement `applyColorMap` from opencv

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#1991]
## 🚀 Feature

Implement `applyColorMap` from opencv

https://docs.opencv.org/ref/master/d3/d50/group__imgproc__colormap.html#gadf478a5e5ff49d8aa24e726ea6f65d15
______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by johnnv1** [comment]
Should the colormap, have all the values (for example for 8 bits, one color for each value between 0-255), or should the function do something more complete like try to distribute the existing colors in the colormap among the existing values in the source image? 


cv2 code: https://github.com/opencv/opencv/blob/ebb6915e588fcee1e6664cce670f0253bac0e67b/modules/imgproc/src/colormap.cpp#L805
