### ISSUE TITLE
`CameraModel` API discussion

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2011]
## 🚀 Feature

Design of the new generic `CameraModel` API to be used e.g to build pinhole, orthographic, stereo, multi, posed apis, etc.

Based on the discussion in https://github.com/kornia/kornia/issues/2006 and the recent effort to upgrade `kornia.geometry`  package to align with Sophus and Eigen.

Please, make suggestions:
https://docs.google.com/document/d/1fE3lgUC36nHp2FjDyH71hefJH7G5hDV4iPCnqa76HoY/edit?usp=sharing

## Motivation

The exising `PinholeModel` is one of the oldest pieces in kornia that lacks of flexibility to extend to other camera types plus not correlate well when want to be used without a pose. Motivation also is to align as much as possible with state of the art production libraries like
- Sophus: https://github.com/strasdat/Sophus/blob/23.04-beta/cpp/sophus/sensor/camera_model.h
- And eventually integrate with Pangolin for 3d viz: https://github.com/stevenlovegrove/Pangolin/tree/pango2

/cc @ducha-aiki @YanivHollander @cjpurackal @lferraz 
______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by cjpurackal** [comment]
Are we planning to interface other sensors, say imu? If yes, it makes sense to put the camera module inside kornia.sensor.

**Comment by edgarriba** [comment]
if there's a demand yes, maybe other sensors like lidars would make sense too. But not a priority for now

**Comment by YanivHollander** [comment]
With the new `CameraModel` class, where should camera extrinsics go? Could it be a meta-class that maps a list of `CameraModel` objects to their respective **R**'s and **t**'s? If so, where should we move `PinholeCamera.project` and `PinholeCamera.unproject` functions to transform between points in 3D world reference to/from camera image?

**Comment by cjpurackal** [comment]
@edgarriba Your proposal looks good to me. Maybe I can write something up based on the above code and send a PR. What say?

**Comment by edgarriba** [comment]
@cjpurackal defenitely, go ahead
