### ISSUE TITLE
rgb_to_yuv420 does not support (*, 3, H, W) format

### ISSUE THREAD

**Issue by ChristophReich1996** [kornia/kornia#2072]
### Describe the bug

The documentation of the `rgb_to_yuv420` function states that the `(*, 3, H, W)` format is supported. However, the average pooling function (torch.nn.functional.avg_pool2d) used after converting to YUV does not support an arbitrary amount of dimensions in the front.

### Reproduction steps

```bash
import torch
import kornia
from torch import Tensor

images: Tensor = torch.rand(2, 2, 3, 16, 16)
images_y, images_uv = kornia.color.rgb_to_yuv420(images)  # type: Tensor, Tensor
```

### Expected behavior

RuntimeError: Expected 3D or 4D (batch mode) tensor with optional 0 dim batch size for input, but got:[2, 2, 2, 16, 16]

### Environment

```shell
- PyTorch Version: `1.12.0`
- How you installed PyTorch: `conda`
- Python version: `3.9.12`
- CUDA/cuDNN version: CPU utilized
- Any other relevant information:
```

**Comment by edgarriba** [comment]
@ChristophReich1996 thanks for pointing this out, feel free to open a PR with the fix.
