### ISSUE TITLE
Add `pytorch-cuda` in the install script

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2082]
I really don't know, I just noticed that it is on the official recommendation page -- https://anaconda.org/pytorch/pytorch-cuda

![image](https://user-images.githubusercontent.com/20444345/207052535-2cac6b1b-71e2-474e-a1e0-af2dfdb8f316.png)

_Originally posted by @johnnv1 in https://github.com/kornia/kornia/pull/1987#discussion_r1045807237_

**Comment by johnnv1** [comment]
done in 67ee33c605f6a9dcbb7aaf7b38f39e728ea39017
