### ISSUE TITLE
warp_perspective3d() for depth images produces monochrome images

### ISSUE THREAD

**Issue by PiaCuk** [kornia/kornia#2102]
### Describe the bug

Previously, I used `kornia.geometry.warp_perspective()` to warp RGB images. Now, I have an additional depth map, and I want to warp the image taking into account the depth information as well. For this, I use  `kornia.geometry.warp_perspective3d()`. However, when I apply this method to my depth image, the output is a monochrome image.

Input:

![beach](https://user-images.githubusercontent.com/32837704/208654978-64b7bd35-b597-4d13-a18d-52019c995cf9.jpg)

Output:

![transformed_beach](https://user-images.githubusercontent.com/32837704/208655086-62b221d2-3c6f-4012-835f-9922804ccd91.jpg)

The tensors used are: 

1. The RGB images with shape [B, 3, H, W]
2. The depth maps with shape [B, 1, H, W]
3. The transformation matrix, which is the output of  `kornia.geometry.get_affine_matrix3d()`, with shape [B, 4, 4]

### Reproduction steps

```bash
import kornia.geometry.transform as K
from PIL import Image
import torch
from torchvision.transforms import ToTensor, ToPILImage

1. img = Image.open('beach.jpg')
2. img_tensor = ToTensor()(img)
3. matrix = K.get_affine_matrix3d(translations=torch.tensor([(0, 0, 0)], dtype=torch.float),
                                  center=torch.tensor([(img_tensor.shape[-1] // 2,
                                                        img_tensor.shape[-2] // 2, 0)],
                                                      dtype=torch.float),
                                  scale=torch.tensor([1], dtype=torch.float),
                                  angles=torch.tensor([(0, 0, 0)], dtype=torch.float))
# The matrix has shape [1, 4, 4]
# [[[1., 0., 0., 0.],
#   [0., 1., 0., 0.],
#   [0., 0., 1., 0.],
#   [0., 0., 0., 1.]]]

4. dsize = (1, *img_tensor.shape[-2:])
5. depth = torch.zeros(dsize) # The behaviour is the same for torch.ones(dsize)
6. img_tensor = img_tensor.unsqueeze(0)
7. depth = depth.unsqueeze(0)
8. src = torch.cat([img_tensor, depth], dim=1)
9. src = src.unsqueeze(2) # src now has shape [1, 4 , 1, 576, 768]
10. transformed = K.warp_perspective3d(src=src, M=matrix, dsize=dsize,
                                       border_mode='border', align_corners=True)
11. transformed = transformed.squeeze()[:3, : , :] # this is the results attached here
```

### Expected behavior

Since the transformation matrix is the identity matrix, and the depth maps only contains zeros, the output image should be the same as the input.

### Environment

```shell
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA Graphics Device
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==1.8.3
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.13.0
[pip3] torch-optimizer==0.3.0
[pip3] torch-pitch-shift==1.2.2
[pip3] torchaudio==0.13.0
[pip3] torchaudio-augmentations==0.2.4
[pip3] torchmetrics==0.10.3
[pip3] torchvision==0.14.0
[conda] Could not collect
```

**Comment by shijianjian** [comment]
The 3D version should be for `[B, N, D, H, W]` I think. The RGBD image is 2.5D. BTW, what is the expected output?

**Comment by PiaCuk** [comment]
@shijianjian thank you for your response. Can you explain what a `[B, N, D, H, W]` input would be? A depth image is typically a 4-channel RGB image, which, in my example, has the shape `[1, 4, 1, 576, 768]`. Regarding the expected output: Since the transformation matrix is the identity matrix, and the depth maps only contains zeros, the output image should be the same as the input. In my example, that is the beach image.

**Comment by shijianjian** [comment]
This function is designed for 3D volumetric data, while your example might be a corner case that only has 1 depth.

In your case, it makes more sense to use the 2D version with B4HW. Is there any errors for `warp_perspective`? Or what are the reasons for using the 3d one?

**Comment by PiaCuk** [comment]
Does `warp_perspective` take depth information into account? The reason I switched to 3D is to warp the perspective with respect to the depth information.

**Comment by edgarriba** [comment]
To take into account depth you might want to use warp_frame_depth

here is an example 

https://github.com/kornia/kornia-examples/blob/master/depth_estimation.ipynb
