### ISSUE TITLE
Weird behavior of LongestMaxSize

### ISSUE THREAD

**Issue by Optimox** [kornia/kornia#2123]
### Describe the bug

Hello me again,

I might be doing something wrong with the way I use kornia augmentations, please let me know if it is the case.

I was expecting `LongestMaxSize` in kornia to perform similarily as the albumentation implementation. Meaning that I can throw any images with different shapes to the the transformation function and get an image with different shapes but similar ratios. The largest size being equal to the value given to `LongestMaxSize`.

See bellow a small code sample that disturbs me.

### Reproduction steps

```bash
import kornia.augmentation as K
a = torch.ones((512, 256))
b = torch.ones((512, 756))

print("first try")
transfo = K.LongestMaxSize(max_size=256, p=1.)

print(transfo(a).shape)
print(transfo(b).shape)

print("second try")

a = torch.ones((512, 256))
b = torch.ones((512, 756))

transfo = K.LongestMaxSize(max_size=256, p=1.)
print(transfo(b).shape)
print(transfo(a).shape)

Outputs:
first try
torch.Size([1, 1, 256, 128])
torch.Size([1, 1, 256, 128])
second try
torch.Size([1, 1, 173, 256])
torch.Size([1, 1, 173, 256])
```

### Expected behavior

I would expect to have the same values for the transformations no matter the order of the elements.

ie `transfo(a).shape == torch.Size([1, 1, 256, 128])` and `transfo(b).shape ==torch.Size([1, 1, 173, 256])`

Am I missing something here ?

### Environment

```shell
kornia='0.6.9'
torch='1.12.1+cu113'
```

**Comment by Optimox** [comment]
Seems like Resize behave similarly when size in an integer.

**Comment by Optimox** [comment]
@johnnv1 @shijianjian Is this the expected behavior ?

**Comment by shijianjian** [comment]
@twsl Can you take a look?

**Comment by twsl** [comment]
Unfortunately I don't have much time right now, but a quick peek at the source code makes me wonder if the resize generator in the resize augmentation does include any checks to recalculate the parameters

**Comment by shijianjian** [comment]
@johnnv1 Can you help fix it if you got some time?

**Comment by johnnv1** [comment]
as @twsl commented, seems for this case we need to recompute the params -- i'm not sure of the best way to try avoid generating the params in each call
