### ISSUE TITLE
[OPTIMIZATION] disabled gradcheck test for extract patches

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#214]
The gradient check tests for `TestExtractPatchesSimple` and `TestExtractPatchesPyr` have been temporally disabled due to it takes 9min respect to 4min when are disabled. Detected during the migration of the tests to CircleCI in #212.

We should look for alternatives in the input sizes or look at the implementation to optimize the functionality.

**Comment by ducha-aiki** [comment]
It looks like all the spatial-transformer-like grad checks are very slow compared to the rest of functions. 
Probably the only possible thing to speed-up is  to reduce image/grid sizes

**Comment by edgarriba** [comment]
yeap, you can try to reduce the input - that's what I did for the warpers.

**Comment by edgarriba** [comment]
@ducha-aiki tests are enabled, still slow but not sure what we can do for now.
I guess we can close this and open new issue once the time arrives for real C++ optimization.
