### ISSUE TITLE
output range of rgb_to_lab function

### ISSUE THREAD

**Issue by gravitychen** [kornia/kornia#2149]
### Describe the bug

the range of a b channel of Lab color space is from -128 to +127, see [this](https://opentextbc.ca/graphicdesign/chapter/4-4-lab-colour-space-and-delta-e-measurements/#:~:text=It%E2%80%99s%20comprised%20of%20three%20axes%3A%20L%20represents%20darkness%20to%20lightness%2C%20with%20values%20ranging%20from%200%20to%20100%3B%20a%20represents%20greenness%20to%20redness%20with%20values%20of%20%2D128%20to%20%2B127%3B%20and%20b%20represents%20blueness%20to%20yellowness%20also%20with%20values%20from%20%2D128%20to%20%2B127.)
but the [comment](https://kornia.readthedocs.io/en/latest/_modules/kornia/color/lab.html#rgb_to_lab:~:text=The%20L%20channel%20values%20are%20in%20the%20range%200..100.%20a%20and%20b%20are%20in%20the%20range%20%2D127..127) shows the range is  -127 to +127

### Reproduction steps

```bash
1. check if there is something wrong with code implementation
2. Or maybe this is simply a comment not written correctly
```

### Expected behavior

match the theory of lab color space

### Environment

```shell
PyTorch version: 1.11.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-94-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: 

Nvidia driver version: 470.82.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
```

**Comment by johnnv1** [comment]
It seems to be just a typo issue in the docs, can you send a PR to fix it?

**Comment by gravitychen** [comment]
OK, please check
#2153
