### ISSUE TITLE
Add tutorials to CI

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#2171]
## 📚 Documentation

We have had issues with examples/tutorials in the past and continue to have them now (e.g. recently https://github.com/kornia/kornia/issues/2161), because out tutorials are not integrated into CI, therefore breaking changes will be unnoticed. 
We should add them into CI. A single PyTorch and Python version is enough. 

cc: @edgarriba @johnnv1

**Comment by johnnv1** [comment]
I will work to add to the tutorials repo a CI, once we have something working, I can also push it here -- I have made a fast test here and will need to update some tutorials too

**Comment by johnnv1** [comment]
Should we run the examples on the main repo too?

**Comment by edgarriba** [comment]
Maybe yes

**Comment by johnnv1** [comment]
Is it worth the effort to move these examples to the tutorials repo? Or should they stay here

**Comment by edgarriba** [comment]
We should yes. But no high priority for now

**Comment by johnnv1** [comment]
About the examples:

these don't use kornia
- [depth_regression](https://github.com/kornia/kornia/tree/master/examples/depth_regression)
- [depth_warper](https://github.com/kornia/kornia/tree/master/examples/depth_warper)
- [homography_regression](https://github.com/kornia/kornia/tree/master/examples/homography_regression) - Just `tensor_to_image` and `transform_points`

Already on the tutorials:
- [edge_detection](https://github.com/kornia/kornia/tree/master/examples/edge_detection)
- [face_detection](https://github.com/kornia/kornia/tree/master/examples/face_detection)
- [feature_detection](https://github.com/kornia/kornia/tree/master/examples/feature_detection) -- at least, I think we have the updated version of it

Need to be added to the tutorials:
- [geometry](https://github.com/kornia/kornia/tree/master/examples/geometry)
    - [ ] fit points
    - [ ] fit plan
- [train](https://github.com/kornia/kornia/tree/master/examples/train) 
    - [ ] classification
    - [ ] detection
    - [ ] semantic segmentation
