### ISSUE TITLE
The optional arguments for warp_affine and warp_perspective are not active

### ISSUE THREAD

**Issue by jasam-sheja** [kornia/kornia#218]
These two functions don't utilize their optional arguments.

kornia.geometry.transform.mgwarp.warp_affine:
`flags` (probably should be named `mode`) is not passed down or used
same for `padding_mode`

kornia.geometry.transform.mgwarp.warp_perspective:
its optional arguments are not mentioned in the documents!
`flags` (probably should be named `mode`) is not passed down or used
same for `border_mode` and `border_value`

**Comment by edgarriba** [comment]
@jasam-sheja @CoinCheung  I mark this as a feature request for v0.1.4

**Comment by edgarriba** [comment]
already solved
