### ISSUE TITLE
Missing AutoAugment Operations

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#2180]
I am working on AutoAugment stuff.

Need a hand to implement:
- ShearX
- ShearY
- TranslateX
- TranslateY
- AutoContrast
- Color (Refer to PIL.enhance.color)

We may have `RandomShear`, `RandomTranslate`, and `RandomAutoContrast`.

**Comment by miquelmarti** [comment]
For AutoContrast I just wrapped `kornia.enhance.normalize_min_max`, would that be the right way?

**Comment by shijianjian** [comment]
I think it might be more complex than that. You may refer to:

https://github.com/CoinCheung/fixmatch-pytorch/blob/9b5a31d194571fd7d8912032f12a5274d04be814/randaugment.py#L11

I think they somehow built a LUT there.

**Comment by miquelmarti** [comment]
I see... torchvision does something more like `normalize_min_max` and call it autocontrast though. https://github.com/pytorch/vision/blob/59dc9383e663a9bab5230370e1f0d7d14b87940f/torchvision/transforms/functional_tensor.py#L835

**Comment by shijianjian** [comment]
> I see... torchvision does something more like `normalize_min_max` and call it autocontrast though. https://github.com/pytorch/vision/blob/59dc9383e663a9bab5230370e1f0d7d14b87940f/torchvision/transforms/functional_tensor.py#L835

Can you try if it outputs similar image as PIL? I think it is okay if so.
