### ISSUE TITLE
Defmo weights

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia#2182]
I don't know if this is a temporary issue, but the weights of the module DeFMO are offline

```python
urls["defmo_encoder"] = "http://ptak.felk.cvut.cz/personal/rozumden/defmo_saved_models/encoder_best.pt"
urls["defmo_rendering"] = "http://ptak.felk.cvut.cz/personal/rozumden/defmo_saved_models/rendering_best.pt"
```

this is currently failing all tests on CI because `test/feature/test_defmo.py::TestDeFMO::test_jit` try to load the pre-trained model 

cc @edgarriba @ducha-aiki

**Comment by edgarriba** [comment]
Maybe we should try to host ourselves the weights in @ducha-aiki website?

**Comment by ducha-aiki** [comment]
It works now. 
Regarding my website - actually I host weights on the same university cluster, it just got under the maintenance for shortwhile.
