### ISSUE TITLE
kornia_augmentation.ipynb notebook is outdated

### ISSUE THREAD

**Issue by amrzv** [kornia/kornia#2205]
### Describe the bug

During
`import kornia.augmentation.functional as F`
an error raises:
`ModuleNotFoundError: No module named 'kornia.augmentation.functional'`

### Reproduction steps

```bash
1. Open `examples/augmentation/kornia_augmentation.ipynb` notebook in [colab](https://colab.research.google.com/github/kornia/kornia/blob/master/examples/augmentation/kornia_augmentation.ipynb)
2. Run all cells
```

### Expected behavior

Notebook runs without any errors.
Seems that notebook is outdated and no longer works with the last version of kornia.

### Environment

```shell
Default google colaboratory env.
- PyTorch Version (e.g., 1.0): 1.13.1
- OS (e.g., Linux): Ubuntu 20.04.5 LTS
- Python version: 3.8.10
- CUDA/cuDNN version: 11.2.152
- GPU models and configuration: Tesla T4
- kornia: 0.6.10.dev0
```

### Additional context

![image](https://user-images.githubusercontent.com/36787333/217533241-0df1e2f1-450e-4099-b726-97deb1bde2ba.png)

**Comment by johnnv1** [comment]
@amrzv thanks for the report. This is a really outdated example (from kornia 3.x 😅 ), you can check some more up-to-date examples at: https://kornia-tutorials.readthedocs.io -- Some examples (e.g aug sequential) need some changes which you can check here https://github.com/kornia/tutorials/pull/41
