### ISSUE TITLE
[Feature Request] Generic type and shape checks

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#223]
We might want to have generic functions to assert variables type and shapes.

See discussion: https://github.com/arraiyopensource/kornia/pull/219#discussion_r328084624

**Comment by edgarriba** [comment]
@lferraz @ducha-aiki was questioning myself whether should we use logging instead of raw prints

**Comment by ducha-aiki** [comment]
Pytorch itself mostly uses prints and asserts
https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L338
https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L552

**Comment by lferraz** [comment]
asserts is fine to me. However, I consider logging more flexible.

**Comment by ducha-aiki** [comment]
What about the following format

input: tensor name, list of possible shapes, e.g. [[None, None, 2]]
output: none, crash + print if error

Kind of stuff I have done here:
https://github.com/kornia/kornia/blob/master/kornia/feature/laf.py#L104

@lferraz, @edgarriba

**Comment by edgarriba** [comment]
@shijianjian @FGeri consider this discussion for the testing refactor
