### ISSUE TITLE
We don't have tests for all functions 

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#2231]
## 🚀 Feature

`denormalize_pixel_coordinates3d`
`normalize_pixel_coordinates3d` are not in tests. 

`normalize_pixel_coordinates3d` is used in https://github.com/kornia/kornia/blob/6d4f83cae02129b7f49acf022561711cd937e8b8/kornia/geometry/subpix/spatial_soft_argmax.py#L432 though. 

We might have other functions w/o tests actually...

**Comment by johnnv1** [comment]
if anyone has an interest in investigating the missing tests, an option to check is run `coverage report` for the specific case, e.g:

```bash
$ coverage erase && coverage run -m pytest test/geometry/test_conversions.py && coverage report --show-missing --skip-covered kornia/geometry/conversions.py 


============================= test session starts =============================
platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
rootdir: /tmp/kornia, configfile: setup.cfg
plugins: cov-4.0.0
collected 236 items                                                           

test/geometry/test_conversions.py ..................................... [ 15%]
....................................................................... [ 45%]
......................................................................s [ 75%]
............................................s.s.......s..               [100%]

======================= 232 passed, 4 skipped in 0.64s ========================
Name                             Stmts   Miss  Cover   Missing
--------------------------------------------------------------
kornia/geometry/conversions.py     448     53    88%   1014-1023, 1043-1052, 1068-1071, 1088-1106, 1126-1135, 1157-1172, 1189-1206, 1226-1242
--------------------------------------------------------------
TOTAL                              448     53    88%

```

Running coverage on all tests ends up omitting some lines/functions that are missing tests -- then I believe it must be something that must be done manually and carefully, so we can create tests for everything

**Comment by edgarriba** [comment]
This should be quite accurate: https://app.codecov.io/gh/kornia/kornia/tree/master/kornia

/cc @johnnv1

**Comment by johnnv1** [comment]
> /cc @johnnv1

if we had the tests for `spatial_soft_argmax.py` and this function runs `normalize_pixel_coordinates3d`, the normalize function will have coverage from the tests of `spatial_soft_argmax` -- but that doesn't mean that the function is being tested -- e.g codecov have reported the `normalize_pixel_coordinates3d` with coverage [here](https://app.codecov.io/gh/kornia/kornia/blob/master/kornia/geometry/conversions.py#L997), but we don't have test for that

**Comment by ducha-aiki** [comment]
Moreover, the function `normalize_pixel_coordinates3d` is wrong inside with variable names. But it matches the `spatial_soft_argmax` expectations, so combination works correctly.

**Comment by johnnv1** [comment]
Missing some augmentations tests -- check out https://github.com/kornia/kornia/pull/2499#discussion_r1309434288
