### ISSUE TITLE
Add Guided filter

### ISSUE THREAD

**Issue by gau-nernst** [kornia/kornia#2241]
## 🚀 Feature

Add Guided filter. It is an edge-preserving image smoothing filter, similar to bilateral filter.

https://kaiminghe.github.io/publications/eccv10guidedfilter.pdf

https://en.wikipedia.org/wiki/Guided_filter

OpenCV:

- https://docs.opencv.org/4.x/da/d17/group__ximgproc__filters.html#ga86813d59f8452a9600e979c6287805f5
- https://github.com/opencv/opencv_contrib/blob/4.x/modules/ximgproc/src/guided_filter.cpp

Matlab: https://www.mathworks.com/help/images/ref/imguidedfilter.html

Some PyTorch implementations

- https://github.com/wuhuikai/DeepGuidedFilter/blob/master/GuidedFilteringLayer/GuidedFilter_PyTorch/guided_filter_pytorch/guided_filter.py (grayscale image only)
- https://github.com/perrying/guided-filter-pytorch/blob/master/guided_filter.py (grayscale and RGB)

Guided filter for 1-channel (grayscale) image is simple and straight-forward. However, for multi-channel (RGB), we need to calculate the covariance matrix for the channels (treat each channel as a random variable), and calculate matrix inverse. perrying's implementation hard-codes this calculation.

## Pitch

Perhaps we can add guided filter for single channel first? Then we can decide if we want to only support RGB images (then it's possible to hard-code the calculations) or >3-channel images.

## Additional context

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by edgarriba** [comment]
+q for this

**Comment by edgarriba** [comment]
@gau-nernst are you planning to work soon on that ? otherwise i can take that one

**Comment by gau-nernst** [comment]
I can work on this this week. Have you decided how we should handle multi-channels? Single channel (grayscale) image is straightforward. Multi-channel (e.g. RGB) is complicated since we need to perform matrix inversion (see Equation 14 - https://kaiminghe.github.io/publications/eccv10guidedfilter.pdf)
