### ISSUE TITLE
numpy dependencies in some functions

### ISSUE THREAD

**Issue by lferraz** [kornia/kornia#2274]
### Describe the bug

some functions require niumpy and it is not a dependency.

Concretelly:
line 177 and 254 in kornia/augmentation/_2d/geometric/crop.py
line 144 in kornia/augmentation/_2d/geometric/base.py
line 282 in kornia/feature/laf.py

Solution:
add numpy dependency or remove reerences.

### Reproduction steps

```bash
try to use any of the functions I said.
```

### Expected behavior

not crashing

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:
```


### Additional context

_No response_

**Comment by edgarriba** [comment]
would be great to add this before the release of 0.7. @lferraz i can help you to fix this during the weekend
