### ISSUE TITLE
`NotImplementedError` for elastic transformation with probability p < 1

### ISSUE THREAD

**Issue by JanSellner** [kornia/kornia#2301]
### Describe the bug

With the newest kornia release (0.6.11), the random elastic transformation fails if it is not applied to every image in the batch.

The problem is that the `apply_non_transform_mask()` method in `_AugmentationBase` per default raises an `NotImplementedError` and since this method is not overwritten in `RandomElasticTransform`, the error is raised. I see that for the other `apply_non*` methods the default is to just return the input.

I see two different solutions:
1. Change the default for `apply_non_transform_mask` to return the input in `_AugmentationBase`.
2. Overwrite the method in `RandomElasticTransform` and just return the input there.

There might be good reasons to keep the `NotImplementedError` in the base class, therefore I wanted to ask first what solution you prefer. I could make a PR for this.

### Reproduction steps

```python
import torch
import kornia.augmentation as K

features = torch.rand(5, 100, 480, 640, dtype=torch.float32, device="cuda")
labels = torch.randint(0, 10, (5, 1, 480, 640), dtype=torch.int64, device="cuda")

torch.manual_seed(0)
aug = K.AugmentationSequential(
    K.RandomElasticTransform(alpha=(0.7, 0.7), sigma=(16, 16), padding_mode="reflection", p=0.2)
)

features_transformed, labels_transformed = aug(features, labels.float(), data_keys=["input", "mask"])
```

### Expected behavior

No `NotImplementedError`.

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- PyTorch Version (e.g., 1.0): 2.0
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.10.9
- CUDA/cuDNN version: 11.8
- GPU models and configuration: 3090
- Any other relevant information:
```

**Comment by shijianjian** [comment]
@JanSellner Please overwrite the `apply_non_transform_mask` of `RandomElasticTransform`.
