### ISSUE TITLE
[Feature Request] Implement addWeighted

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#233]
we might want to implement `addWeighted` from OpenCV.

https://docs.opencv.org/3.4/d2/de8/group__core__array.html#gafafb2513349db3bcff51f54ee5592a19

the motivation is that all can be used as base to implement all the adjust functions

**Comment by kshitij12345** [comment]
@edgarriba Would like to work on it if that is okay with you.

Just wondering in which of the current namespace will it fit or should there be a namespace with core functionality.

**Comment by edgarriba** [comment]
that would be awesome. We can place inside kornia.color by now. Ping us in case you need any help
