### ISSUE TITLE
Integrate PyTorch minimal solvers 

### ISSUE THREAD

**Issue by Parskatt** [kornia/kornia#2347]
## 🚀 Feature

PyTorch minimal solvers and more advanced ransac loops.

Implementations for nister/stewenius are available here: https://github.com/weitong8591/differentiable_ransac

I would be willing (when I get the time), to help out.

## Motivation

Kornia lacks good minimal solvers / ransac loops.

**Comment by ducha-aiki** [comment]
Amazing! Actually @weitong8591 herself was planning to make a PR into kornia, but after the paper acceptance.
