### ISSUE TITLE
Create `draw_point2d`

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2352]
Right now we have `render_gaussian2d` to "draw" 2d points, but would be great to find user friendly function that you can pass an input tensor and draw some points.

https://kornia.readthedocs.io/en/latest/geometry.subpix.html#kornia.geometry.subpix.render_gaussian2d

**Comment by alex-jw-brooks** [comment]
Hi @edgarriba, I'd like to contribute this. Could you please clarify how this differs from [`_draw_pixel`](https://github.com/kornia/kornia/blob/master/kornia/utils/draw.py#L11) in the utils?

I assume that the intent here is to add a capability similar to [`circle()`](https://docs.opencv.org/4.x/d6/d6e/group__imgproc__draw.html#gaf10604b069374903dbd0f0488cb43670) in OpenCV, where by default the behavior just plots the individual pixels, but the radius etc can be configured to draw circles around one or more centered points. Is that correct?

**Comment by edgarriba** [comment]
I would add first draw pixel configurable and vectorised so that we can make later draw_circle that will calculate the locations based on circle equation. Open question whether coordinates should be with subpixel precision and use a proxy grid_sample . Maybe we can add the second later since it might require creating an auxiliary image mask where to pull from values /cc @ducha-aiki
