### ISSUE TITLE
Class weighting for focal loss

### ISSUE THREAD

**Issue by ptr-br** [kornia/kornia#2365]
## 🚀 Feature
Current implementation of the [focal_loss](https://github.com/kornia/kornia/blob/master/kornia/losses/focal.py#L16) has a scalar weighting factor alpha. In my opinion this does not reflect the intention of a class weighting factor but rather only scales the loss.

## Pitch

I would suggest to have alpha as a list/tensor of class weights and apply this weighting to the specific classes. 

My current fix is to add one line of code that adapts the dimensions properly right before the weighting is applied [here](https://github.com/kornia/kornia/blob/master/kornia/losses/focal.py#L81).

```python
 alpha = alpha[(None, ) + (slice(None),) * 1 + (None, ) * len(input.shape[2:])]
```
I could create a pr for this if wanted.

**Comment by johnnv1** [comment]
this would not be the same problem reported in #875?

**Comment by ptr-br** [comment]
Oh yeah, you are right.
Did not see this thread, sorry :)
