### ISSUE TITLE
[Feature request] RGB to Lab, Lab to RGB

### ISSUE THREAD

**Issue by Oktai15** [kornia/kornia#239]
It would be great if you implemented differentiable conversation between RGB and Lab.

**Comment by edgarriba** [comment]
@Oktai15 thanks for the request. I add here a reference link from OpenCV so that we can start looking into it before starting the implementation: https://docs.opencv.org/master/de/d25/imgproc_color_conversions.html

**Comment by HassanAlsamahi** [comment]
@edgarriba I'll work on this, if still available

**Comment by edgarriba** [comment]
@HassanAlsamahi sure go ahead

**Comment by peterjiz** [comment]
I forked the code and implemented lab_to_rgb and rgb_to_lab
[lab_color_space](https://github.com/peterjiz/kornia/tree/lab_color_space)

**Comment by edgarriba** [comment]
Great, please open a PR

**Comment by peterjiz** [comment]
Done!

**Comment by edgarriba** [comment]
This is a work in progress https://github.com/kornia/kornia/pull/712

**Comment by edgarriba** [comment]
merged in https://github.com/kornia/kornia/pull/784
