### ISSUE TITLE
Implement MobileSAM

### ISSUE THREAD

**Issue by gau-nernst** [kornia/kornia#2426]
## 🚀 Feature

Integrate MobileSAM into Kornia as an alternative to SAM.

https://github.com/ChaoningZhang/MobileSAM

## Pitch

From the look of it, architecture-wise, only the backbone is changed to TinyVIT (https://arxiv.org/abs/2207.10666). Thus adapting MobileSAM to the current SAM codebase (inference only) should be simple. The license is Apache-2.0, so I think it should be fine too.
______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by edgarriba** [comment]
Looks good to me
