### ISSUE TITLE
Use Kornia resize in ResizePreprocessor in ObjectDetector

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2439]
Use Kornia resize in ResizePreprocessor

_Originally posted by @edgarriba in https://github.com/kornia/kornia/pull/2363#discussion_r1257304346_

**Comment by jeffin07** [comment]
@edgarriba Did you mean to replace `[F.interpolate(img.unsqueeze(0), self.size, mode=self.interpolation_mode) for img in imgs]` with `kornia.augmentation.Resize` ? Can you please guide me on this issue i would like to work on this if this is still open

**Comment by edgarriba** [comment]
@jeffin07 yes, that's the idea. For contributing please check https://github.com/kornia/kornia/blob/master/CONTRIBUTING.md

/cc @gau-nernst
