### ISSUE TITLE
[Enhancement] Input of functions in color conversions.

### ISSUE THREAD

**Issue by HassanAlsamahi** [kornia/kornia#244]
I've noticed that the input of some functions in color conversions, has to be floating points and normalized, and I know that this is required for the conversion, but what about implementing the floating conversion and normalization inside the function so that it doesn't confuse the user?

**Comment by edgarriba** [comment]
if it's well specified in the docs I don't think it's confusing. The target of the library is training and we usually deal with normalized tensors. In pytorch 1.3 there is quantization by default, but not sure how this can help.
