### ISSUE TITLE
np.ndarray should be used instead of np.array in type hints

### ISSUE THREAD

**Issue by aerobio** [kornia/kornia#246]
The tutorials and the documentation show the use of **np.array** as the return type for methods returning numpy arrays. For example:

    img_bgr: np.array = cv2.imread('./data/arturito.jpeg')

However, the class defining an array in numpy is **np.ndarray**, while **np.array** is a function that constructs arrays:

    >>> import numpy as np
    >>> type(np.array)
    <class 'builtin_function_or_method'>
    >>> type(np.ndarray)
    <class 'type'>

Static checkers like mypy will complain when [stub files for numpy](https://github.com/rmcgibbo/numpy-mypy) are available.

**Comment by edgarriba** [comment]
@aerobio you are right. We will update. Any help is always welcomed :D

**Comment by aerobio** [comment]
Sorry to bother you with the same issue, but the [tutorials](https://github.com/kornia/tutorials/blob/master/source/hello_world_tutorial.ipynb) insist on using `np.array` instead of `np.ndarray`:

    img_bgr: np.array = cv2.imread('arturito.jpg')

**Comment by edgarriba** [comment]
that's a typo -- worth sending a PR with the update
