### ISSUE TITLE
Add from / to euler angle in Quaterion

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2467]
## 🚀 Feature

We would like a direct interface for the [Quaternion](https://github.com/kornia/kornia/blob/02de36a3dbe6fe7361c9a5cea78974413f09f67d/kornia/geometry/quaternion.py#L19) class to go from / to Euler angles implemented in
https://github.com/kornia/kornia/blob/02de36a3dbe6fe7361c9a5cea78974413f09f67d/kornia/geometry/conversions.py#L739

```python
quat = Quaternion.from_euler(roll, pitch, yaw)
euler: Tensor = quat.to_euler()

```

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by Tchaikovic** [comment]
@edgarriba can I take this?
