### ISSUE TITLE
is Kornia modules differentiable actually?

### ISSUE THREAD

**Issue by sipie800** [kornia/kornia#2487]
If I don't misunderstand it, the purpose of Kornia is to build differentiable CV operator as trainable torch modules. 
However after I learned the demo jupyter books or the document tutorials, I just found that it seems to be a bunch of torch-based OpenCV functions? It's nice to have a CV operator in a torch module just like a training-free nn.Relu. 
But is that all ? Few examples is about building a learnable modules and training. 
Forgive me if I didn't investigate carefully, may I understand the purpose of the existing implementations? 

Say if I want to build a simple torch colorjitter module which learn 2 or 3 parameters in a regular colorjitter operator, how can I implement this with Kornia? Does it mean that I must write the autograd myself because I can't find a trainable colorjitter module in Kornia code. The codes are all just about the plain forward?

**Comment by edgarriba** [comment]
You can find what you ask in this paper: https://arxiv.org/pdf/2011.09832.pdf

Besides, check well the code and you'll see that a high percentage of the operators tests cover gradcheck.
