### ISSUE TITLE
refractor `kornia.geometry` to use `kornia.core` instead of `torch`.

### ISSUE THREAD

**Issue by cjpurackal** [kornia/kornia#2511]
_Originally posted by_ @cjpurackal  in https://github.com/kornia/kornia/pull/2509#discussion_r1288388256

**Comment by cjpurackal** [comment]
@Tchaikovic please go ahead :+1:

**Comment by Tchaikovic** [comment]
@cjpurackal great! I will break this down into multiple PRs as it is my first open source contribution.
