### ISSUE TITLE
Allow different filling formats

### ISSUE THREAD

**Issue by priba** [kornia/kornia#2534]
## 🚀 Feature

Warp operators (https://kornia.readthedocs.io/en/latest/geometry.transform.html#warp-operators) should allow fill values for different sizes. For example `warp_perspective` and `warp_affine` should allow filling values for one channel images.

## Motivation

Apply data augmentation in 1 channels images such as grayscale or IR.

## Pitch

Filling value should match the size of the channels rather than asking always to have size 3

**Comment by edgarriba** [comment]
@priba isn't this scenario working for you ? maybe it's a docu typo
https://github.com/kornia/kornia/blob/master/kornia/geometry/transform/imgwarp.py#L222

**Comment by priba** [comment]
There is a `ValueError` just before this function is called. Maybe it works but I guess it might need to be properly tested that removing the `raise` do not effect anything else.

See: https://github.com/kornia/kornia/blob/4cd9a61f50c4661d829a15703ca86260012d30e2/kornia/geometry/transform/imgwarp.py#L190
