### ISSUE TITLE
Reduce repository size from history

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2540]
## 🚀 Feature

Reported by: https://twitter.com/Parskatt/status/1699658729161924681

Possibly files like old testing images, or notebooks were not properly deleted from the repo history.

Explore using: https://rtyley.github.io/bfg-repo-cleaner/

______________________________________________________________________

#### Consider also to contribute to Kornia universe projects :)

<sub>

- [**Tutorials**](https://github.com/kornia/tutorials): our repository containing the tutorials.

</sub>

**Comment by johnnv1** [comment]
related to #1650 -- we never did the history clean
