### ISSUE TITLE
SOLD2 - ability to load the pretrained model from an arbitrary path

### ISSUE THREAD

**Issue by ogencoglu** [kornia/kornia#2544]
## 🚀 Feature

SOLD2 line segment detection has the `pretrained` argument. Would be very useful if the path to the pretrained model can also be specified.

## Motivation

This will ease productionizing SOLD2 without having to meddle with the source code of SOLD2 in kornia.

**Comment by edgarriba** [comment]
i think that should be feasible to add. Are you open to contribute ?

**Comment by ogencoglu** [comment]
In the end I ended up converting the models to onnx and loading that. I will close that now.

**Comment by edgarriba** [comment]
@ogencoglu if you are open to contribute with those onnx models, we recently added support for onnxruntime in superglue that would be interesting to have i think for SOLD2 as well. See: https://github.com/kornia/kornia/tree/master/kornia/feature/lightglue_onnx /cc @ducha-aiki
