### ISSUE TITLE
SOLD2 output line and junction heatmaps have different shape than eachother and from the original tensor

### ISSUE THREAD

**Issue by ogencoglu** [kornia/kornia#2546]
### Describe the bug

SOLD2 line segment detection outputs line and junction heatmaps but their shape can be both different from each other as well as different from the original tensor.

It is not clear how to overlay the results to the original image and where would the detected line segments be located if the heatmap shapes are different from the original image.

Code to replicate is given below.

### Reproduction steps

```bash
image_tensor = torch.Tensor(np.random.randn(1, 1, 532, 847))  # shape = (1, 1, 532, 847)
sold2_model = K.feature.SOLD2_detector(pretrained=True)
with torch.inference_mode():
    outputs = sold2_model(image_tensor)
junction_heatmap = outputs["junction_heatmap"]  # shape = [1, 536, 848]
line_heatmap = outputs["line_heatmap"]  # shape = [1, 532, 848]
```

### Expected behavior

Both of the heatmaps having the same size/shape as the original tensor (532 x 847 in the example above)

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
- PyTorch Version (e.g., 1.0): 2.0
- OS (e.g., Linux): Mac
- How you installed PyTorch (`conda`, `pip`, source): conda
- Build command you used (if compiling from source):
- Python version: 3.11
- CUDA/cuDNN version: -
- GPU models and configuration: CPU only
- Any other relevant information:
```


### Additional context

_No response_

**Comment by rpautrat** [comment]
Due to several downsampling and upsampling, the size of the heatmaps can indeed change. I think that the original dimensions must be divisible by 8 to keep the same resolution as in the output.

However, if I remember correctly, the output size will always be bigger than the input size, and you can simply crop the output to make it fit with the input one, removing the right and bottom borders. In your case, you could do this:
```
h, w = image_tensor.shape[2:4]
junction_heatmap_cropped = junction_heatmap[:, :h, :w]
line_heatmap_cropped = line_heatmap[:, :h, :w]
```

**Comment by ogencoglu** [comment]
@ducha-aiki I know. But I need and am using heatmaps for other purposes as well.

I confirm that dims need to be divisible by 8 to have the same resolution. Thanks. This is enough I think.
