### ISSUE TITLE
Add the deprecated decorator in `depth_to_3d`

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2560]
we should add the deprecated decorator there: https://github.com/kornia/kornia/blob/a212b4d0746b15a4e56a34e72ddee9b320284fb9/kornia/utils/helpers.py#L70

_Originally posted by @johnnv1 in https://github.com/kornia/kornia/pull/2557#discussion_r1333672167_

**Comment by karakumm** [comment]
can I resolve it? :) @edgarriba

**Comment by johnnv1** [comment]
> can I resolve it? :) @edgarriba

of course, place a PR for it 😄
