### ISSUE TITLE
Add an alias `average_enpoint_error = aepe` (or viceversa)

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2597]
i'd also add an alias `average_enpoint_error = aepe` (or viceversa) to have more explicit name functions

_Originally posted by @edgarriba in https://github.com/kornia/kornia/pull/2500#discussion_r1335526211_

**Comment by be-unkind** [comment]
can I resolve this issue?😃 @edgarriba

**Comment by johnnv1** [comment]
> can I resolve this issue?😃 @edgarriba

of course, place a PR for it 😄
