### ISSUE TITLE
ImportError: cannot import name 'QuaternionCoeffOrder' from 'kornia.geometry.conversions'

### ISSUE THREAD

**Issue by jelenastojanovic95** [kornia/kornia#2599]
### Describe the bug

when I try to run script I've got the error that 'QuaternionCoeffOrder' cannot be imported.
I've also checked file kornia.geometry.conversions.py and I couldn't find name QuaternionCoeffOrder.
I've install kornia using `pip install git+https://github.com/kornia/kornia` command
Can you help me, how to solve this problem?

### Reproduction steps

```bash
1. from kornia.geometry.conversions import QuaternionCoeffOrder
2. error occurs
```

### Expected behavior

importing QuaternionCoeffOrder or telling me which function can replace that name

### Environment

```shell
- PyTorch Version (1.13.1+cu116 ):
- OS (e.g., Linux):
- How you installed PyTorch ( `pip`):
- Build command you used (if compiling from source):
- Python version 3.8.10:
- CUDA/cuDNN version 11.6:
```

**Comment by edgarriba** [comment]
@jelenastojanovic95 `QuaternionCoeffOrder` was deprecated in the  0.7.0 release in favour of simplicity during maintenance and keep a single quaternion format
