### ISSUE TITLE
Create test for Auto Modules with `InputTensor` / `OutputTensor`

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#2602]
@johnnv1 i think as post meta task from this we could exploring to prototype an AutoModule that basically given a function parsed via `inspect` to automatically generate Modules. This might requires creating `InputTensor` / `OutputTensor`  alias types.

_Originally posted by @edgarriba in https://github.com/kornia/kornia/pull/2588#discussion_r1343692970_

**Comment by johnnv1** [comment]
is it the same thing of https://github.com/kornia/kornia/issues/2751 ?

**Comment by edgarriba** [comment]
nope but let's skip for now
