### ISSUE TITLE
CI Fails testing the Sift Descriptor

### ISSUE THREAD

**Issue by dvd42** [kornia/kornia#270]
The CI fails whenever testing the  `test_batch_shape_non_std function` from the sift descriptor because it takes too long.

```
test/feature/test_siftdesc.py::TestSIFTDescriptor::test_batch_shape_non_std Makefile:9: recipe for target 'test-cpu-cov' failed
make: *** [test-cpu-cov] Terminated
Too long with no output (exceeded 10m0s)
```
Is there an easy way to fix this?

**Comment by ducha-aiki** [comment]
@dvd42 what happened with CI setup then? Tests were working last week for sure

**Comment by dvd42** [comment]
Ok it seems like its not consistent, sometimes it breaks because the test took too long and other times it just runs fine. Unfortunately I am unaware of how the CI works internally and don't now what the problem might be.

**Comment by edgarriba** [comment]
I've seen this behavior in some PRs. Let's keep tracked of this

**Comment by edgarriba** [comment]
solved
