### ISSUE TITLE
[Feature request] CLAHE implementation

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#271]
Recent ICCV 2019 paper (http://cmp.felk.cvut.cz/daynightretrieval/)  shows that CLAHE filtering greatly improves day-night recognition and is not worse than complex learned image translation stuff.  Besides CNNs, CLAHE was used for a long time for king of illumination-invariant recognition
I think, it is good thing to have in kornia.

![image](https://user-images.githubusercontent.com/4803565/67215014-0bc3f300-f421-11e9-87fc-e4676f4f12bb.png)

OpenCV implementation: https://github.com/opencv/opencv/blob/master/modules/imgproc/src/clahe.cpp
CLAHE paper (in book, pages 472 - 483):
http://cas.xav.free.fr/Graphics%20Gems%204%20-%20Paul%20S.%20Heckbert.pdf

**Comment by edgarriba** [comment]
another thing related to this could be histogram equalization"
https://stackoverflow.com/questions/28518684/histogram-equalization-of-grayscale-images-with-numpy

**Comment by Noezor** [comment]
Will look into CLAHE first from Heckbert's book. Will try to do a PR by this week-end.
IDK if we can write fully differentiable Histogram Equilization though. I will aim for it.

**Comment by ducha-aiki** [comment]
Sure, go ahead!

I think that differentiable histogram can be done similarly to this gaussian (or triangular) kernel density:

https://papers.nips.cc/paper/7545-unsupervised-learning-of-shape-and-pose-with-differentiable-point-clouds.pdf
![image](https://user-images.githubusercontent.com/4803565/70186327-fc0c1f80-16eb-11ea-96d5-ed9c97d613e9.png)
