### ISSUE TITLE
Add/move `_differentiable_clipping`, ` _differentiable_polynomial_floor` and ` _differentiable_polynomial_rounding` to our utilities functions

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia#2761]
for a further pr, i think having `_differentiable_clipping`, ` _differentiable_polynomial_floor` and ` _differentiable_polynomial_rounding` into our utilities can be usefully :)

_Originally posted by @johnnv1 in https://github.com/kornia/kornia/pull/2748#discussion_r1464089248_

**Comment by jeffin07** [comment]
@johnnv1 Where do you prefer moving these in utils ?  `utils/helpers.py` a good option ?

**Comment by johnnv1** [comment]
> @johnnv1 Where do you prefer moving these in utils ? `utils/helpers.py` a good option ?

hi, it can be moved to `utils/misc.py` that file already had some ops
