### ISSUE TITLE
Can kornia be used for bounding box/ keypoint data augmentation

### ISSUE THREAD

**Issue by pablovela5620** [kornia/kornia#277]
I see this can be used for different affine/perspective transformations for an image, can this library also be used to perform the same transformation on bounding box/ keypoint coordinates batched on the gpu? If so how?

**Comment by ducha-aiki** [comment]
Not yet exactly. We will add this for our plan. https://github.com/arraiyopensource/kornia/issues/279
In mean time, if you have transformation in format of homography matrix, you can use this function:

https://kornia.readthedocs.io/en/latest/geometry.linalg.html#kornia.geometry.linalg.transform_points

**Comment by pablovela5620** [comment]
Gotcha, thanks for the response. I'm assuming that getting the homography matrix is non-trivial and there is no function implementation in kornia? Not the same as getting a transformation matrix (Rotation/translation?)

**Comment by ducha-aiki** [comment]
It depends on what you are starting from :) 
If you have 4 corners before and after, then just apply this
https://kornia.readthedocs.io/en/latest/geometry.transform.html#kornia.geometry.transform.get_perspective_transform

If rotation angle is available, then use https://kornia.readthedocs.io/en/latest/geometry.transform.html#kornia.geometry.transform.get_rotation_matrix2d and add 3rd row == [0, 0, 1]

**Comment by dvd42** [comment]
@pablovela5620 check out the new[ data augmentaion module ](https://kornia.readthedocs.io/en/latest/augmentation.html)
