### ISSUE TITLE
[Feature Request] draw polygonal curves use kornia

### ISSUE THREAD

**Issue by zccyman** [kornia/kornia#278]
How do I draw polygonal curves like using the OpenCV function cv2.polylines when I have known coordinates?

**Comment by ducha-aiki** [comment]
We don`t have drawing functions yet I believe, except rendering blobs:

https://kornia.readthedocs.io/en/stable/geometry.html#kornia.geometry.render_gaussian_2d

**Comment by edgarriba** [comment]
we don't have it, however would be great if we can implement it using standard pytorch functions

**Comment by edgarriba** [comment]
added in the roadmap. Lets discuss here the api, functionalities and so.

**Comment by edgarriba** [comment]
continue discussion here https://github.com/kornia/kornia/issues/936
