### ISSUE TITLE
[Feature request] Tensor as factor input for color.adjust_hue and color.adjust_saturation

### ISSUE THREAD

**Issue by smounsav** [kornia/kornia#280]
Hi, I've noticed that the functions color.adjust_brightness and color.adjust_contrast are accepting tensors as factor input and can process batches.
However, color.adjust_hue and color.adjust_saturation are only accepting a single float as factor. Would it be possible to extend those 2 functions, so that they handle tensors as well?
Thx.

**Comment by edgarriba** [comment]
It definitely can.  Similar to: https://github.com/arraiyopensource/kornia/blob/master/kornia/color/adjust.py#L95

the factor need to be extended to `Union[float, torch.Tensor]` and later just adapt shapes. Would be great if you could contribute with that.

**Comment by smounsav** [comment]
Sure, I've already started the corrections on my local machine. I'll go through the contribution guideline to know the process for pull requests.

**Comment by edgarriba** [comment]
@smounsav cool ! let me know if you need help

**Comment by smounsav** [comment]
Hi, this has already been handled in PR #324 (https://github.com/kornia/kornia/pull/324), so I think we can close this issue.
