### ISSUE TITLE
Replace Kmeans `euclidean_distance` method by `kornia.geometry.linalg.euclidean_distance`

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia#2809]
you can use existing `euclidean_distance`: https://github.com/kornia/kornia/blob/69a697020a5f63ba7d46369673709c4f23d72313/kornia/geometry/linalg.py#L241

_Originally posted by @edgarriba in https://github.com/kornia/kornia/pull/2804#discussion_r1489182309_

For that needs to remove the line https://github.com/kornia/kornia/blob/69a697020a5f63ba7d46369673709c4f23d72313/kornia/geometry/linalg.py#L254

On Kmeans internals, we also may be able to replace a sum of the distances: 
> probably here we can reuse the euclidean distance routine if we adjust the function to pass the reduction axis ?

_Originally posted by @edgarriba in https://github.com/kornia/kornia/pull/2804#discussion_r1489184226_

**Comment by smruthi-sumanth** [comment]
HI! Newbie to OSS. Can I work on your issue?

**Comment by johnnv1** [comment]
> HI! Newbie to OSS. Can I work on your issue?

Sure, If you have any questions, just call us on Slack, or open a PR for discussion

**Comment by yoii18** [comment]
Hi @johnnv1, is this issue under work? I have replaced the sum with the Euclidean distance function as suggested [here](https://github.com/kornia/kornia/pull/2804#discussion_r1489184226)

Should I create a PR or should I wait for @smruthi-sumanth to finish?
