### ISSUE TITLE
[BUG] crop_and_resize doesn't work when it changes image aspect ratio

### ISSUE THREAD

**Issue by potocpav** [kornia/kornia#281]
Here is a failing test-case, adapted from [this test](https://github.com/arraiyopensource/kornia/blob/a48164b1274827773f3da36dcbe2879c69f4471c/test/geometry/transform/test_crop.py#L14) but with some aspect-ratio distortion:
```python3
>>> inp = torch.tensor([[
            [1., 2., 3., 4.],
            [5., 6., 7., 8.],
            [9., 10., 11., 12.],
            [13., 14., 15., 16.],
        ]])
>>> height, width = 2, 3
>>> boxes = torch.tensor([[
            [1., 1.],
            [1., 2.],
            [2., 1.],
            [2., 2.],
        ]])
>>> kornia.crop_and_resize(inp, boxes, (height, width))
tensor([[[ 6.0000,  7.0000,  8.0000],
         [ 8.0000,  9.0000, 10.0000]]])
```
But the expected result, as per [documentation](https://torchgeometry.readthedocs.io/en/latest/geometry.transform.html#kornia.geometry.transform.crop_and_resize), is:
```python
torch.tensor([[[6., 6.5, 7.],
               [10., 10.5, 11.]]])
```

The issue seems to be caused by a mis-use of the `get_perspective_transform` function by `crop_and_resize`. The arguments to [`get_perspective_transform`](https://torchgeometry.readthedocs.io/en/latest/geometry.transform.html#kornia.geometry.transform.get_perspective_transform) expect points to be written in [x,y] format (not documented), but `crop_and_resize` passes them in [y,x]. The [x,y] ordering in `get_perspective_transform` is [used in this example](https://kornia.readthedocs.io/en/latest/tutorials/warp_perspective.html).

The existing tests for `crop_and_resize` are written in such an unfortunate way that they work both ways.

**Comment by potocpav** [comment]
The question is how to correct this:

1. Change `crop_and_resize` to take [x,y]
2. Change `get_perspective_transform` to take [y,x]
3. Leave the interfaces as-is, and convert between the representations inside `crop_and_resize`

**Comment by potocpav** [comment]
I will submit a PR if we decide which approach to take.

**Comment by edgarriba** [comment]
@potocpav good catch ! I would go for 1 just make thing simple. If you can also update the test to cover this corners cases would be great.
