### ISSUE TITLE
[BUG] setup_dev_env for MacOSX

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#282]
the [`setup_dev_env.sh`](https://github.com/arraiyopensource/kornia/blob/master/setup_dev_env.sh#L20) script should be able to detect whether is running under a linux or macosx system since the miniconda binary is different.

Linux: `Miniconda3-latest-Linux-x86_64.sh`
MacOSX: `Miniconda3-latest-MacOSX-x86_64.sh`

**Comment by tdchaitanya** [comment]
In the pull request #285, I have modified the `setup_dev_env.sh` and haven't touched any other files. Not sure why the python 3.6 test is failing. Could you please help me find the reason @edgarriba

**Comment by tdchaitanya** [comment]
The issue has been resolved !!
