### ISSUE TITLE
AttributeError: module 'kornia.augmentation' has no attribute 'RandomSaltAndPepperNoise'

### ISSUE THREAD

**Issue by f-amerehi** [kornia/kornia#2821]
When calling [RandomSaltAndPepperNoise](https://kornia.readthedocs.io/en/latest/augmentation.module.html#kornia.augmentation.RandomSaltAndPepperNoise) it returns an AttributeError.

### Reproduction steps

```bash
import kornia
kornia.augmentation.RandomSaltAndPepperNoise(amount=(0.01, 0.06), salt_vs_pepper=(0.4, 0.6), p=0.5, same_on_batch=False, keepdim=False)
```
```


### Expected behavior

load without an error: AttributeError: module 'kornia.augmentation' has no attribute 'RandomSaltAndPepperNoise'

### Environment

```shell
- PyTorch Version 2:
- OS : Windows
- How you installed PyTorch (`conda`, `pip`, source): Conda 
- Python version:3.11
- CUDA/cuDNN version:12
- GPU models and configuration: RTX 3080
```

**Comment by johnnv1** [comment]
Hey, I believe this augmentation is available only on master for now and will be present in the next release  (0.7.2 on end of march)

 Should be fine if you install kornia from git `pip install git+https://github.com/kornia/kornia`, can you try it?

**Comment by f-amerehi** [comment]
Hi @johnnv1. Many thanks. It works now.
