### ISSUE TITLE
`AugmentationSequential` does not support instance masks shape (N, H, W)

### ISSUE THREAD

**Issue by ashnair1** [kornia/kornia#2855]
### Describe the bug

Currently `AugmentationSequential` does not seem to support instance masks i.e. an image (C, H, W) having multiple masks (N, H, W). 

### Reproduction steps

The following code snippet errors out with a `RuntimeError: Expect (B, C, H, W). Got torch.Size([3, 256, 256]).` error.

```python
import torch
import kornia.augmentation as K

img = torch.randn(3, 256, 256)
masks = torch.ones( 2, 256, 256)

aug_dict = K.AugmentationSequential(
    K.RandomHorizontalFlip(p=1.0),
    data_keys=None,
    keepdim=True,
)
aug_dict.keepdim = True

data = {'image': img, 'mask': masks}
out = aug_dict(data)
```

### Expected behavior

Error should not be raised

### Environment

```shell
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

kornia==0.7.2
```
- PyTorch Version (e.g., 1.0):
- OS (e.g., Linux):
- How you installed PyTorch (`conda`, `pip`, source):
- Build command you used (if compiling from source):
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by shijianjian** [comment]
I think we should support `(B,C,H,W)` if you give `(1,X,100,100)` for both input and masks.

But this joint preprocessing is a feature that we should support @johnnv1
