### ISSUE TITLE
[Bug] Incorrect documentation for adjust_contrast

### ISSUE THREAD

**Issue by smounsav** [kornia/kornia#287]
Hi,
I think the documentation for function adjust_contrast is incorrect.
The documentation states that a contrast factor of 0 generates a black image and 1 outputs the original image. However, with the current implementation, it is not the case, the original image is obtained with factor 0 and a factor 1 outputs a white image.
I think to obtain a black image, the factor to use would be -1 but this value is not permitted in the actual implementation as it expects a positive value.

**Comment by edgarriba** [comment]
@smounsav you are right. We should probably consider rethink about this adjusting operators. Just discovered torchvision already implement that in raw tensors. We could take it as reference. https://github.com/pytorch/vision/blob/master/torchvision/transforms/functional_tensor.py

we were discussing with @dvd42 to also implement `add_weigthed` from opencv, which is similar to this blending operator in torchvision. Check this: https://github.com/kornia/kornia/issues/233

**Comment by edgarriba** [comment]
@smounsav check this: https://github.com/kornia/kornia/pull/304 and feel free to comment

**Comment by edgarriba** [comment]
fixed
