### ISSUE TITLE
[Bug] Division by 0 problem in rgb_to_hsv function

### ISSUE THREAD

**Issue by smounsav** [kornia/kornia#288]
In kornia.color.rgb_to_hsv, the computation of s is leading to nan value due to division by 0 when variable v contains 0.
`s: torch.Tensor = deltac / v  # saturation`
I don t know what is the best solution to solve this. On my local machine, I add a small eps=1e-7 as a workaround:
`s: torch.Tensor = deltac / (v + 1e-7) # saturation`

**Comment by edgarriba** [comment]
right, this is a simple fix by adding an epsilon value. Should be easy to fix, maybe with a test

**Comment by MartinPernus** [comment]
For me, the epsilon loss was too low, causing NaN values in backprop. Solved it by changing from 1e-32 (as is in the code right now) to the suggested value 1e-7 of smounsav.

**Comment by edgarriba** [comment]
@MartinPernus @smounsav I'll add epsilon as a function parameter
