### ISSUE TITLE
[Bug] Wrong implementation of adjust_hue

### ISSUE THREAD

**Issue by smounsav** [kornia/kornia#290]
I think the implementation of color.adjust_hue is wrong.
According to the documentation the factor should be between [-0.5:0.5], a factor 0 meaning no transformation. However, the code implemented doesn t leave h unchanged if hue_factor=0:
`h_out: torch.Tensor = torch.frac(h * hue_factor)`
If we take inspiration from the torchvision implementation, I think a correction could be:
` h_out: torch.Tensor = torch.clamp(h + (h * hue_factor), min=0, max=1)`

**Comment by edgarriba** [comment]
you are right and I'm pretty fine with it. Would be great though to find some resources to take as a reference and try to stick to it. Maybe @mrT23 has some opinions about this.

@smounsav could you take care of opening a PR to fix this ?

**Comment by priba** [comment]
PR #333 corrects this issue.

`h_out: torch.Tensor = torch.fmod(h + hue_factor, divisor)`

hue_factor moves the hue by a values between [-pi, pi], and fmod with the proper divisor scales it properly.
