### ISSUE TITLE
Including Steerers

### ISSUE THREAD

**Issue by georg-bn** [kornia/kornia#2913]
## 🚀 Feature
It would be simple to add support for [Steerers](https://github.com/georg-bn/rotation-steerers), since the descriptor is already implemented with DeDoDe.

The only thing that would have to be added are the steerers themselves [see here](https://github.com/georg-bn/rotation-steerers/blob/main/rotation_steerers/steerers.py), perhaps in the DeDoDe folder. And new matchers [(e.g. something like this)](https://github.com/georg-bn/rotation-steerers/blob/main/rotation_steerers/matchers/max_similarity.py), I suppose either in kornia/feature/matching.py or a new file.

I'll create a pull request if this is of interest.

**Comment by edgarriba** [comment]
sounds very interesting ! Could be great to have a tutorial too to see the potential applications. /cc @ducha-aiki

**Comment by ducha-aiki** [comment]
@georg-bn please do!
