### ISSUE TITLE
how do u set kornia?

### ISSUE THREAD

**Issue by xalteropsx** [kornia/kornia#2935]
self.set_rng_device_and_dtype(device="cuda", dtype=torch.float64)  i didnt understand this part

what is self here ? and how do u set kornia to cuda ? so whatever i run it use gpu ?

**Comment by edgarriba** [comment]
@xalteropsx can you point to codebase / version ? or how are you attempting to use?

**Comment by johnnv1** [comment]
@xalteropsx i'll give a shot in the dark here, so, an example for your side will be welcomed

I know this is a method from the augmentation container, so if you are trying to setup an augmentation or a augmentation container you can follow this:
