### ISSUE TITLE
`utils.draw_convex_polygon` is not in-place update

### ISSUE THREAD

**Issue by riaqn** [kornia/kornia#2969]
### Describe the bug

The function in the title does not in-place update the `images` argument, which is suggested by the document. Instead, one has to take the returned value to acquire the updated images.

The code to blame is at https://github.com/kornia/kornia/blob/4bd1bd172d27ae0ffb5a811b7338150b65f404dc/kornia/utils/draw.py#L354

**Comment by edgarriba** [comment]
@riaqn can you update the docs according to the functionality ?

**Comment by riaqn** [comment]
Given that all the other `draw_*` functions are in-place, I think this one should be in-place as well. I will make a PR when I have time.

**Comment by edgarriba** [comment]
thanks!
