### ISSUE TITLE
YUV Chroma limits

### ISSUE THREAD

**Issue by egidioln** [kornia/kornia#3008]
## 📚 Documentation

Hi everyone!

In the docstring of [yuv_to_rgb](https://kornia.readthedocs.io/en/latest/color.html#kornia.color.yuv_to_rgb), it is stated that 

> The image data is assumed to be in the range of (0, 1) for luma and (-0.5, 0.5) for chroma.

However, it seems that the equations in `kornia/color/yuv.py` implemented the M/PAL values (see [BT.470](https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.470-5-199802-S!!PDF-E.pdf), Table 2, items 2.5 and 2.6). The range of chroma for these values are $(-0.436, 0.436)$ and $(-0.615, 0.615)$ instead, conflicting with the documentation of `yuv_to_rgb`. For example, notice that RGB `[1.0, 0, 0]` converts to YUV `[0.299, -0.147, 0.615]` in `kornia`. These ranges are also highlighted in the [wikipedia page on YUV](https://en.wikipedia.org/wiki/Y%E2%80%B2UV#SDTV_with_BT.470). Should this entry in the documentation of `yuv_to_rgb` be fixed to specify the correct assumed range and what YUV means there? Or should the equations be modified to use another flavor of YUV, such as [BT.601](https://en.wikipedia.org/wiki/YCbCr#ITU-R_BT.601_conversion) whose values are actually $(-0.5, 0.5)$?

Cheers!

**Comment by edgarriba** [comment]
i would update properly the docs and if needed just create a separated implementation under a different name similat to [`rgb_to_yuv422`](https://github.com/kornia/kornia/blob/main/kornia/color/yuv.py#L76). Are you open to make such contribution ?

**Comment by egidioln** [comment]
> Are you open to make such contribution ?

I can surely open an PR to update the docs. Regarding the implementation of other YUV/YCbCr flavors I currently don't need it and, as there are many flavors out there, I wouldn't pick a random one and implement it right now, but I can help later if the need pops up.

**Comment by egidioln** [comment]
Hi @edgarriba, I opened #3016
