### ISSUE TITLE
[Feature Request] Motion Blur

### ISSUE THREAD

**Issue by mronta** [kornia/kornia#302]
I would like to implement Motion Blur.
At the moment I lack of a reference for it, apart its implementation in 'imgaug' lib (https://github.com/aleju/imgaug).

**Comment by mronta** [comment]
In my understanding, 'albumentations' implementation does not have direction of the Motion Blur like 'imgaug' (https://imgaug.readthedocs.io/en/latest/source/api_augmenters_blur.html#imgaug.augmenters.blur.MotionBlur). 
Which one should I follow?

**Comment by edgarriba** [comment]
the more the better. Adding the functionality to the roadmap.
