### ISSUE TITLE
AugmentationSequential explicitly moves the output to the CPU if data_keys is given

### ISSUE THREAD

**Issue by JanSellner** [kornia/kornia#3066]
### Describe the bug

With the 0.7.4 release, augmentations on the GPU are not possible anymore because the output of the input tensor is always explicitly moved to the CPU.

The problem is that `_detach_tensor_to_cpu` is called explicitly on every tensor in [augment.py](https://github.com/kornia/kornia/blob/main/kornia/augmentation/container/augment.py#L507).

### Reproduction steps
The augmented version of the input gets moved to the CPU:

```python
import torch
import kornia

input = torch.randn(1, 3, 10, 10, device="cuda")
mask = torch.randn(1, 10, 10, device="cuda")
aug_list = kornia.augmentation.AugmentationSequential(kornia.augmentation.RandomHorizontalFlip(p=1))

for a in aug_list(input, mask, data_keys=["input", "mask"]):
    print(a.dtype, a.device)
# torch.float32 cpu
# torch.float32 cuda:0
```

Without `data_keys` and only one input, the output device is as expected:
```python
for a in aug_list(input):
    print(a.dtype, a.device)
# torch.float32 cuda:0
```

### Expected behavior

I would expect the augmented version of the input tensor to reside on the GPU.

### Environment

- PyTorch Version (e.g., 1.0): 2.5.1
- OS (e.g., Linux): Ubuntu
- How you installed PyTorch (`conda`, `pip`, source): pip
- Build command you used (if compiling from source):
- Python version: 3.12
- CUDA/cuDNN version: 12.4
- GPU models and configuration: NVIDIA 4090 RTX
- Any other relevant information:

### Additional context

Reverting back to 0.7.3 fixes the problem.

**Comment by edgarriba** [comment]
> BTW, I think we may need a pre-merge action to run CUDA tests. At least to run it for one-time for each merge. It has happened many times I think that some CUDA errors after all CPU tests passed.

For that, we need someone to sponsor with access to a machine that has a cuda device.

**Comment by edgarriba** [comment]
we can try yes

**Comment by abarbadan** [comment]
One of Kornia's biggest strengths is fast GPU augmentations. This bug makes 0.7.4 unusable for many including me - are there any updates on a fix?

**Comment by shijianjian** [comment]
hey @ashnair1, can you help fix this issue?

**Comment by ashnair1** [comment]
Simplest solution would be to not detach tensors to cpu
