### ISSUE TITLE
[Bug] Potential bug in rgb_to_hsv

### ISSUE THREAD

**Issue by smounsav** [kornia/kornia#308]
Hi, I have some doubts about the implementation of rgb_to_hsv.
To avoid division by zero when dividing by deltac to calculate rc, gc and bc, 0 values are replaced by 1 by following command :
```
deltac: torch.Tensor = torch.where(
     deltac == 0, torch.ones_like(deltac), deltac)
```
What is the motivation to replace 0 by 1?
To avoid division by 0, I would rather go by adding a small epsilon to delta:
```
    rc: torch.Tensor = (maxc - r) / deltac + 1e-7
    gc: torch.Tensor = (maxc - g) / deltac + 1e-7
    bc: torch.Tensor = (maxc - b) / deltac + 1e-7
```
What do you think?

**Comment by edgarriba** [comment]
@dvd42 followed this I guess: https://gist.github.com/PolarNick239/691387158ff1c41ad73c#file-rgb_to_hsv_np-py-L36

your solution should work too. Does this really really change the performance ?

**Comment by dvd42** [comment]
Yeah I dont think this is a bug. Since the values where deltac is 0 will be replaced in the following lines anyways. You can try doing:

```
deltac: torch.Tensor = torch.where(deltac == 0, torch.full_like(deltac, 1e-7), deltac)
```
And I suspect you would get the same results.
