### ISSUE TITLE
RandomRain crashes for small batch sizes or probabilities

### ISSUE THREAD

**Issue by plamen-alcatraz** [kornia/kornia#3097]
### Describe the bug

For small batch sizes or probabilities the RandomRain crashes with:

> File "/home/plamen/anaconda3/envs/mlops2/lib/python3.9/site-packages/kornia/augmentation/random_generator/_2d/random_rain.py", line 67, in forward
>     (batch_size, int(number_of_drops_factor.max().item()), 2),
> RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

The problem is that number_of_drops_factor could be empty and then number_of_drops_factor.max() will crash.

### Reproduction steps

```bash
Use RandomRain with a small batch size, for example 2.
```

### Expected behavior

Not to crash

### Environment

```shell
kornia==0.7.2
```

**Comment by plamen-alcatraz** [comment]
Also reproduced on kornia==0.7.4

**Comment by edgarriba** [comment]
Are you open to fix this ?

**Comment by plamen-alcatraz** [comment]
I can give it a try.
