### ISSUE TITLE
rgb <-> hls conversion [bug]

### ISSUE THREAD

**Issue by Dipet** [kornia/kornia#320]
Hi!
Why are you normalize HLS to `[0, 1]`? HLS defined like `H: [0, 360]` `L: [0, 1]`, `S: [0, 1]`. This behaviour slower and absolutely inintiutive.

Also you need tests to compare results of all your transforms with OpenCV. Current implementations of this transforms get different results to OpenCV, and I did still not test other transforms.

**Comment by Dipet** [comment]
HLS to RGB wrong.
```
np.random.seed(0)
image = np.random.random([1000, 1000, 3]).astype(np.float32)
image[..., 0] *= 360

cv_img = cv.cvtColor(image, cv.COLOR_HLS2RGB)

k_img = image.copy()
k_img[..., 0] /= 360
k_img = torch.from_numpy(image.transpose([2, 0, 1]))
k_img = K.hls_to_rgb(k_img)
k_img = k_img.numpy().transpose([1, 2, 0])

print(np.abs(cv_img - k_img).max())  # 0.9972929
assert np.allclose(cv_img, k_img)
```

**Comment by ducha-aiki** [comment]
I agree with you. It should be normalized to [0, 2*pi] and documented

**Comment by priba** [comment]
I also agree. I am adding tests to compare to openCV and I will normalize the hue to [0,2*pi]. HSV should also be normalized.

Some functionalities such as AdjustHue use the previous scale and will be also modified. The hue_factor ranges in [-0.5, 0.5] like torchvision (https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.functional.adjust_hue), shall we change it to [-pi, pi]?

**Comment by priba** [comment]
Check PR #342
