### ISSUE TITLE
mode parameter is not used in warp_affine (and homography)

### ISSUE THREAD

**Issue by EmilienDupont** [kornia/kornia#326]
Hi,

Thanks for the great library!

I've been trying to use the [warp_affine](https://github.com/kornia/kornia/blob/cdd8f01f5ff6e1c7ac68b47137f0f77bd671ba4d/kornia/geometry/transform/imgwarp.py#L111) function using the `nearest` interpolation (as opposed to the default `bilinear` interpolation). However, in the function definition it looks like the `flags` parameter is not used. `warp_affine` depends on [transform_warp_impl](https://github.com/kornia/kornia/blob/cdd8f01f5ff6e1c7ac68b47137f0f77bd671ba4d/kornia/geometry/transform/imgwarp.py#L57) which doesn't have the `flags` or `mode` keyword for interpolation. `transform_warp_impl` in turn depends on `homography_warp` which does have the `mode` keyword for interpolation. Finally, it seems like, the `mode` keyword is passed to `torch.nn.functional.grid_sample` and this is where the interpolation actually happens. But it seems like the interpolation mode is "lost" when going from `warp_affine` to the eventual `grid_sample`.

Is there any plan to fix this? It can be quite confusing when reading the docs, since `warp_affine`'s behaviour does not change when changing the interpolation mode. Thank you!

**Comment by ducha-aiki** [comment]
Hi,

Thank you for the point out. We plan to fix it, but now quite busy because of CVPR deadline. Feel free to submit fixing PR in meantime ;)

**Comment by EmilienDupont** [comment]
Sounds good, thank you :smile:
