### ISSUE TITLE
[PERFORMANCE] filter2D performance issue

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#355]
Now filter2d runs multichannel data as group convolution https://github.com/kornia/kornia/blob/master/kornia/filters/filter.py#L70

However, I found that it is 2x slower, than doing reshape (B,C) -> (B*C, 1) and do single channel convolution. 

Code to reproduce:

```python
import torch
import kornia
import random
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
cudnn.benchmark = True

b,c,h,w = 16,16,800,800
device = torch.device('cuda:0')
kernel1 = kornia.filters.kernels.get_gaussian_kernel2d((11,11), (1.6,1.6))
kernel1 = kernel1.to(device).view(1,1,11,11).float()

with torch.autograd.profiler.profile(use_cuda=True) as prof:
    out = []
    for i in range(10):
        x = F.conv2d(F.pad(random.random() + torch.rand(b,c,h,w, device=device).view(b*c,1, h, w),
                   (5,5,5,5)), kernel1).view(b,c,h,w)
        out.append(x)
print (prof)

with torch.autograd.profiler.profile(use_cuda=True) as prof:
    out = []
    for i in range(10):
        x = F.conv2d(F.pad(random.random() + torch.rand(b,c,h,w, device=device),
                   (5,5,5,5)), kernel1.repeat(c,1,1,1), groups=c)
        out.append(x)
print (prof)
```

Reshape method:
```
Self CPU time total: 1.787ms
CUDA time total: 6.804s
```

Groupconv (current) method:

```
Self CPU time total: 1.940ms
CUDA time total: 13.319s
```
With kernel_size = 5:

Reshape method:
```
Self CPU time total: 1.647ms
CUDA time total: 2.701s
```

Groupconv (current) method:

```
Self CPU time total: 1.480ms
CUDA time total: 4.220s
```

With kernel_size = 3:

Reshape method:
```
Self CPU time total: 1.606ms
CUDA time total: 1.851s
```

Groupconv (current) method:

```
Self CPU time total: 1.442ms
CUDA time total: 1.889s
```

**Comment by edgarriba** [comment]
Awesome

**Comment by ducha-aiki** [comment]
```python
import torch
import kornia
import random
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
import timeit
def benchmark_group(data, device):
    b,c,h,w = data.size()
    torch.cuda.synchronize()
    x = F.conv2d(data, kernel.expand(c,-1,-1,-1), groups=c)
    torch.cuda.synchronize()
    return

def benchmark_reshape(data, device):
    b1,c1,h1,w1 = data.size()
    torch.cuda.synchronize()
    x = F.conv2d(data.view(b*c,1, h1,w1), kernel).view(b,c,h,w)
    torch.cuda.synchronize()
    return
```


Then 
```python
for ks in [3,5,7,9,11]: 
    for device in [torch.device('cpu'), torch.device('cuda:0')]: 
        data = torch.rand(b,c,h,w, device=device).float() 
        x = F.pad(data,(ks//2,ks//2,ks//2,ks//2)) 
        b1,c1,h1,w1 = x.size() 
        kernel = torch.rand(1,1,ks,ks, device=device).float() 
        #warmup 
        o = F.conv2d(x, kernel.expand(c,-1,-1,-1), groups=c) 
        o = F.conv2d(x.view(b*c,1, h1,w1), kernel).view(b,c,h,w) 
        torch.cuda.synchronize() 
        print (ks, 'group', str(device)) 
        %timeit benchmark_group(x,device) 
        torch.cuda.synchronize() 
        print (ks, 'reshape',str(device))
        %timeit benchmark_reshape(x,device)```

**Comment by ducha-aiki** [comment]
Results, 
NVIDIA DGX1, torch 1.3.1

3 group cpu
134 ms ± 581 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
3 reshape cpu
1.31 s ± 4.39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3 group cuda:0
3.16 ms ± 5.89 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
3 reshape cuda:0
20.3 ms ± 29.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5 group cpu
263 ms ± 3.91 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5 reshape cpu
1.32 s ± 5.72 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5 group cuda:0
7.34 ms ± 3.95 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
5 reshape cuda:0
36.6 ms ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
7 group cpu
481 ms ± 3.55 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7 reshape cpu
1.35 s ± 3.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7 group cuda:0
12.3 ms ± 632 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)
7 reshape cuda:0
41.8 ms ± 15.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
9 group cpu
803 ms ± 6.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
9 reshape cpu
1.48 s ± 7.49 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
9 group cuda:0
17.3 ms ± 35.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
9 reshape cuda:0
62.5 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
11 group cpu
1.19 s ± 11.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11 reshape cpu
1.65 s ± 8.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11 group cuda:0
25 ms ± 36.1 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
11 reshape cuda:0
89.8 ms ± 40.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Group is much faster

**Comment by ducha-aiki** [comment]
NVIDIA 1080, torch 1.3.0, CUDA 10.1

3 group cpu
301 ms ± 1.08 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3 reshape cpu
1.86 s ± 1.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3 group cuda:0
30.7 ms ± 68.9 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
3 reshape cuda:0
44.6 ms ± 3.17 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5 group cpu
580 ms ± 1.75 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5 reshape cpu
1.86 s ± 3.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
5 group cuda:0
79 ms ± 176 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5 reshape cuda:0
62.3 ms ± 177 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
7 group cpu
4.68 s ± 10.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7 reshape cpu
1.98 s ± 1.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
7 group cuda:0
143 ms ± 594 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
7 reshape cuda:0
88.7 ms ± 128 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
9 group cpu
7.73 s ± 49.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
9 reshape cpu
2.37 s ± 4.29 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
9 group cuda:0
210 ms ± 45.6 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
9 reshape cuda:0
122 ms ± 261 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
11 group cpu
11.4 s ± 89.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11 reshape cpu
2.92 s ± 5.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11 group cuda:0
256 ms ± 539 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
11 reshape cuda:0
165 ms ± 448 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


reshape is faster

**Comment by ducha-aiki** [comment]
Titan X, torch 1.3.1, CUDA 10.1


3 group cuda:0
57.4 ms ± 65.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
3 reshape cuda:0
91.7 ms ± 95.3 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5 group cuda:0
150 ms ± 189 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5 reshape cuda:0
275 ms ± 970 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
7 group cuda:0
274 ms ± 487 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
7 reshape cuda:0
195 ms ± 15.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
9 group cuda:0
484 ms ± 702 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
9 reshape cuda:0
298 ms ± 402 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
11 group cuda:0
616 ms ± 2.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11 reshape cuda:0
404 ms ± 405 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

**Comment by edgarriba** [comment]
@ducha-aiki can we close this ?

**Comment by ducha-aiki** [comment]
Yes.
