### ISSUE TITLE
[Bug] rgb_to_grayscale implementation issue

### ISSUE THREAD

**Issue by LeeHayun** [kornia/kornia#358]
Hi, I have question about the implementation of `kornia.color.rbg_to_grayscale`.

https://github.com/kornia/kornia/blob/04307c26a9b4dc8d37f0b1a746c197609e98514c/kornia/color/gray.py#L57-L59

Reference:
https://docs.opencv.org/4.0.1/de/d25/imgproc_color_conversions.html

According to the reference, I think the implementation should look like this:
```python
    gray: torch.Tensor = 0.299 * r + 0.587 * g + 0.114 * b
```

If not, is there a reason to use 0.110 for blue color?

**Comment by edgarriba** [comment]
@LeeHayun you are right, this is wrong. Will fix it
