### ISSUE TITLE
rgb_to_hls nan in output tensor

### ISSUE THREAD

**Issue by Dipet** [kornia/kornia#365]
Code for reproduce
```
mport numpy as np
import kornia as K
import torch

np.random.seed(0)

img = np.random.randint(0, 256, [1000, 1000, 3], np.uint8).astype(np.float32) / 255.0
img = torch.from_numpy(img.transpose(2, 0, 1))

result = K.rgb_to_hls(img)
res = torch.isnan(result).any() or not torch.isfinite(result).all()

print(res) # tensor(True)
```

**Comment by priba** [comment]
Hi @Dipet it seems this happens because of kornia versions.  In my case, installing it from git does not generate NaN: `pip install git+https://github.com/kornia/kornia`

`pip install kornia` produces exactly what you report. I guess it will be corrected in the next release (@edgarriba ?).

**Comment by Dipet** [comment]
Yes I did use old version. sorry.
