### ISSUE TITLE
[JIT] Can I pack kornia operation in model and export as onnx model?

### ISSUE THREAD

**Issue by soham24** [kornia/kornia#380]
I want to only process grayscale version of image. 
Can I pack kornia operation in model and export as onnx model?

**Comment by edgarriba** [comment]
@soham24 this will be possible once this first PR gets in: https://github.com/kornia/kornia/pull/261

To make this happen, we need to wait until the patch @suo did in pytorch/pytorch#31057 gets into a supported release, which I guess will be in pytorch 1.3.2. During the hackathon we discussed about including a `kornia.jit` module which already converts every function into a torch script module, meaning that later this can be easily exported to onnx and loaded from any frameworks that supports the traced operations.

If you are interested in this we are looking for contributors.

**Comment by dvd42** [comment]
Yes, you should be able to as long as the used operations inside the kornia modules are supported ONNX. Here is a small example:

```
>>> import kornia
>>> import cv2
>>> import torch
>>> import torch.nn as nn
>>> import onnx
>>> img = cv2.imread("examples/data/arturito.jpeg")
>>> img = kornia.image_to_tensor(img)
>>> model = nn.Sequential(kornia.color.RgbToGrayscale())
>>> torch.onnx.export(model, img, "model.onnx", verbose=True, export_params=True)
graph(%input : Float(3, 288, 512)):
  %1 : Float(1, 288, 512), %2 : Float(1, 288, 512), %3 : Float(1, 288, 512) = onnx::Split[axis=-3, split=[1, 1, 1]](%input)
  %4 : Float() = onnx::Constant[value={0.299}]()
  %5 : Float(1, 288, 512) = onnx::Mul(%1, %4)
  %6 : Float() = onnx::Constant[value={0.587}]()
  %7 : Float(1, 288, 512) = onnx::Mul(%2, %6)
  %8 : Float(1, 288, 512) = onnx::Add(%5, %7), scope: Sequential/RgbToGrayscale[0] # /home/diego/Projects/kornia/kornia/color/gray.py:60:0
  %9 : Float() = onnx::Constant[value={0.114}]()
  %10 : Float(1, 288, 512) = onnx::Mul(%3, %9)
  %11 : Float(1, 288, 512) = onnx::Add(%8, %10), scope: Sequential/RgbToGrayscale[0] # /home/diego/Projects/kornia/kornia/color/gray.py:60:0
  return (%11)

>>> onnx.checker.check_model(onnx.load("model.onnx"))

```

**Comment by soham24** [comment]
Thanks @edgarriba  and @dvd42 for reply.
This is so cool and will change everything.
I would love to contribute with my limited set of skills.

**Comment by edgarriba** [comment]
@soham24 great. In the next release we create the mentioned module so that can be easy to plug in new methods.
