### ISSUE TITLE
[ENHANCEMENT] Improve random rectangle erasing

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#387]
Improve the existing random erasing algorithm in
https://github.com/kornia/kornia/commit/85ef4c0a1e58a023dbae840b233677b37ac32fdc#diff-d354cebd44a3d59c414bcb9dc7a78f66R111

by the one proposed here: https://twitter.com/francoisfleuret/status/1208342223340875776

![image](https://user-images.githubusercontent.com/5157099/71309309-c6af4380-2406-11ea-9f86-a1d44cb05277.png)

**Comment by ducha-aiki** [comment]
https://gist.github.com/alexandre01/7d4a03f2ba21e57a676a491782933dfc -- updated version

**Comment by edgarriba** [comment]
@shijianjian can you take a look at this ?
