### ISSUE TITLE
[Feature Request] histogram computation

### ISSUE THREAD

**Issue by albertaparicio** [kornia/kornia#413]
I would like to request the implementation of histogram computation (similar to what OpenCV does) into Kornia.

**Comment by edgarriba** [comment]
adding the opencv link reference so that we can discuss the implementation
https://docs.opencv.org/4.2.0/d6/dc7/group__imgproc__hist.html#ga4b2b5fd75503ff9e6844cc4dcdaed35d

**Comment by edgarriba** [comment]
Adding as reference this thread in torchvision https://github.com/pytorch/vision/issues/598

**Comment by connorlee77** [comment]
@edgarriba @ducha-aiki 

Is this feature complete yet? I've written code for a batch histogram1d, and histogram2d via kernel density estimation.

Since its an estimation, the histogram won't be exactly correct, but it should be close. Should I open a PR to include it in Kornia?

**Comment by edgarriba** [comment]
@connorlee77 sure go ahead

**Comment by edgarriba** [comment]
@albertaparicio this feature is merged in #530. Let us know it helps with your usage.
Feel free to propose other feature requests
