### ISSUE TITLE
ScaleSpaceDetector return SIFT keypoints? 

### ISSUE THREAD

**Issue by connorlee77** [kornia/kornia#440]
What exactly does ScaleSpaceDetector return? I presume a list of SIFT keypoints? How do I find the positions of these keypoints in the image?

**Comment by ducha-aiki** [comment]
Please, see the documentation
https://kornia.readthedocs.io/en/latest/feature.html#kornia.feature.ScaleSpaceDetector

"Returns
shape [BxNx2x3]. Detected local affine frames. responses (torch.Tensor): shape [BxNx1]. Response function values for corresponding lafs:

It doesn't return list of SIFTs, it returns tensor of those keypoints, which were specified in resp_module input parameter.

**Comment by connorlee77** [comment]
Thanks for the explanation! I guess my real question is: what are the lafs? 

I'm ultimately trying to get the location of the keypoints in order to pass a patch into the siftdescriptor class.

**Comment by connorlee77** [comment]
Is there an example of using ScaleSpaceDetector with SIFTDescriptor anywhere? That may be more useful for me to understand the outputs of ScaleSpaceDetector

**Comment by connorlee77** [comment]
Never mind. I see that we can use extract_patches_simple() to retrieve said patches from laf.

**Comment by ducha-aiki** [comment]
Here are some tutorials and examples of usage:

https://github.com/kornia/kornia-examples/blob/master/local_feature_detection_example.ipynb
https://github.com/kornia/kornia-examples/blob/master/image-matching-example.ipynb

I would also recommend to use not extract_patches_simple, but extract_patches_from_pyramid. It gives much better results
