### ISSUE TITLE
[BUG] image_to_tensor() changes the image datatype to float 

### ISSUE THREAD

**Issue by lferraz** [kornia/kornia#441]
e.g. if I have a uint8 numpy image and I apply the method it returns a float tensor.
I consider these kind of changes shouldn't be done or at least they should be clearly noted in the docstring. 
Another issue with this is the speed, datatype changes are not for free, and in my case means that using image_to_tensor there are two unnecessary dtype conversions (unit8->float->uint8)

**Comment by edgarriba** [comment]
solved here https://github.com/kornia/kornia/pull/497
