### ISSUE TITLE
[Features Request] Elastic Transformation for data augmentation.

### ISSUE THREAD

**Issue by pabloppp** [kornia/kornia#444]
There seems to be an open PR for adding it to torchvision https://github.com/pytorch/vision/pull/1448 and I thought it would really good to have this as an augmentation transformation in kornea (maybe it can be already achieved combining existing kornea modules)

Not sure if possible but it would also be awesome if this could be added as a differentiable module.

**Comment by edgarriba** [comment]
@pabloppp thanks for reporting. As you said, it can definitely be implemented. Adding it to the roadmap #434

**Comment by edgarriba** [comment]
https://github.com/kornia/kornia/pull/471 has to be finished

**Comment by edgarriba** [comment]
@pabloppp @smounsav any help on this would be great

**Comment by smounsav** [comment]
Hi, I will be happy to help.
What do you need us to do exactly?






Le lundi 19 octobre 2020 à 05:37:44 UTC−4, Edgar Riba <notifications@github.com> a écrit : 







@pabloppp @smounsav any help on with would be great

**Comment by edgarriba** [comment]
@smounsav check https://github.com/kornia/kornia/pull/471 needs to be polished and implement some tests.
