### ISSUE TITLE
[Feature Request] Canny Edge Detection Algorithm

### ISSUE THREAD

**Issue by jannctu** [kornia/kornia#446]
Hi, 

do you think it is possible to implement NMS edge thinning as a CNN layer? 
here is the NMS algorithm in python as a reference. 

https://github.com/StefanPitur/Edge-detection---Canny-detector/blob/master/canny.py

**Comment by edgarriba** [comment]
@jannctu yes, I think it's doable applying 'diff' kernels over angles feature map.

**Comment by shijianjian** [comment]
Closed by #1020.
