### ISSUE TITLE
[BUG] in the homography warper example.

### ISSUE THREAD

**Issue by lferraz** [kornia/kornia#452]
in `kornia/examples/homography_regression/homography.ipynb` there is the next import:
`import torchgeometry as tgm`

I assume should be:
`import kornia`

**Comment by skmatz** [comment]
@lferraz

Can you tell me why?
`kornia` is not used in this notebook.

**Comment by edgarriba** [comment]
@lferraz probably you are looking at an old branch. I recently updated the examples in this branch for the WACV tutorial: https://github.com/kornia/kornia-examples/blob/wacv/homography.ipynb
