### ISSUE TITLE
Easy way to use Dense Sift

### ISSUE THREAD

**Issue by connorlee77** [kornia/kornia#459]
Is there a simple way to generate lafs to feed into extract_patches_from_pyramid for the purposes of dense sift? 

I was thinking about feeding a list of centers into laf_from_center_scale_ori, with each center having a couple scales and 8 orientations per scale. 

Are there any easier ways I'm not thinking of?

**Comment by ducha-aiki** [comment]
Probably not. But feel free to request DenseSIFT as separate module. It is not hard to implement and I can do it after ECCV deadline (after March 8)

**Comment by connorlee77** [comment]
For sure, thanks! I'll implement it on my own for now and create a PR so you dont have to create it from scratch. 

The current implementation is pretty slow. I'm using 8 orientations and 10 scales per center. For an 300x300 image with N centers on the grid, I have a total of 80N unique dense keypoints. The dense LAFS are pre-generated in the constructor of my DenseSift class. 

Do you expect it to be slow? Any ideas on how to make it memory-efficient?

**Comment by ducha-aiki** [comment]
No, I meant that I could implement DenseSIFT is a proper memory efficient way w/ o lafs

**Comment by edgarriba** [comment]
closing in favor of #462
