### ISSUE TITLE
crop_and_resize does not return correct results

### ISSUE THREAD

**Issue by skmatz** [kornia/kornia#461]
`kornia.geometry.crop_and_resize` example may be not correct (or the implementation may be wrong).

When running the example code, it outputs

```python
tensor([[[ 6.0000, 10.0000],
         [11.0000,  7.0000]]])
```

not

```python
tensor([[[ 6.0000,  7.0000],
         [10.0000, 11.0000]]])
```

in example.
Also, even if changing the box as pointed out #448, it outputs

```python
tensor([[[ 6.0000, 10.0000],
         [ 7.0000, 11.0000]]])
```

https://github.com/kornia/kornia/blob/cb9373bbe0b98103ad982b9a2317fe472dd2e631/kornia/geometry/transform/crop.py#L30-L45

**Comment by victoriansir** [comment]
I just checked and the results are correct if i use 

`boxes = torch.tensor([[ 
                 [1., 1.], 
                 [2., 1.], 
                 [2., 2.], 
                 [1., 2.], 
             ]])`

The coordinate of the boxes must be given with x coordinate first and y coordinate second (x,y).

**Comment by skmatz** [comment]
Exactly.
Was simply in the wrong order.
