### ISSUE TITLE
[Question] Which parameters in ScaleSpaceDetector to use to mimic OpenCV sift?

### ISSUE THREAD

**Issue by connorlee77** [kornia/kornia#467]
Which parameters in ScaleSpaceDetector should I be using if I want to mimic OpenCV sift?

**Comment by connorlee77** [comment]
Does LAFOrienter perform the orientation assignment part specificed in the OpenCV [documentation](https://docs.opencv.org/master/da/df5/tutorial_py_sift_intro.html)?

**Comment by ducha-aiki** [comment]
> Which parameters in ScaleSpaceDetector should I be using if I want to mimic OpenCV sift?

None. We currently don't have Difference-of-Gaussian detector.

>oes LAFOrienter perform the orientation assignment part specificed in the OpenCV documentation?
Yes, except that in OpenCV it may generate several orientations, which in kornia only one - to keep the batch aligned.

**Comment by connorlee77** [comment]
Does the choice in nms module particularly matter?

**Comment by edgarriba** [comment]
@ducha-aiki can you leave here or maybe do a quick note update what should be the config to replicate SIFT you used in your benchmark ?

**Comment by ducha-aiki** [comment]
Sure
