### ISSUE TITLE
[DOCS] crop_and_resize interface changed

### ISSUE THREAD

**Issue by tshadley** [kornia/kornia#470]
crop_and_resize boxes format changed,  used to be (0.1.4):

"The tensor must have the shape of Bx4x2, where each box is defined in the following order: top-left, top-right, bottom-left and bottom-right. The coordinates order must be in y, x respectively"

Now (0.2.0):

"The tensor must have the shape of Bx4x2, where each box is defined in the following (clockwise) order: top-left, top-right, bottom-right and bottom-left. The coordinates must be in the x, y order."

This change destroys backward compatibility.  Perhaps should be noted in release notes.

Thanks

**Comment by edgarriba** [comment]
@tshadley thanks for reporting. WIll add myself to the release notes.

**Comment by edgarriba** [comment]
updated
