### ISSUE TITLE
[QUESTION] Image segmentation mask transform

### ISSUE THREAD

**Issue by bluesky314** [kornia/kornia#476]
I am doing image segmentation and using random transforms. How do I get the image and mask to have the same transform done and the mask not have stuff like brightness happen to it? The tut applies then separately: https://kornia.readthedocs.io/en/latest/tutorials/data_augmentation.html#sphx-glr-tutorials-data-augmentation-py

**Comment by edgarriba** [comment]
@bluesky314 I'll generate an example for such case

**Comment by bluesky314** [comment]
OK

**Comment by shijianjian** [comment]
Hi @bluesky314,

Currently, you may use the workaround like the following:
```python
k1 = kornia.augmentation.RandomAffine([-180, 180])
k2 = kornia.augmentation.ColorJitter()
img= k2(k1(in_tensor))
mask = k1(in_tensor, k1._params)
```

**Comment by edgarriba** [comment]
@bluesky314 checkout this example I created: https://github.com/kornia/kornia-examples/blob/master/data_augmenation_segmentation.ipynb

notice that we are under refactoring to improve the API. Feel free to provide more use cases our any general feedback.

**Comment by DeepVoltaire** [comment]
Hi @edgarriba, if I am having integers as mask labels the bilinear resampling used by rotations will create in between values that are hard to map back. For example, a mask with labels 0 and 3 will have a lot of values between 0 and 3 after rotating and some on the border between the classes will round to 1 and 2. Is there a simple way to select "nearest" resampling when using apply_rotation()?

**Comment by edgarriba** [comment]
@DeepVoltaire we are merging this feature in this PR https://github.com/kornia/kornia/pull/514/files
potentially the next coming days which willl be included in the v0.2.1 release. We are pruning minor issues

**Comment by DeepVoltaire** [comment]
@edgarriba Thank you very much for this library, affine transformations as data augmentation on GPU are such a time saver! What is missing for the best results are border_modes like [cv2.warpaffine](https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html#warpaffine) has. How could this be implemented?

**Comment by edgarriba** [comment]
@DeepVoltaire thanks to point this out. We are going to refactor the warping API pretty soon in order to support 3D volumetric warpings. @lferraz can you consider this during the refactor ?

**Comment by ducha-aiki** [comment]
We are going to expose padding_mode (aka border_mode) in near future, yes

**Comment by vadimkantorov** [comment]
Is it possible to recover the "occupancy" mask after an affine transform? Right now I could imagine using some special padding value and then excluding from further processing / loss computation the pixels that belong to padding

Thanks!

**Comment by shijianjian** [comment]
> Is it possible to recover the "occupancy" mask after an affine transform? Right now I could imagine using some special padding value and then excluding from further processing / loss computation the pixels that belong to padding
> 
> 
> 
> Thanks!

Do you mean to reverse the applied transformation? If so, you may apply the inversed transformation matrices.

**Comment by vadimkantorov** [comment]
E.g. if one wants to apply equivariance loss on the rotated image (as in https://github.com/kornia/kornia-examples/blob/master/data_augmenation_segmentation.ipynb), the loss should not be computed for the padded black regions

**Comment by shijianjian** [comment]
It could be one enhancement. Well, how about the situation that the rotated image has some areas cropped out? Will it be considered as equivalent?

**Comment by erburl** [comment]
> 
> 
> Hi @edgarriba, if I am having integers as mask labels the bilinear resampling used by rotations will create in between values that are hard to map back. For example, a mask with labels 0 and 3 will have a lot of values between 0 and 3 after rotating and some on the border between the classes will round to 1 and 2.
> 
> Is there a simple way to select "nearest" resampling when using apply_rotation() or apply_affine?

Related to this, it would be great to be able to apply the same elastic/affine transformation grid but using `bilinear` and `nearest` interpolation modes on the input image and mask, respectively. This could give smoother output images while preserving the values in the mask. I was taking a look at the `AugmentationSequential` class was unable to come up with such a solution.

**Comment by shijianjian** [comment]
@erburl Agreed. I think one possible solution is to deep copy the params and update the interpolation flag in ```apply_to_masks```, ```apply_to_keypoints``` and ```apply_to_bboxes```. Then probably should delete the copied params afterwards.

https://github.com/kornia/kornia/blob/8b619aea49a6b93b703e84586ed535f58e3685e9/kornia/augmentation/container/augment.py#L115-L119

BTW, are you willing to go for a PR to do this?

**Comment by lollows** [comment]
> @erburl Agreed. I think one possible solution is to deep copy the params and update the interpolation flag in `apply_to_masks`, `apply_to_keypoints` and `apply_to_bboxes`. Then probably should delete the copied params afterwards.
> 
> https://github.com/kornia/kornia/blob/8b619aea49a6b93b703e84586ed535f58e3685e9/kornia/augmentation/container/augment.py#L115-L119
> 
> BTW, are you willing to go for a PR to do this?

@shijianjian In the albumentaion, they use a basic class([DualTransform](https://github.com/albumentations-team/albumentations/blob/422b14ee577a51591d394ac824383ced8cf25e78/albumentations/core/transforms_interface.py#L211-L240)) to do this. I think it's a good idea to augment data for low level task.

**Comment by shijianjian** [comment]
@lollows I think the API shall be proper aligned with the ```data_keys```, but I have no  idea regarding the best approach. What do you have in mind?
