### ISSUE TITLE
[Bug] jit.trace of RandomResizedCrop raises error

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#477]
Code to reproduce:

```python 
import torch
import torch.nn as nn

import kornia as K

transform = nn.Sequential(
    K.augmentation.RandomResizedCrop(size=(32,32), scale=(0.7, 1.0), ratio=(0.9, 1.10))
)


example = torch.rand(10,3,96,96)

traced_script_module = torch.jit.trace(transform, example)
traced_script_module.save("AUG_JIT.pt")
```

Error message:

> RuntimeError                              Traceback (most recent call last)
> <ipython-input-1-ad2166869785> in <module>
>      11 example = torch.rand(10,3,96,96)
>      12 
> ---> 13 traced_script_module = torch.jit.trace(transform, example)
>      14 traced_script_module.save("AUG_JIT.pt")
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/__init__.py in trace(func, example_inputs, optimize, check_trace, check_inputs, check_tolerance, _force_outplace, _module_class, _compilation_unit)
>     856         return trace_module(func, {'forward': example_inputs}, None,
>     857                             check_trace, wrap_check_inputs(check_inputs),
> --> 858                             check_tolerance, _force_outplace, _module_class)
>     859 
>     860     if (hasattr(func, '__self__') and isinstance(func.__self__, torch.nn.Module) and
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/__init__.py in trace_module(mod, inputs, optimize, check_trace, check_inputs, check_tolerance, _force_outplace, _module_class, _compilation_unit)
>     995         func = mod if method_name == "forward" else getattr(mod, method_name)
>     996         example_inputs = make_tuple(example_inputs)
> --> 997         module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
>     998         check_trace_method = module._c._get_method(method_name)
>     999 
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     537                 input = result
>     538         if torch._C._get_tracing_state():
> --> 539             result = self._slow_forward(*input, **kwargs)
>     540         else:
>     541             result = self.forward(*input, **kwargs)
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
>     523         tracing_state._traced_module_stack.append(self)
>     524         try:
> --> 525             result = self.forward(*input, **kwargs)
>     526         finally:
>     527             tracing_state.pop_scope()
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/container.py in forward(self, input)
>      90     def forward(self, input):
>      91         for module in self._modules.values():
> ---> 92             input = module(input)
>      93         return input
>      94 
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
>     537                 input = result
>     538         if torch._C._get_tracing_state():
> --> 539             result = self._slow_forward(*input, **kwargs)
>     540         else:
>     541             result = self.forward(*input, **kwargs)
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/nn/modules/module.py in _slow_forward(self, *input, **kwargs)
>     523         tracing_state._traced_module_stack.append(self)
>     524         try:
> --> 525             result = self.forward(*input, **kwargs)
>     526         finally:
>     527             tracing_state.pop_scope()
> 
> ~/dev/fresh-kornia/kornia/augmentation/augmentation.py in forward(self, input, params)
>     549                 batch_shape = input.shape
>     550             params = RandomResizedCrop.get_params(
> --> 551                 batch_size, (batch_shape[-2], batch_shape[-1]), self.size, self.scale, self.ratio)
>     552         return super().forward(input, params)
> 
> ~/dev/fresh-kornia/kornia/augmentation/augmentation.py in get_params(batch_size, input_size, size, scale, ratio)
>     539         # TODO: scale and aspect ratio were fixed for one batch for now. Need to be separated.
>     540         return pg._random_crop_gen(batch_size, input_size,
> --> 541                                    (int(target_size[0].data.item()), int(target_size[1].data.item())), resize_to=size)
>     542 
>     543     def forward(self, input: UnionType, params: Optional[Dict[str, torch.Tensor]] = None) -> UnionType:  # type: ignore
> 
> ~/dev/fresh-kornia/kornia/augmentation/param_gen.py in _random_crop_gen(batch_size, input_size, size, resize_to)
>     317                          % (str(input_size), str(size)))
>     318 
> --> 319     x_start = Uniform(0, x_diff + 1).rsample((batch_size,)).long()
>     320     y_start = Uniform(0, y_diff + 1).rsample((batch_size,)).long()
>     321 
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/distributions/uniform.py in rsample(self, sample_shape)
>      65     def rsample(self, sample_shape=torch.Size()):
>      66         shape = self._extended_shape(sample_shape)
> ---> 67         rand = torch.rand(shape, dtype=self.low.dtype, device=self.low.device)
>      68         return self.low + rand * (self.high - self.low)
>      69 
> 
> RuntimeError: _th_uniform_ not supported on CPUType for Long
>

**Comment by edgarriba** [comment]
have you tried with `torch.script`?

**Comment by ducha-aiki** [comment]
Yes. It gives another error

> --------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-12-15fd0bae5e2e> in <module>
>      11 example = torch.rand(10,3,96,96)
>      12 
> ---> 13 traced_script_module = torch.jit.script(transform, example)
>      14 traced_script_module.save("AUG_JIT.pt")
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/__init__.py in script(obj, optimize, _frames_up, _rcb)
>    1201 
>    1202     if isinstance(obj, torch.nn.Module):
> -> 1203         return torch.jit.torch.jit._recursive.recursive_script(obj)
>    1204 
>    1205     qualified_name = _qualified_name(obj)
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/_recursive.py in recursive_script(mod, exclude_methods)
>     114     if isinstance(mod, (torch.nn.ModuleList, torch.nn.Sequential, torch.nn.ModuleDict)):
>     115         # Create constant versions for the iterable modules
> --> 116         return create_constant_iterable_module(mod)
>     117 
>     118     if not hasattr(mod, '_parameters'):
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/_recursive.py in create_constant_iterable_module(module)
>     231             modules[key] = create_constant_iterable_module(submodule)
>     232         else:
> --> 233             modules[key] = recursive_script(submodule)
>     234 
>     235     if isinstance(module, Sequential):
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/_recursive.py in recursive_script(mod, exclude_methods)
>     170 
>     171     filtered_methods = filter(ignore_overloaded, methods)
> --> 172     stubs = list(map(make_stub, filtered_methods))
>     173     return copy_to_script_module(mod, overload_stubs + stubs)
>     174 
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/_recursive.py in make_stub(method)
>     167     def make_stub(method):
>     168         func = get_function_from_type(type(mod), method)
> --> 169         return torch.jit.script_method(func, _jit_internal.createResolutionCallbackFromClosure(func))
>     170 
>     171     filtered_methods = filter(ignore_overloaded, methods)
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/__init__.py in script_method(fn, _rcb)
>    1278     if _rcb is None:
>    1279         _rcb = _jit_internal.createResolutionCallback(frames_up=2)
> -> 1280     ast = get_jit_def(fn, self_name="ScriptModule")
>    1281     return ScriptMethodStub(_rcb, ast, fn)
>    1282 
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/frontend.py in get_jit_def(fn, self_name)
>     167     type_line = torch.jit.annotations.get_type_line(source)
>     168     ctx = SourceContext(source, filename, file_lineno, leading_whitespace_len, _uses_true_division(fn))
> --> 169     return build_def(ctx, py_ast.body[0], type_line, self_name)
>     170 
>     171 
> 
> ~/storage/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/jit/frontend.py in build_def(ctx, py_def, type_line, self_name)
>     203     is_method = self_name is not None
>     204     if type_line is not None:
> --> 205         type_comment_decl = torch._C.parse_type_comment(type_line)
>     206         decl = torch._C.merge_type_from_type_comment(decl, type_comment_decl, is_method)
>     207     return Def(Ident(r, py_def.name),
> 
> RuntimeError: expected type comment but found 'def' here:
> def forward(self, input: UnionType, params: Optional[Dict[str, torch.Tensor]] = None) -> UnionType:  # type: ignore
> ~~~ <--- HERE
>

**Comment by shijianjian** [comment]
Union type is currently unsupported in torchscript.

Issue: https://github.com/pytorch/pytorch/issues/41412

Partial workaround: https://github.com/kornia/kornia/pull/684#pullrequestreview-492876119. After tested, this workaround worked for input Union type but not the return Union type.

**Comment by edgarriba** [comment]
continue in https://github.com/kornia/kornia/issues/941
