### ISSUE TITLE
Blury on rotated image.

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#485]
Here is a comparison between PIL rotation and kornia rotation. It is pretty clear that the image was blurred.

```python
import torch

import kornia.augmentation.functional as F
from torchvision.transforms import functional as tvF
from torchvision.transforms import transforms

import matplotlib.pyplot as plt
import numpy as np

to_tensor = transforms.ToTensor()
to_pil = transforms.ToPILImage()

def tensor_pre_transform_wrapper(input: torch.Tensor):
    """ A wrapper that tried to reproduce the actual output from:
        - transforms.ToPILImage()
        - transforms.ToTensor()
        For each image, simply (img * 255).int() // 255
    """
    return (input * 255).int().float() / 255

in_tensor = torch.rand((3, 23, 44))
in_pil = to_pil(in_tensor)
degrees = 10
out_tensor = F._apply_rotation(
    tensor_pre_transform_wrapper(in_tensor), {'degrees': torch.tensor(degrees)}, False)
out_pil = tvF.rotate(in_pil, angle=degrees)
```

```python
plt.imshow(np.moveaxis(out_tensor.numpy(), 0, -1))
plt.imshow(np.array(out_pil))
```
<img width="379" alt="Screenshot 2020-03-21 at 12 57 59 AM" src="https://user-images.githubusercontent.com/15955486/77187300-353b9480-6b0f-11ea-9d3a-32a04952f77a.png">

**Comment by ducha-aiki** [comment]
I think that  pil in your example use nearest neighbour Iiterpolation and our one bilinear.

**Comment by ducha-aiki** [comment]
here is with hardcoded 
```
python3
def warp_affine(src: torch.Tensor, M: torch.Tensor,
                dsize: Tuple[int, int], flags: str = 'nearest',
                padding_mode: str = 'zeros') -> torch.Tensor:
```

But your example shows that we should expose interpolation method, which is now not accessible via augmentation interface.  


![image](https://user-images.githubusercontent.com/4803565/77194117-a2373600-6adf-11ea-9b1e-f553ad462bf7.png)

**Comment by edgarriba** [comment]
Let's add that flag

**Comment by shijianjian** [comment]
Resolved in #514 and #486

**Comment by doube1008** [comment]
ModuleNotFoundError: No module named 'kornia.augmentation.functional'  
 
hello ,how can i fix this problem  i had install kornia

**Comment by edgarriba** [comment]
@doube1008 to rotate image use [`kornia.geometry.transform.rotate`](https://kornia.readthedocs.io/en/latest/geometry.transform.html?highlight=rotate#kornia.geometry.transform.rotate)
