### ISSUE TITLE
Expose align_corners and interpolation_flag to set of functions 

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#486]
Right now we can specify interpolation mode in warp_affine and warp_perspective,
but not in the augmentation https://github.com/kornia/kornia/blob/master/kornia/augmentation/functional.py  and not in the https://github.com/kornia/kornia/blob/master/kornia/geometry/transform/affwarp.py  (where all stuff like rotate etc is in)

**Comment by ducha-aiki** [comment]
Related issues: https://github.com/kornia/kornia/issues/388  https://github.com/kornia/kornia/issues/485

**Comment by edgarriba** [comment]
@shijianjian I agree that has to be done, but not quite sure about the need of having custom Resample type when this can be achieved by primitive type string. Two reasons, adding this kind of code dependencies can be a pain if someone else wants to take and migrate this part of the code; follow pytorch convention using strings for enum like parameters.

**Comment by ducha-aiki** [comment]
Done in #546
