### ISSUE TITLE
[Feat] Move all the image warping functionality implementation into single module 

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia#487]
Now we have:

affine transforms + image pyramid in https://github.com/kornia/kornia/tree/master/kornia/geometry/transform
and homography warping in the https://github.com/kornia/kornia/tree/master/kornia/geometry/warp 

It confuses me all the time %)

**Comment by edgarriba** [comment]
Agree. What do you suggest?

**Comment by ducha-aiki** [comment]
geometry.warp for transforming image and geometry.transform for coordinates and points/cameras/matrices?

**Comment by edgarriba** [comment]
@ducha-aiki we might end up removing `kornia.warp` from top level API and split `HomographyWarper` to `kornia.geometry.homography` and `DepthWarper` to `kornia.geoemtry.depth`. What do you think ?

**Comment by ducha-aiki** [comment]
@edgarriba sounds good if we would not have any other kind of warping

**Comment by edgarriba** [comment]
the warping happens only with affine and homography 2d/3d which I think that can be all placed in `kornia.geometry.transform` as high level interface, and then the depth warper which this ones makes sense to me to be included in `kornia.geometry.depth`
