### ISSUE TITLE
Inconsistent of adjust_contrast and adjust_brightness with PIL lib

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#488]
The ```adjust_contrst``` implementation in Kornia is essentially the ```adjust_brightness``` in Torchvision.

In order to reproduce the results from Torchvision, I think we might need to rename the ```adjust_contrast``` to ```adjust_brightness```, and rewrite the ```adjust_contrast```. Our current implementation of ```adjust_contrast``` is not adjusting contrast at all.

To reproduce:
```python
from PIL import Image
import requests
from io import BytesIO
from torch import allclose
from kornia.color.adjust import (
    adjust_brightness, adjust_contrast, adjust_saturation, adjust_hue)

response = requests.get("https://tinypng.com/images/social/website.jpg")
img = Image.open(BytesIO(response.content))

import torch

import kornia.augmentation.functional as F
from torchvision.transforms import functional as tvF
from torchvision.transforms import transforms

import matplotlib.pyplot as plt
import numpy as np

to_tensor = transforms.ToTensor()
to_pil = transforms.ToPILImage()

def tensor_pre_transform_wrapper(input: torch.Tensor):
    """ A wrapper that tried to reproduce the actual output from:
        - transforms.ToPILImage()
        - transforms.ToTensor()
        For each image, simply (img * 255).int() // 255
    """
    return (input * 255).int().float() / 255

in_tensor = to_tensor(img)
in_pil = img
# factor = 0.5
out_tensor = adjust_contrast(tensor_pre_transform_wrapper(in_tensor), torch.tensor(2))
out_pil = tvF.adjust_brightness(in_pil, 2)

allclose(out_tensor, to_tensor(out_pil))
```

<img width="654" alt="Screenshot 2020-03-21 at 10 36 25 AM" src="https://user-images.githubusercontent.com/15955486/77217759-db16ef80-6b5f-11ea-93e8-7b1fa41b7e66.png">

**Comment by edgarriba** [comment]
@shijianjian good finding; I remember that there was already a discussion about it since different libraries handle contrast/brightness in a different way. I''m okay for renaming to match PIL/torchvision in case it makes sense from theory point of view (which I thing was the reason @priba  took this decision). Let's double check it.

**Comment by priba** [comment]
Hi,

I reported it in https://github.com/kornia/kornia/issues/145#issuecomment-517918935. At the end I decided to follow it opencv-like, but I do not have any objection on changing it to follow PIL/torchvision library.

Now it is defined as, g(x)=αf(x)+β where the parameters α>0 and β are the contrast and brightness respectively.

**Comment by shijianjian** [comment]
Brilliant. I think we are now considering to converge to the torchvision. Do you mind to have a PR for a PIL version of adjust_contrast?

**Comment by edgarriba** [comment]
@shijianjian I think that we more or less agreed that the better would be to update docs (probably in the augmentation API section?) and explain reproducibility in this case with torchvision/PIL. Could you do that ?

**Comment by shijianjian** [comment]
Yes. I will finish the tests for spatial augmentation in this weekend and update the docs accordingly.

**Comment by shijianjian** [comment]
Closed since we are going to keep those functions in OpenCV math than PIL.
