### ISSUE TITLE
Motion blur doesn't take tuple range for params angle and direction

### ISSUE THREAD

**Issue by vishal-wiai** [kornia/kornia#494]
It would be useful to have `MotionBlur` taking range of values (tuple) for parameters angle and direction when the object is initialised. Every time it is called, it samples a random value from the range to perform the filtering.

**Comment by edgarriba** [comment]
@vishal-wiai thanks for asking for this request. We can definitely add this feature to the `kornia.augmentation` API.

I suggest something like /cc @shijianjian 
```python

# float: (-value, value)
# Tuple[float, float]: (-value, value)
# torch.Tensor: torch.tensor([-value, value]) -> we might want this to be optimized
UnionType = Union[float, Tuple[float, float], torch.Tensor]

class RandomMotionBlur(nn.Module):
    def __init__(angle: UnionType, direction: UnionType):
        self._angle = angle
        self._direction = direction

    def foward(self, input):
       # generate params
       params = get_params(self._angle, self._direction)
       return kornia.filters.motion_blur(**params)
```

**Comment by shijianjian** [comment]
@vishal-wiai  It looks like not pretty hard to implement. Do you have any resource material or standard implementation for this? 

OpenCV has a Motion Deblur implementation but not Motion Blur. From elsewhere, I have seen different implementations:
1. Horizontal, Vertical Motion Blur: [here](https://www.geeksforgeeks.org/opencv-motion-blur-in-python/)
2. Diagnal Motion Blur: [here](https://stackoverflow.com/questions/1602988/convolution-matrix-for-diagonal-motion-blur)
3. Zoom motion blur: [here](https://docs.gimp.org/2.10/en/gimp-filter-motion-blur-zoom.html) No math found for this.

It seems like different kernel sizes are influencing the outcome as well. What parameters should be given to users to control? Or should they pass a conv kernel directly?

**Comment by edgarriba** [comment]
@shijianjian I think the idea would provide the high level interface to known filters to apply motion blur using `kornia.filter2d`. Motion deblurring is an open area of research mostly covered now by learned filters and some optical flow. Probably the 3 types you mention are fine by now. I will add this feature request in the roadmap.

@vishal-wiai feel free to send a PR.

**Comment by edgarriba** [comment]
solved https://github.com/kornia/kornia/pull/482
