### ISSUE TITLE
[Bug] tiny bug on _kl_div_2d causes runtime error

### ISSUE THREAD

**Issue by Eizenborg** [kornia/kornia#499]
Hi all, 
Not sure why this happens, but when using js_div_loss_2d (which is awesome, thanks!) I get this Runtime Error:
`
line 12, in _kl_div_2d
    q.view(batch * chans, height * width).log(),
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
`

which is solved by changing 
`q.view(batch * chans, height * width).log(),
        p.view(batch * chans, height * width),`

to 
`q.reshape(batch * chans, height * width).log(),
        p.reshape(batch * chans, height * width),`

on divergence.py, _kl_div_2d, line 12 and 13

**Comment by edgarriba** [comment]
@Eizenborg is it happening calling `.contiguous()` before kornia ?

**Comment by edgarriba** [comment]
@anibali can you check this ?

**Comment by anibali** [comment]
@edgarriba I just wrote a quick test and it does appear that `js_div_loss_2d` fails on non-contiguous inputs. What's your policy on this? Are users expected to make the inputs contiguous themselves when required?

```python
    @pytest.mark.parametrize('input,target,expected', [
        (torch.full((1, 1, 2, 4), 0.125), torch.full((1, 1, 2, 4), 0.125), 0.0),
        (torch.full((1, 7, 2, 4), 0.125), torch.full((1, 7, 2, 4), 0.125), 0.0),
        (torch.full((1, 7, 2, 4), 0.125), torch.zeros((1, 7, 2, 4)), 0.346574),
        (torch.zeros((1, 7, 2, 4)), torch.full((1, 7, 2, 4), 0.125), 0.346574),
    ])
    def test_noncontiguous_js(self, device, input, target, expected):
        input = input.to(device).view(input.shape[::-1]).T
        target = target.to(device).view(target.shape[::-1]).T
        # Uncomment the next two lines to make the test pass:
        # input = input.contiguous()
        # target = target.contiguous()
        actual = kornia.losses.js_div_loss_2d(input, target).item()
        assert_allclose(actual, expected)
```
