### ISSUE TITLE
How do I get L1 distance of two matrix using kornia?  

### ISSUE THREAD

**Issue by zccyman** [kornia/kornia#502]
for example, matrix1 shape: [12, 27], matrix2 shape: [2048, 27], the L1 distance shape: [12, 2048].

**Comment by edgarriba** [comment]
@zccyman this is a general Pytorch related question. I would suggest you use their forums next time
https://discuss.pytorch.org/

However, I believe that the response of your question can be done like this
```python
import torch

a = torch.rand(12, 27).view(12, 27, 1)
b = torch.rand(2048, 27).T.view(1, 27, 2048)
assert (a - b).abs().sum(1).shape == (12, 20148)
```

**Comment by zccyman** [comment]
@edgarriba thanks!
