### ISSUE TITLE
[QUESTION][geometry] Is there a differentiable function for inverse projective transformation?

### ISSUE THREAD

**Issue by SeokjuLee** [kornia/kornia#505]
Thanks for releasing such a powerful library for 3D vision.
I am interested in estimating depth by differentiable rendering.
If a dense correspondence map (F_12) and relative camera pose (T_12) between two frames (I_1, I_2) are given, can I inversely compute a relative reference depth in a differentiable way?
Could you recommend some scripts to achieve this?

**Comment by edgarriba** [comment]
hi @SeokjuLee. You might want to take a look at this example since I believe it does what you are asking for: https://github.com/kornia/kornia-examples/blob/master/depth_estimation.ipynb
