### ISSUE TITLE
RandomHorizontalFlip unexpected squeeze

### ISSUE THREAD

**Issue by shamangary** [kornia/kornia#519]
input:(B=1,C,H,W)
RandomHorizontalFlip
output:(C,H,W)

I've tried RandomGrayscale,ColorJitter,RandomCrop,RandomAffine, and no one has the above issue. I believe this is a bug. However, I tracked the code and it seems non-trivial to me how to fix the bug. Please check this one.

Also please check the RandomCrop pull request I made.

**Comment by edgarriba** [comment]
Hi @shamangary , thanks for the contributions :)
I can fix this, but be aware that there a refactor going on in here https://github.com/kornia/kornia/pull/514

We are doing a release next week to clean up stuff and align results with torchvision API. Please let's us any other things to consider.

**Comment by edgarriba** [comment]
Check this too: https://github.com/kornia/kornia/issues/460

**Comment by shijianjian** [comment]
Hi @shamangary,

Thanks for reporting this. It is from our legacy coding issues. Now it has been fixed in [here](https://github.com/kornia/kornia/pull/514/commits/efdde5a2d32968367210a52cae4486ac25b66f48). Will be merged when other stuff is ready.

Also, thanks for your PR.

Jian

**Comment by shamangary** [comment]
Thank you both.
