### ISSUE TITLE
[BUG] Raise Exception when Int Tensor

### ISSUE THREAD

**Issue by Kshitij09** [kornia/kornia#523]
I was trying to use `ColorJitter` augmentation and mistakenly passing `torch.uint8` Tensor as input. This didn't raise any warning/error but instead crashed the session abruptly. I realized the cause after 2-3 attempts. So assuming that majority of augmentations work on Float types, it would be great to introduce a type-check at the beginning of forward pass to avoid unnecessary crashes.

**Comment by edgarriba** [comment]
@Kshitij09 thanks for reporting this bug. We should start normalizing type checks to avoid this problems. I add this as a TODO for next releases. Any contribution is welcomed.

**Comment by Kshitij09** [comment]
I'd love to contribute, but need your guidance on the same. Might use this issue for asking relavent doubts

**Comment by edgarriba** [comment]
@Kshitij09 @shijianjian this fixed ?

**Comment by Kshitij09** [comment]
Sorry but I wasn't working on this. Also, I just skimmed through the commit that was referring to this issue and thought it'll be fixed by that. So I'm not sure about the progress.

**Comment by shijianjian** [comment]
Yes. I have added a type check. ```_validate_input_dtype(input, accepted_dtypes=[torch.float16, torch.float32, torch.float64])```. Only float numbers are accepted now.
