### ISSUE TITLE
[QUESTION] How can we use differential sift descriptors to prevent Adversarial Attacks?

### ISSUE THREAD

**Issue by Udit1999** [kornia/kornia#532]
In a [live stream](https://www.youtube.com/watch?v=zltoYKu4ct0) done by Edgar Riba, he presented this. So, my question is, how can we use differential sift descriptors to modify images so that SIFT algorithm or any other feature matching algorithm will work better..?
![image](https://user-images.githubusercontent.com/42462392/79893223-60244b80-8421-11ea-902d-3c013d0e920b.png)

**Comment by edgarriba** [comment]
@Udit1999 thanks for your interested in this. Please, check this example to accomplish this https://github.com/kornia/kornia-examples/blob/master/local-feature-adversarial-attack.ipynb
