### ISSUE TITLE
[Feature Request] AutoAugment transforms

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#549]
Recent feature request in https://github.com/kornia/kornia/issues/434#issuecomment-622026915 to provide transforms to reproduce AutoAugment paper.

Lnk to the paper: https://arxiv.org/pdf/1805.09501.pdf
link to tf autoaugment: https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/autoaugment.py
link to albumentation functionals: https://github.com/albumentations-team/albumentations/blob/master/albumentations/augmentations/functional.py

Needed transforms for AutoAugment:
- [ ] Solarize
- [ ] Equalize
- [ ] Posterize
- [ ] Sharpness

**Comment by shijianjian** [comment]
Added in #571
