### ISSUE TITLE
3D Data Augmentation APIs

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#585]
## 🚀 Feature
I am going to give some basic 3D data augmentation methods recently. 

The first thing is shall we rename all the current APIs into 2D?
```python
import kornia.augmentation as K
aug_2d  = K.RandomHorizontalFlip()
aug_3d = K.RandomHorizontalFlip3D()
```
or we shall name it as:
```python
import kornia.augmentation as K
aug_2d  = K.RandomHorizontalFlip2D()
aug_3d = K.RandomHorizontalFlip3D()
```

Also, the functionalities like ```kornia.geometry.VFlip``` accepts only BCHW and I do not think it is appropriate to make it accepts BCDHW. Thus, It seems to be redundant but should we have a 3D version like ```kornia.geometry.VFlip3D``` and  ```kornia.geometry.VFlip2D```. Or should we have another ```kornia_3d``` repo?

**Comment by edgarriba** [comment]
@shijianjian in the case of flip you might end up calling `torch.flip` where you specify de flipping axis and I don't think there's a problem for keeping same signature.
`K.VerticalHorizontalFlip() -> x.flip(-1)`
`K.RandomHorizontalFlip() -> x.flip(-2)`
`K.RandomDepthFlip() -> x.flip(-3)`

this particular one should work either for `BCHW` `BTCHW` `BCDHW`

**Comment by edgarriba** [comment]
besides, will push warp_projective during the next couple of days so that you can use it to double check that the returned 3d transforms are consistent to go forth and back transformations.

**Comment by shijianjian** [comment]
It is not only about the transform itself but we also included a shape standardization in the beginning. In 2D cases, all HW, CHW, and BCHW will be reshaped into BCHW. Then go for the corresponding transformation. While in 3D, we gonna reshape DHW, CDHW, and BCDHW into BCDHW. Thus, we cannot mix them up since the 2D transformation outputs BCHW and 3D transformation shall output BCDHW.

For the naming, I think there is currently no standardized name for the depth axis, I think we can use either: ```RandomLongitudinalFlip``` or ```RandomDepthicalFlip```. (I personally like `depthical` though it is not a proper English word~)

We will have three more files:
- ```kornia.augmentation.functional3D```
- ```kornia.augmentation.augmentation3D```
- ```kornia.augmentation.random_generator3D```: I think most functions can be imported from the 2D one. This file would contain only 3D-specific transforms.

For the included transformations, I think we can have:
- [ ] RandomHorizontalFlip3D
- [ ] RandomVerticalFlip3D
- [ ] RandomDepthicalFlip3D / RandomLongitudinalFlip3D
- [ ] RandomAffine3D
- [ ] RandomRotate3D
- [ ] RandomElasticTransform3D
- [ ] RandomMotionBlur3D

Also, there are some implementations here:
- [TorchIO](https://github.com/fepegar/torchio/tree/master/torchio/transforms/augmentation)
    - torch backended
    - still maintaining
- [MedicalTorch](https://github.com/perone/medicaltorch/blob/master/medicaltorch/transforms.py)
   - skimage backended
   - not actively maintained

**Comment by edgarriba** [comment]
I like this proposal. Minor naming thing - `RandomDepthFlip3D` should be simple enough

**Comment by shijianjian** [comment]
#592

**Comment by edgarriba** [comment]
already introduced in v0.4.x
