### ISSUE TITLE
Resize dataset

### ISSUE THREAD

**Issue by develooper1994** [kornia/kornia#589]
### Please note that this issue tracker is not a help form and this issue will be closed.
I keep taking error that "RuntimeError: "upsample_bilinear2d" not implemented for 'Byte'" 
and that "NotImplementedError: Got 3D input, but bilinear mode needs 4D input". 
I can't solve what is it and how to make my dataset class. Can any one help me?

class ImageDataset_superresolution(Dataset):
    def __init__(self, root=None, hr_shape=None, interpolation='bilinear'):
        hr_height, hr_width = hr_shape
        # Transforms for low resolution images and high resolution images
        self.lr_transform = kornia.nn.Sequential(
            kornia.geometry.Resize(size=(hr_height // 4, hr_height // 4), interpolation=interpolation),
            kornia.color.Normalize(torch.from_numpy(mean), torch.from_numpy(std)),
        )
        self.hr_transform = kornia.nn.Sequential(
            kornia.geometry.Resize(size=(hr_height, hr_height), interpolation=interpolation),
            kornia.color.Normalize(torch.from_numpy(mean), torch.from_numpy(std)),
        )
        if isinstance(root, str):
            self.files = sorted(glob.glob(root + "/*.*"))
        else:
            self.files = root
    def __getitem__(self, index):
        if isinstance(self.files[index], str):
            # img = Image.open(self.files[index % len(self.files)])
            img_bgr = cv2.imread(self.files[index % len(self.files)])
            img = kornia.image_to_tensor(img_bgr).unsqueeze(0)
        else:
            img = self.files
        img_lr = self.lr_transform(img)
        img_hr = self.hr_transform(img)
        return {"lr": img_lr, "hr": img_hr}
    def __len__(self):
        return len(self.files)

We have a set of [listed resources available on the Wiki](https://github.com/kornia/kornia/wiki). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/c/vision/kornia)

**Comment by edgarriba** [comment]
@develooper1994 you need to cast to any floating point precision. Pytorch bilinear sample doesn't support uint8 type =s yet
