### ISSUE TITLE
Homogenize interpolation Attribute across Augmentations

### ISSUE THREAD

**Issue by ORippler** [kornia/kornia#613]
## 🚀 Feature

Currently, there exist two attributes amongst augmentations that are both responsible for the same thing, denoting the interpolation type that whould be applied:

1. `interpolation`, used by e.g. [RandomRotation](https://github.com/kornia/kornia/blob/master/kornia/augmentation/augmentation.py#L541)
2. `resample` used by e.g. [RandomAffine](https://github.com/kornia/kornia/blob/master/kornia/augmentation/augmentation.py#L433)

This nomenclature is propagated and resolved imo only at the lower internal levels

## Motivation

When orchestrating Augmentations for use in segmentation tasks, it is cumbersome to watch two attributes/keys inside the Augmentations and the parameter dicts returned by `AugmentationBase.generate_parameters` (we need to interpolate with NN for segmentations and can choose otherwise for images).

## Pitch

Only use one key, but this one consistently, to denote the interpolation characteristic of an Augmentation (I would vote for the `interpolation` key, which more closely represents the underlying functionality imo)

**Comment by edgarriba** [comment]
@ORippler you are right. This might be a bit confusing as user. I'd vote for `interpolation` since it's what in the end grid_sample takes in the signature. @shijianjian what do you think ?

We are about to release 0.4, so I guess this request can be done by next 0.5 release.

**Comment by shijianjian** [comment]
TorchVision used ```resample``` for ```RandomAffine``` and ```RandomRotation``` while they used ```interpolation``` for others like ```RandomPerspective```, ```RandomResize```, etc.

If we are still aiming at inheriting TorchVision APIs, I think we shall rename them to ```resample```. If not, I am okay with both names.

**Comment by shijianjian** [comment]
Fixed in #633. We gonna move to ```resample```.
