### ISSUE TITLE
[Feat] RandomAffine scale width or height only

### ISSUE THREAD

**Issue by LSOFT123** [kornia/kornia#615]
Hi,

Kornia is really great, one question, is it possible to scale on one dimension only (width or height) with RandomAffine?
Aspect ratio not kept. It looks not available in options, what is the best way to achieve it?

Thanks.

**Comment by edgarriba** [comment]
@LSOFT123 the feature you mention indeed is not available in `kornia.augmentation`, however, the proper way to achieve that is using the following [`kornia.get_affine_matrix2d`](https://github.com/kornia/kornia/blob/master/kornia/geometry/transform/imgwarp.py#L459), which btw are missing in the docs.

**Comment by shijianjian** [comment]
Closed by #646
