### ISSUE TITLE
[Bug] Solarize transform breaks with cuda input tensors

### ISSUE THREAD

**Issue by mshalvagal** [kornia/kornia#622]
## 🐛 Bug

Solarize doesn't seem to perform a check for being on the same device as the input tensor, and always keeps the addition and threshold parameters on the cpu.

## To Reproduce

```python
import torch
from kornia import augmentation as augs
augmentor = augs.RandomSolarize(0.5,0.1)
x = torch.randn([64, 3, 32, 32]).to('cuda:0')
augmentor(x)
```

## Expected behavior

Error message (last call only):

```
File "<venv path>/lib/python3.6/site-packages/kornia/enhance/adjust.py", line 300, in solarize
    input = input + additions
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

## Environment

PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.5 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Quadro RTX 5000
Nvidia driver version: 440.100
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect

**Comment by edgarriba** [comment]
@mshalvagal thanks for the report. My guess is that this
https://github.com/kornia/kornia/blob/master/kornia/enhance/adjust.py#L281
https://github.com/kornia/kornia/blob/master/kornia/enhance/adjust.py#L289

must be properly initialized with device and dtype from the input tensor:
`additions = torch.tensor(additions, device=input.device, dtype=input.dtype)`

feel free to open a PR with the fix. /cc @shijianjian can you double check this ?

**Comment by mshalvagal** [comment]
Thanks!

I made a pull request. Please take a look if it's good. I manually tested it, and it works now
