### ISSUE TITLE
[Docs] Allow faster overview of available classes and functions

### ISSUE THREAD

**Issue by lukasfolle** [kornia/kornia#634]
## 📚 Documentation

To be able to get a quick overview of the available classes and functions for the kornia packages I´d suggest adding a list of all classes and functions to the navigation bar on the left side of the documentation.

<img width="1046" alt="Bildschirmfoto 2020-08-17 um 15 21 00" src="https://user-images.githubusercontent.com/26490449/90400907-825f6a80-e09d-11ea-965f-bacc59a7595f.png">

Maybe something similar to the way pytorch handels this:
<img width="201" alt="Bildschirmfoto 2020-08-17 um 15 25 45" src="https://user-images.githubusercontent.com/26490449/90401272-00bc0c80-e09e-11ea-95fb-400ed834d88b.png">

**Comment by edgarriba** [comment]
Agree, let's draft a list for subgroups here

**Comment by lukasfolle** [comment]
How about creating a list of the available classes in the Module section and a list of the functions in the Functional section automatically?

**Comment by edgarriba** [comment]
@lukasfolle this is related I guess https://github.com/kornia/kornia/issues/520

**Comment by lukasfolle** [comment]
I guess I would suggest using the list from [the documentation outline](https://github.com/kornia/kornia/blob/master/docs/source/augmentation.rst).
It should be possible to get all classes and functions from the site scanning for just `.. autoclass::` and `.. automodule::` right?

**Comment by edgarriba** [comment]
@lukasfolle didn't know about this property. Could you give it a shot and share a screenshot? /cc @shijianjian

**Comment by lukasfolle** [comment]
To make those show up in the doc we would need to change [the index file](https://github.com/kornia/kornia/blob/master/docs/source/index.rst), right?

**Comment by edgarriba** [comment]
@lukasfolle yes, and all the subsequent *rst files

**Comment by lukasfolle** [comment]
You are right. I imagined it like this:
![Bildschirmfoto 2020-09-01 um 11 04 48](https://user-images.githubusercontent.com/26490449/91830490-22db9000-ec43-11ea-9fa6-fd3640a277ea.png)

**Comment by lukasfolle** [comment]
But as it would extend quite large probably other sites such as kornia.color wont be reachable without a lot of scrolling.
Such that I would favor the way pytorch does this with a index on the right side.

**Comment by edgarriba** [comment]
@lukasfolle absolutely, this would another way to do that. Can we do it with the default sphinx theme ?

**Comment by lukasfolle** [comment]
I guess not, but I am also quite new to read_the_docs. This is what I found at the pytorch sphinx theme:
![grafik](https://user-images.githubusercontent.com/26490449/91865218-71a01e80-ec71-11ea-9e5b-aa7e62e7c0bd.png)

**Comment by edgarriba** [comment]
@lukasfolle I started at some point the migration to the pytorch theme.
https://github.com/kornia/kornia/pull/517

I stopped it since e.g. the embed tutorials were not rendering well and notice other small differences. But if you want to give it a shot and resume this task, you will be more than welcome.

**Comment by lukasfolle** [comment]
@edgarriba Thank you for giving it a try. I am not familiar with the creation of docs using sphinx so I am closing this. If anyone else feels comfortable tackling this feel free to do so 😄
