### ISSUE TITLE
[Feat] Enable equalization of volumes (sequences of images)

### ISSUE THREAD

**Issue by vribeiro1** [kornia/kornia#637]
## 🚀 Feature

Implements equalize function for a sequence of images using PyTorch ops. Considers the histogram of the volume on the equalization calculations.

## Motivation

For medical applications, we often handle volumes, i.e., sequences of images. I am always frustrated that there is no easy way to implement volume transformations. For MRI data, histogram equalization is a mandatory pre-processing step, but we need to consider the distribution of the entire volume, not the single image.

## Pitch

My suggestion is to implement two new functions. The `_to_blchw`, similar to `kornia.utils.image._to_bchw`, and the `equalize_volume`, similar to `kornia.enhance.equalize`. The first, adds the batch dimension to a sequence (L) of images. The seconds equalizes the tensor given the volume's histogram.

## Alternatives

For general volume transformations, the alternative solution is to use the batch dimension as the sequence length dimension, and set `same_on_batch=True`. For equalization, this is not enough since the histogram calculation will still be in the image level.

A second alternative is to use video operations, but the operations are not fully interchangeable. So the differences must be taken into account.

Finally, there are volume transformations implemented on the SimpleITK library, but I would love to see something like this implemented on a library that uses native PyTorch.

## Additional context

I have my own separate implementation of what I want. And I have tested with MRI series, which worked fine. If my proposal is relevant, I can submit a pull request for further evaluation.

**Comment by shijianjian** [comment]
Sounds good. Please go ahead for the PR. 

You may use kornia.augmentation.utils._transform_input3d for the input standardisation. Note that we normally use BCDHW instead of the l dimension.

**Comment by shijianjian** [comment]
Added in #639 #653
