### ISSUE TITLE
Make kornia.augmentation.random_crop_generator safer

### ISSUE THREAD

**Issue by pmeier** [kornia/kornia#647]
## 🚀 Feature

Make `kornia.augmentation.random_crop_generator` safer.

## Motivation

Within `kornia.augmentation.random_crop_generator` `_adapted_uniform` is used to generate random starting points for the crop. Since it returns a `torch.float`, the upper delimiter (`high`) is increased by one (`high = x_diff + 1`) and cast to `torch.long`, which is basically a floor division. While this generates a uniform distribution of the integers, it opens up an edge-case: what if `Uniform.rsample` (used from `_adapted_uniform`) returns exactly (or within the precision) `high`?

```python
from unittest import mock
import torch
from kornia.augmentation.random_generator import _adapted_uniform

batch_size = 1
input_size = (None, 2)
size = (None, 1)
same_on_batch = True

x_diff = input_size[1] - size[1]


with mock.patch(
    "kornia.augmentation.utils.Uniform.rsample",
    new=lambda self, shape: torch.ones(shape) * self.high,
):
    x_start = _adapted_uniform((batch_size,), 0, x_diff + 1, same_on_batch).long()

print(f"x_start {'<=' if x_start <= x_diff else '>'} x_diff")
```
`x_start` should lesser or equal to `x_diff`, but as you can see

```
x_start > x_diff
```

## Pitch

Although this edge case is unlikely, I think we should implement this properly. Especially since the fix is trivial:

```python
from typing import Tuple, Union


def _adapted_uniform_int(
    shape: Union[Tuple, torch.Size],
    low: Union[float, torch.Tensor],
    high: [float, torch.Tensor],
    same_on_batch: bool = False,
) -> torch.Tensor:
    return _adapted_uniform(shape, low, high + 1 - 1e-6, same_on_batch).int()


with mock.patch(
    "kornia.augmentation.utils.Uniform.rsample",
    new=lambda self, shape: torch.ones(shape) * self.high,
):
    x_start = _adapted_uniform_int((batch_size,), 0, x_diff, same_on_batch).long()

print(f"x_start {'<=' if x_start <= x_diff else '>'} x_diff")
```

```
x_start <= x_diff
```

`_adapted_uniform_int` has the same signature as `_adapted_uniform`. The only difference to the above call is that we subtract a small constant from `high + 1` to prevent it from being drawn exactly. As long as this constant `1e-6` is smaller than `torch.finfo(torch.float).eps ~= 1.19e-7` this should be fine.

## Additional Context

I've encountered this while working with `kornia.augmentation.random_crop_generator`. If this used in other places throughout the code base the fix should be applicable everywhere.

**Comment by shijianjian** [comment]
If I understand it right, you mean the current implementation would perform a uniform sample from [low, high]?

According to the doc of [Uniform](https://pytorch.org/docs/stable/distributions.html#torch.distributions.uniform.Uniform), it shall be already [low, high).

**Comment by pmeier** [comment]
Yeah my bad, I should have checked this. In that case it is safe as is. We still could implement `_adapted_uniform_int` without the constant to make this more convenient.

**Comment by shijianjian** [comment]
Without which constant for ```_adapted_uniform_int```?

How about adding a new param ```dtype```? Something like:
```python
def _adapted_uniform(
    shape: Union[Tuple, torch.Size],
    low: Union[float, torch.Tensor],
    high: Union[float, torch.Tensor],
    same_on_batch: bool = False,
    dtype: Optional[Torch.DType]=None
) -> torch.Tensor:
```

**Comment by pmeier** [comment]
About the small numerical constant `1e-6` and the safety of `Uniform`. I don't think its as easy as we thought. Consider the following edge scenario:

```python
from torch.distributions import Uniform
import torch

low = 1.0 - torch.finfo(torch.float).eps
high = 1.0
dist = Uniform(low, high)

torch.manual_seed(0)
print(dist.rsample((10,)).int())
```

```
tensor([0, 1, 0, 0, 0, 0, 0, 1, 0, 0], dtype=torch.int32)
```

Since `.int()` is basically a floor division, `rsample` indeed returns exactly `high`. Without further investigation I think this is due to numerical issues: any number that is drawn that is larger than `1.0 - torch.finfo(torch.float).eps/2` will flip to `1.0`.

--- 

The extra `dtype` parameter seems fine. I think it could look like this:

```python
def _adapted_uniform(..., dtype: torch.dtype = torch.float):
     ...
     if not dtype.is_floating_point:
         high += 1 - 1e-6
     return Uniform.rsample(...).to(dtype)
```

**Comment by shijianjian** [comment]
I think it should be a bug for PyTorch team than ours. But before they fix this, I think we could have this functionality for ```_adapted_uniform``` for safer cropping. Do you mind going for a PR?

**Comment by pmeier** [comment]
IMO this is not a bug but a limitation of the floating point format. Values between `1.0 - torch.finfo(torch.float).eps` and `1.0` simply cannot be represented by a `torch.float32`. That means, if we draw a value from this range the distribution might not return `1.0` but a value that cannot represented by anything else. By including the small constant such as `1e-6` we can simply circumvent this completely.

**Comment by edgarriba** [comment]
we can this to the documentation as a side note, otherwise this limitation will dead here in this issue and not to the final user.

**Comment by pmeier** [comment]
@edgarriba If we include the `dtype` in `_adapted_uniform` we don't need to change the documentation at all.

**Comment by shijianjian** [comment]
If our final fix is to use something like:
```python
     if not dtype.is_floating_point:
         high += 1 - 1e-6
```
Then I think we should better include it in the doc than apply that fix. If I am a user that I want to generate from [1, 2], I may do:
```python
Uniform(1, 2.1)
```
If we did a brutal deduction here, the user will sample a ```3``` as well which he is not intended to.

**Comment by pmeier** [comment]
@shijianjian Neither `_adapted_uniform` nor `kornia.augmentation.random_crop_generator` is documented at all. Even if it where, I don't see where you getting at with your approach: why don't you want to fix this bug and only document its existence? I don't think fixing it is BC breaking for anyone. If you do, could you give an example?

>  If I am a user that I want to generate from [1, 2], I may do:

Assuming you are talking about sampling `int`s here. If you do that, you will not get a uniform distribution at all: values in the interval `[1.0, 2.0)` map to `1` while values from `[2.0, 2.1]` will map to `2`. As you can see the latter interval is far smaller than the former. This is why we already are sampling from `[1.0, 3.0)` (`[1.0, 2.0 + 1)`) to get a uniform distribution of `1`s and `2s`: `[1.0, 2.0)` maps to `1` and `[2.0, 3.0)` map to `2`. 

As explained above simply `Uniform(1.0, 3.0).rsample()` is dangerous since it might yield exactly `3.0` due to numerical limitations. To circumvent this we subtract a small constant and now get the following intervals: `Uniform(1.0, 3.0 - 1e-6).rsample()`: `[1.0, 2.0)` maps to `1` and `[2.0, 3.0 - 1e-6)` maps to `2`. While the second interval is indeed smaller than the first, it is only be a very small margin that is negligible in most cases.

**Comment by shijianjian** [comment]
I meant with a brutal deduction (even it is a 1e-6) is a bit inappropriate to me. I did some investigation here, the ```torch.float32``` is not enough when we have values like ```1 - torch.finfo(torch.float).eps / 4.0``` as the input.
```
>>> torch.set_printoptions(precision=32)
>>> torch.tensor(1 - torch.finfo(torch.float).eps / 2.0)
tensor(0.99999994039535522460937500000000)
>>> torch.tensor(1 - torch.finfo(torch.float).eps / 4.0)
tensor(1.)
```
So, if we use ```torch.float64```:
```
>>> torch.tensor(1 - torch.finfo(torch.float).eps / 4.0).int()
tensor(1, dtype=torch.int32)
>>> torch.tensor(1 - torch.finfo(torch.float).eps / 4.0, dtype=torch.float64).int()
tensor(0, dtype=torch.int32)
```
Thus, within your example, we only need to cast everything into ```torch.float64``` will solve the problem.
```
>>> dist = Uniform(torch.tensor(low, dtype=torch.float64), torch.tensor(high, dtype=torch.float64))
>>> dist.rsample((10,)).int()
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
>>> dist.rsample((10,)).int()
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
>>> dist.rsample((10,)).int()
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)
```

In the code, it seems like we only need to:
```python
def _adapted_uniform(shape: Union[Tuple, torch.Size], low: Union[torch.Tensor, int, float],
                     high: Union[torch.Tensor, int, float], same_on_batch=False) -> torch.Tensor:
    r""" The uniform function that accepts 'same_on_batch'.
    If same_on_batch is True, all values generated will be exactly same given a batch_size (shape[0]).
    By default, same_on_batch is set to False.
    """
    if not isinstance(low, torch.Tensor):
        low = torch.tensor(low, dtype=torch.float64)
    if not isinstance(high, torch.Tensor):
        high = torch.tensor(high, dtype=torch.float64)
    dist = Uniform(low, high)
    if same_on_batch:
        return dist.rsample((1, *shape[1:])).repeat(shape[0])
    else:
        return dist.rsample(shape)
```

**Comment by pmeier** [comment]
This will make the problem more unlikely, but does not fix it:

```python
import torch
from torch.distributions import Uniform

low = 1.0 - torch.finfo(torch.float64).eps
high = 1.0
dist = Uniform(torch.tensor(low, dtype=torch.float64), torch.tensor(high, dtype=torch.float64))

torch.manual_seed(0)
print(dist.rsample((10,)).int())
```

```
tensor([1, 0, 0, 1, 0, 1, 0, 0, 0, 0], dtype=torch.int32)
```

As long as we use a floating point representation with a fixed number of bits (which is always as long we build upon PyTorch) this will always be possible. 

> I meant with a brutal deduction (even it is a 1e-6) is a bit inappropriate to me.

Could you explain why? As stated above, the interval is negligibly smaller and this should have no measurable effect on the user. If we allow the full interval a user might (albeit very unlikely) run into an error that is basically non-reproducible, which should not happen.

**Comment by shijianjian** [comment]
The brutal deduction will clearly be failed when they want something like ```_adapted_uniform(1 - 1e-6, 1 + 1e-6)```, which this should output a 50/50 chance to be under or over 1. Thus, the deduction with 1e-6 will not affect user only if we assume they always input ```high - low >> 1e-6```.  At least, this ```_adapted_uniform``` function is not designed as so.

In the context of this issue, ```torch.distribution.Uniform``` is a bit buggy since it seems to overflow the ```torch.float```, which would cause unexpected values with ```.int()``` operation. So here:
1. I still think it might be an issue for PyTorch team, the ```torch.distribution.Uniform``` will have unexpected values than they documented.
2. I am not confident, but I am thinking of your first proposal to have something like ```_adapted_uniform_int```. In which I think we might do it as simple as:
    ```python
    def _adapted_uniform_int(low, high):
         ints = _adapted_uniform(low, high).int()
         return torch.where(ints == high, ints - 1, ints)
    ```
    In this case, we do not mess up with the user's inputs but perform postprocessing towards the expected outcomes.

**Comment by pmeier** [comment]
> The brutal deduction will clearly be failed when they want something like `_adapted_uniform(1 - 1e-6, 1 + 1e-6)`, which this should output a 50/50 chance to be under or over 1. Thus, the deduction with 1e-6 will not affect user only if we assume they always input `high - low >> 1e-6`. At least, this `_adapted_uniform` function is not designed as so.

As stated above the subtraction of the small constant should only apply if the input is **not** a floating point `dtype`:

```python
def _adapted_uniform(..., dtype: torch.dtype = torch.float):
     ...
     if not dtype.is_floating_point:
         high += 1 - 1e-6
     return Uniform.rsample(...).to(dtype)
```

Thus, a problem as you are describing will not happen.

> I still think it might be an issue for PyTorch team, the `torch.distribution.Uniform` will have unexpected values than they documented.

Again, this is not a bug, but a limitation of the floating point `dtype`s with a constant number of bits. Thus, it **can't** be fixed, only circumvented. Since we have a concrete case where this could fail, we should simply circumvent this in our code as their library is more general.

**Comment by shijianjian** [comment]
In this context, the ```dtype``` param controls the output type, not the input type. Users can still do something like ```_adapted_uniform(1 - 1e-6, 1 + 1e-6, dtype=torch.long)``` in your example.

Also, why insist on modifying the user's inputs?

**Comment by pmeier** [comment]
> In this context, the dtype param controls the output type, not the input type

Correct, that was a mistake. It should have been

"the subtraction of the small constant should only apply if the ~in~**out**put is not a floating point dtype"

> Users can still do something like `_adapted_uniform(1 - 1e-6, 1 + 1e-6, dtype=torch.long)` in your example.

This whole thread started with me noting that `_adapted_uniform` is unsafe when it is used as is (for example in `random_crop_generator`) to generate a uniform distribution of `int`s. You suggested we use a new parameter `dtype` to solve this. 

Given that, how would your example be sensible? I mean, do you want a uniform distribution of integers between `1 - 1e6` and `1 + 1e6`? What do you expect as an output?

> Also, why insist on modifying the user's inputs?

I only insist on having this working as expected. If you know another way to generate a uniform distribution of `int`s without the risk of generating a value outside of the given interval, I'm happy to use that.

**Comment by shijianjian** [comment]
It does not matter how sensible it is. We should disallow the usage of ```_adapted_uniform(1 - 1e-6, 1 + 1e-6, dtype=torch.long)``` if we know it will give unexpected values.

I think the following shall be simple and intuitive enough to address the floating overflow issue with integers.

```python
def _adapted_uniform_int(low, high):
     ints = _adapted_uniform(low, high).int()
     return torch.where(ints >= high, ints - 1, ints)
```

**Comment by pmeier** [comment]
> It does not matter how sensible it is. We should disallow the usage of `_adapted_uniform(1 - 1e-6, 1 + 1e-6, dtype=torch.long)` if we know it will give unexpected values.

Given that `_adapted_uniform` is an internal function and not documented anywhere I don't think it is that important to make this completely foolproof. That being said, I don't mind going for `_adapted_uniform_int` as it is what I proposed in the first place.

> I think the following shall be simple and intuitive enough to address the floating overflow issue with integers.

It is, but it significantly affects the performance:

```python
import timeit as _timeit
from kornia.augmentation.random_generator import _adapted_uniform


def adapted_uniform_mask(shape, low, high):
    ints = _adapted_uniform(shape, low, high).int()
    return torch.where(ints >= high, ints - 1, ints)


def adapted_uniform_eps(shape, low, high):
    return _adapted_uniform(shape, low, high + 1 - 1e-6).int()


shape = (1000,)
low = 0
high = 255


def timeit(fn, number=100000):
    total = _timeit.timeit(lambda: fn(shape, low, high), number=number)
    avg = total / number
    if avg < 1e-3:
        factor = 1e6
        unit = "µs"
    else:
        factor = 1e3
        unit = "ms"
    print(f"Average runtime for {fn.__name__}: {avg * factor:.1f} {unit}")


timeit(_adapted_uniform)
timeit(adapted_uniform_mask)
timeit(adapted_uniform_eps)
```

```
Average runtime for _adapted_uniform: 72.5 µs
Average runtime for adapted_uniform_mask: 113.9 µs
Average runtime for adapted_uniform_eps: 75.2 µs
```

While your suggestion increases the runtime by ~57%, my approach only needs ~4% more runtime. Both approaches yield the same distribution:

```python
import torch


def histc(fn):
    torch.manual_seed(0)
    return torch.histc(
        adapted_uniform_mask(shape, low, high).float(), bins=high, min=low, max=high,
    )


assert torch.all(histc(adapted_uniform_mask) == histc(adapted_uniform_eps))
```

**Comment by pmeier** [comment]
@shijianjian How do you want to proceed?

**Comment by shijianjian** [comment]
I personally will not include a potential buggy function. Your implementation shall add a type check first to ensure ```low is int, high is int``` to guarentee the correct output. I am alright with either:

```python
def adapted_uniform_eps(shape, low, high):
    assert isinstance(low, (int, torch.Tensor)), ""
    assert isinstance(high, (int, torch.Tensor)), ""
    return _adapted_uniform(shape, low, high + 1 - 1e-6).int()
```
or
```python
def adapted_uniform_mask(shape, low, high):
    ints = _adapted_uniform(shape, low, high).int()
    if ints.max() >= high:
        return torch.where(ints >= high, ints - 1, ints)
    return ints
```

Both methods have some drawbacks here, the first one will only accept integers while the second one is a little slower.
