### ISSUE TITLE
[Bug][Feat] Failing tests for Half precision due to operations not implemented in Half

### ISSUE THREAD

**Issue by FGeri** [kornia/kornia#649]
## 🐛 Bug

Some tests fail due to some operations not being implemented for half precision, eg.:
FAILED test/geometry/epipolar/test_essential.py::TestEssentialFromFundamental::test_from_to_fundamental[cuda-float16] - RuntimeError: "inverse_cuda" not implemented for 'Half'
FAILED test/geometry/epipolar/test_essential.py::TestEssentialFromFundamental::test_from_fundamental[cuda-float16] - RuntimeError: "lu_cuda" not implemented for 'Half'
FAILED test/geometry/epipolar/test_essential.py::TestDecomposeEssentialMatrix::test_smoke[cuda-float16] - RuntimeError: "svd_cuda" not implemented for 'Half'

## Expected behavior

All tests should pass.

## Environment

PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.18.1

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 440.44
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0

**Comment by edgarriba** [comment]
@FGeri we don't properly test torch.float16 yet in the CI. So expect some adventures. Is this something that you need ?

**Comment by FGeri** [comment]
Not at the moment, just bumped into it when running the test suit for a PR. Probably those ops were deliberately not implemented due to the possible loss of precision, so maybe the functions depending on such ops should cast the input args to at least float32 or double for the sake of accuracy anyway.

**Comment by edgarriba** [comment]
I'd launch an assertion instead and not support them until pytorch does, otherwise they mostlikely will end up with fake dtype forever in kornia.

**Comment by edgarriba** [comment]
@FGeri I consulted to the pytorch core team about this and there's no short term plan to support such functionalities in fp16. The suggestion was to cast to fp32 compute inverse and go back to fp16

**Comment by edgarriba** [comment]
half precision is already supported in > `0.5.1`
