### ISSUE TITLE
[Docs] Missing `crop_by_boxes` docs

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#651]
## 📚 Documentation

Non existing documentation for [`kornia.crop_by_boxes`](https://github.com/kornia/kornia/blob/f4f70fefb63287f72bc80cd96df9c061b1cb60dd/kornia/geometry/transform/crop.py#L159)

Needs also improvement in typing and parameters definition.

**Comment by shijianjian** [comment]
Added in #609
