### ISSUE TITLE
5 points in get_perspective_transform

### ISSUE THREAD

**Issue by twmht** [kornia/kornia#657]
Hi,

I am not familiar with the formula, but  this API `get_perspective_transform`  (https://kornia.readthedocs.io/en/latest/_modules/kornia/geometry/transform/imgwarp.html#get_perspective_transform) has limitations on the inputs, only 4 points are allowed.

But in my applications, I have 5 points  to align, is there any way to modify the code to support 5 points?

thank you

**Comment by ducha-aiki** [comment]
You could use https://kornia.readthedocs.io/en/latest/_modules/kornia/geometry/homography.html#find_homography_dlt or https://kornia.readthedocs.io/en/latest/geometry.homography.html#kornia.geometry.homography.find_homography_dlt_iterated

Homography is the perspective transform

**Comment by twmht** [comment]
I've seen that before. But how could I pass `weights` to the API?

**Comment by edgarriba** [comment]
@twmht for the case of 5 points just call `find_homography_dlt_iterated(pts1, pts2, weights=torch.ones(B, 5))` where `pts1` and `pts2` has shape of `Bx5x2`. Is that what you are asking ?

**Comment by ducha-aiki** [comment]
@twmht weights mean your confidence in the resp. point pair, as the 5 is more than the minimum necessary number of points = 4 to estimate the perspective transform. Thus, if points disagree, weights are here to help.  
As @edgarriba said, just send torch.ones(B,5) if you think that all 5 are correct

**Comment by twmht** [comment]
thank you guys:)
