### ISSUE TITLE
[Bug] RandomAffine3D throws an exception when used with scales

### ISSUE THREAD

**Issue by FGeri** [kornia/kornia#674]
## 🐛 Bug

RandomAffine3D throws an exception when used with scales

        if scale is not None:
            assert scale.shape == torch.Size([3, 2]), f"'scale' must be the shape of (3, 2). Got {scale.shape}."
            scale = torch.cat([
                _adapted_uniform((batch_size,), scale[0, 0], scale[0, 1], same_on_batch),
                _adapted_uniform((batch_size,), scale[1, 0], scale[1, 1], same_on_batch),
                _adapted_uniform((batch_size,), scale[2, 0], scale[2, 1], same_on_batch),
>           ], dim=1)
E           IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

## To Reproduce
augmentation=RandomAffine3D(degrees=45., translate = (0.5,0.5,0.5),scale= (0.5,0.5),align_corners = True,return_transform=True),
input = torch.zeros((1,1,50,100,200),device=device, dtype=dtype)
output,T = augmentation(input

**Comment by shijianjian** [comment]
You may update it from ```torch.cat``` to ```torch.stack```. Will fix it in the master soon.
