### ISSUE TITLE
Backpropagation through Translation

### ISSUE THREAD

**Issue by NivNayman** [kornia/kornia#682]
Hi,
Thank you for the wonderful package !
I have been trying to learn translation (x, y) parameters in the following manner:

`class DTranslation(nn.Module):
    def __init__(self, x_translation, y_translation):
        super(DTranslation, self).__init__()
        self.translations = torch.stack([x_translation, y_translation], 1)
        self.angle = torch.tensor([0])
        
        
    def forward(self, input):
        _, _, h, w = input.shape
        if self.angle.shape[0] != input.shape[0]:
            angle = self.angle.repeat(input.shape[0])
        else:
            angle = self.angle
            
        if self.translations.shape[0] != input.shape[0]:
            translations = self.translations.repeat([input.shape[0], 1])
        else:
            translations = self.translations
        
        translations[:, 0] *= h
        translations[:, 1] *= w
        
        # define the rotation center
        center = torch.ones(2)
        center[..., 0] = input.shape[3] / 2  # x
        center[..., 1] = input.shape[2] / 2  # y
        center = center.repeat(input.shape[0], 1)

        # define the scale factor
        scale = torch.ones(input.shape[0])

        # compute the transformation matrix
        M = kornia.get_rotation_matrix2d(center, -angle, scale)
        
        # Translate
        M[..., 2] += translations  # tx/ty
        
        # apply the transformation to original image
        out = kornia.warp_affine(input, M, dsize=(h, w))
        
        return out

tx = torch.tensor([0.3], dtype=torch.float32)
tx_p = Parameter(tx, requires_grad=True)
            
ty = torch.tensor([-0.2], dtype=torch.float32)
ty_p = Parameter(ty, requires_grad=True)

translation = DTranslation(x_translation=tx_p, y_translation=ty_p)

criterion = nn.MSELoss()
optimizer = optim.Adam([tx_p, ty_p], lr=1)

for x, y in dataloader: 
        optimizer.zero_grad()
        loss = criterion(x, translation(x))
        loss.backward()
        optimizer.step()`

The first backward call passes, but the second one fails:

`
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
`
When I follow the instructions and instead I use:
 `loss.backward(retain_graph=True)`
I receive the following error:
`
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [1]] is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
`
I also tried to avoid the inplace operation:
`M[..., 2] += translations `
and use instead:
`
shape = list(M.shape)
shape[-1] -= 1
M = M + torch.cat([torch.zeros(shape), translations.unsqueeze(-1)], 2)
`
but got the same errors.

Maybe another inplace operation causes this ? e.g. https://github.com/kornia/kornia/blob/5a736409a9a133da27c3dfa581bba2bc71f27286/kornia/geometry/conversions.py#L122

Or is it something else ?

It is worth mentioning that I do manage to backpropagated through rotation angle and shear (x, y) but only translation seems to be the problem, i.e. when I comment out
`M[..., 2] += translations `
No errors occur, but of course I cannot learn the translation parameters either.

Any thoughts ?

**Comment by edgarriba** [comment]
@NivNayman thanks for reporting this error. Could you try to run the code as said in the error message `with torch.autograd.set_detect_anomaly(True)` to see which operator raises this error? Besides, if you could also share a colab with this minimal example we can take it a look at it.

**Comment by NivNayman** [comment]
Thank you for your replay. 

Here is a link for the colab: https://colab.research.google.com/drive/1i9f82qltMn7gHqAfSyyt4qjvCHSc06Mz?usp=sharing
Please note that while rotation angle is learnt properly, translation raised this kind of errors.

The same error is raised when using `with torch.autograd.set_detect_anomaly(True)`:

`RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
Exception raised from apply at /pytorch/torch/csrc/autograd/generated/Functions.cpp:10227 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f14932971e2 in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch::autograd::generated::StackBackward::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x29f (0x7f14d1072dcf in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x3375bb7 (0x7f14d1675bb7 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #3: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x1400 (0x7f14d1671400 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #4: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x451 (0x7f14d1671fa1 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>) + 0x37c (0x7f14d166f6bc in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::python::PythonEngine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>) + 0x3c (0x7f14dee0a8dc in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #7: torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x803 (0x7f14d166e9f3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x4e (0x7f14dee0a6de in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: THPEngine_run_backward(THPEngine*, _object*, _object*) + 0xa54 (0x7f14dee0b3c4 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)`

**Comment by kshitij12345** [comment]
Looking at the colab code, my suspicion is at 
```python
        translations[:, 0] *= h
        translations[:, 1] *= w
```

As you update the values here in-place.

**Comment by NivNayman** [comment]
Thank you for the suggestion. 
I also comment out those lines but still same error.

**Comment by edgarriba** [comment]
@kshitij12345 @NivNayman maybe same applied here `M[..., 2] += translations  # tx/ty`  ?

**Comment by NivNayman** [comment]
So, as I mentioned in the original post, for avoiding the inplace operation, I also tried replacing 
`M[..., 2] += translations # tx/ty`
with:
shape = list(M.shape) 
shape[-1] -= 1 
M = M + torch.cat([torch.zeros(shape), translations.unsqueeze(-1)], 2)

**Comment by shijianjian** [comment]
@NivNayman This error is actually introduced by your initialization ```self.translations = torch.stack([x_translation, y_translation], 1)```. I think this line makes the learnable ```x_translation```, ```y_translation``` params invisible.

The below code worked for me.

```python
from torch.nn.parameter import Parameter

class DTranslation(nn.Module):
    def __init__(self, x_translation, y_translation, angle=torch.tensor([0.])):
        super(DTranslation, self).__init__()
        self.x_translation = x_translation
        self.y_translation = y_translation
        self.angle = angle
    
    def __compute__(self, input, angle, translations):
        # define the rotation center
        center = torch.ones(2)
        center[..., 0] = input.shape[3] // 2  # x
        center[..., 1] = input.shape[2] // 2  # y
        center = center.repeat(input.shape[0], 1)

        # define the scale factor
        scale = torch.ones(input.shape[0], 2)

        # compute the transformation matrix
        M = kornia.get_rotation_matrix2d(center, -angle, scale)
        # print(M)
        M_part = torch.zeros((input.size(0), 2, 2))
        M_add = torch.cat([M_part, translations], 2)
        x_M = M + torch.nn.functional.pad(translations, [2, 0, 0, 0, 0, 0], value=0)
        return x_M

    def forward(self, input):
        angle = self.angle.repeat(input.shape[0])
        translations = torch.stack([self.x_translation, self.y_translation], 1)
        translations = translations.repeat([input.shape[0], 1])
        translations = translations.unsqueeze(-1)
        print(translations.requires_grad)
        
        x_M = self.__compute__(input, angle, translations)

        # apply the transformation to original image
        out = kornia.warp_affine(input, x_M, dsize=(input.size(2), input.size(3)))

        return out
```

**Comment by NivNayman** [comment]
Wonderful ! It works now:
![learn_x_translation_0 30000001192092896_y_translation_-0 20000000298023224_entropy_0 01_step_](https://user-images.githubusercontent.com/29902065/93782432-3cb13700-fc33-11ea-91b8-073a224eeb0c.gif)

Indeed the **only** problem was  placing `        translations = torch.stack([self.x_translation, self.y_translation], 1)
` at the __init__() rather than in the forward().

FYI all the inplace operations doesn't interfere with the differentiation as those are all differentiable, i,e, both:
`  translations[:, 0] *= h
    translations[:, 1] *= w`
And:
 `    M[..., 2] += translations 
`

Closing the issue.

**Comment by shijianjian** [comment]
Hi @NivNayman, impressive gif you have made!

We are currently actively looking for tutorials/examples using Kornia, especially on those demonstrated differentiabilities in a world use cases. I think your example can be a very impressive one. Let me know if you are okay with making a jupyter notebook!

**Comment by NivNayman** [comment]
I suppose I can do that.

**Comment by edgarriba** [comment]
@NivNayman please, join our slack community in case you want to discuss more on this
