### ISSUE TITLE
[Bug] Tests failed occasionally in Python 3.6

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#685]
## 🐛 Bug

It seems like ```test_essential.TestEssentialFromFundamental.test_from_to_fundamental``` will not always output similar outputs in different seeds.

I run the tests twice and this function failed twice with different outputs (the last time diff is 0.001 and this time is 0.004). Is it expected or we should somehow fix it?

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by edgarriba** [comment]
After a quick check, I suspect the error could come from 
https://github.com/kornia/kornia/blob/339340b4a61153edcc2cb1467ba035c93c878c3f/kornia/geometry/epipolar/scene.py#L22

since it has been reported several times that this API seems to be broken

**Comment by edgarriba** [comment]
@shijianjian is this still relevant ?

**Comment by shijianjian** [comment]
Probably shall be closed now.
