### ISSUE TITLE
[Feat] Bounding boxes geometry sub-module

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#688]
## 🚀 Feature

I open this feature request ticket to kickoff a dedicated sub-module to deal with different functionalities to work with bounding boxes. We already have some functionalities across the library that could be grouped in the same place under `kornia.geometry.transform.boxes`.

Different existing operations:

Found in: https://github.com/kornia/kornia/blob/master/kornia/geometry/transform/crop.py
```python
    "bbox_to_mask",
    "infer_box_shape",
    "validate_bboxes",
    "bbox_generator"
```
Found in: https://github.com/kornia/kornia/blob/master/kornia/geometry/linalg.py#L230
```python
    "transform_boxes",
```

## Motivation

The main motivation is that all the bboxes functionalities are scattered across different places.

## Pitch

 The idea is to group all the functionalities for bounding boxes in the same place: `kornia.geometry.transform.boxes`.

**Comment by shijianjian** [comment]
One function not sure about ````K.geometry.linalg.transform_boxes``, should be included or not?

**Comment by dkoguciuk** [comment]
Done in #1103 .
