### ISSUE TITLE
Broken link "InvDepthSmoothnessLoss"

### ISSUE THREAD

**Issue by KushajveerSingh** [kornia/kornia#692]
## 📚 Documentation

In the documentation of this function https://kornia.readthedocs.io/en/latest/losses.html#kornia.losses.inverse_depth_smoothness_loss, the link is broken.

```See InvDepthSmoothnessLoss for details.```

The error is due to an incorrect name. The correct name should be `InverseDepthSmoothnessLoss`.

**Comment by edgarriba** [comment]
@KushajveerSingh could you send a quick PR fixing the typo ?
