### ISSUE TITLE
[Question] Why a left-handed camera reference frame?

### ISSUE THREAD

**Issue by swiss-knight** [kornia/kornia#704]
https://github.com/kornia/kornia/blob/master/docs/source/data/pinhole_model.png

Why the choice of a left-handed coordinate system was done for the camera reference frame?    

Most of the frameworks make use of a right-handed coordinate system.

**Comment by edgarriba** [comment]
@swiss-knight I think it's just an issue for this image representation. Have you found any specific issue on the code for this ?
