### ISSUE TITLE
[Feat] Input value range converting from (0, 255) to (0, 1)

### ISSUE THREAD

**Issue by allanbatista** [kornia/kornia#705]
## 🐛 Bug

When try to use **ColorJitter** all images become BLACK.

## To Reproduce

https://colab.research.google.com/drive/1xtuFk-jcrJON47ZHxw28Ig9BKPamR85n?usp=sharing

## Environment

Colab

**Comment by FGeri** [comment]
@allanbatista Kornia augmentations expects the images to be scaled to [0,1], so if you divide the input by 255 before the augmentation then multiply it by 255 for display it should be fine.
@shijianjian @edgarriba I don't seem to find this in the docs now. Also some runtime validation would be nice to avoid such situations.

**Comment by shijianjian** [comment]
We current only checked if the dtype is float or not. Will add this test soon.

**Comment by edgarriba** [comment]
All the library assumes inputs to be normalised between 0/1. We can improve documentation on this. 

I don't think it's a good Idea checking ranges here, since it might hurt to the performance at running times. Besides, since we assume batched inputs might be a bit tricky.

**Comment by allanbatista** [comment]
> @allanbatista Kornia augmentations expects the images to be scaled to [0,1], so if you divide the input by 255 before the augmentation then multiply it by 255 for display it should be fine.
> @shijianjian @edgarriba I don't seem to find this in the docs now. Also some runtime validation would be nice to avoid such situations.

Thanks @FGeri , this works well now. But is some weird, some augmentation works well with "255" pixels and others not.
So, I agree with @edgarriba this not a good idea to try to "understand" what kind a data are in the input. Is better to make this explicit on doc. :)

**Comment by shijianjian** [comment]
Yes. We will make this more specific in the docs.

> Thanks @FGeri , this works well now. But is some weird, some augmentation works well with "255" pixels and others not.

Most geometric transformations may work because they may not need to modify the inner pixels.

Also, I am thinking of having something like ```K.StandardizeInput2D``` and ```K.StandardizeInput3D``` to help standardize the input sequence as:
```python
nn.Sequential(
    K.StandardizeInput2D(),
    K.ColorJitter()
)
```

But not sure if it is necessary since it will be useless if the user is familiar with the lib. The only use-case I can think of is when (0, 255) and (0, 1) appeared in a batch simultaneously while it is not a common scenario.

**Comment by edgarriba** [comment]
@shijianjian isn't standarise already `Normalize` ops ?

**Comment by shijianjian** [comment]
@edgarriba Not meant ```Normalize``` here. Something similar as ```ToTensor()``` in Torchvision.

**Comment by edgarriba** [comment]
What action should we take here ? I vote to update docs at first.

**Comment by shijianjian** [comment]
Yes. Will update the docs for sure. May implement ```Kornia.TensorStandardize``` or so later. Low priority.

**Comment by edgarriba** [comment]
what about `NormalizeTensor()`?

**Comment by shijianjian** [comment]
I would try to avoid the confusion between ```Normalize``` and ```NormalizeTensor```. Or maybe ```AsDifferentiableTensor```?

I think we might support the conversion from ```torch.int8, torch.int16``` (assume BCHW, CHW, HW), ```numpy.uint8, numpy.uint16``` (assume BHWC, HWC, HW).

Probably include ```volume_to_tensor```, ```tensor_to_volume``` as well, similar to the existing ```image_to_tensor```, ```tensor_to_image```.

**Comment by edgarriba** [comment]
+1 for  `volume_to_tensor` and `tensor_to_volume` -> open a separated ticket with the feature request

As for to tensor, why not just `ToTensor` ? I guess pytorch users would be already used to it.

**Comment by shijianjian** [comment]
Because ```ToTensor``` is for converting numpy array / PIL image into a torch tensor, while we are accepting tensor / array. I feel it is better to differentiate it.

If I got a uint8 tensor, then calling ```ToTensor``` is not really making sense.

**Comment by edgarriba** [comment]
we could consider this in  https://github.com/kornia/kornia/issues/941
