### ISSUE TITLE
[Feat] Add the `same_on_batch` for random motion blur

### ISSUE THREAD

**Issue by skyoung** [kornia/kornia#707]
https://github.com/kornia/kornia/blob/6292943088cbb32adf323ebdb497d3e5f290f19e/kornia/augmentation/augmentation.py#L803-L804

Current implementation of `RandomMotionBlur` misses the flag of `same_on_batch` to set batch mode. Please add this in a later release. Thanks.

**Comment by shijianjian** [comment]
Makes sense. It should be relatively easy to do.

https://github.com/kornia/kornia/blob/6292943088cbb32adf323ebdb497d3e5f290f19e/kornia/filters/filter.py#L99

I think the easiest approach is to edit the kernel in ```filter2D``` and ```filter3D```. It is currently repeated by ```c``` times. \cc @edgarriba

**Comment by edgarriba** [comment]
@skyoung can you send a PR with this ?

**Comment by shijianjian** [comment]
This functionality has already been included in #713. Will finalize the PR soon.
