### ISSUE TITLE
[Feat] Update the default values for align_corners and interpolation

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#715]
## 🚀 Feature

Proposal:
- ```align_corners = True``` for all augmentations (potentially some functional as well)
- ```interpolation = 'nearest', align_corners = True``` for all cropping augmentations and functional.

Relevant issues:
#485
#546 
#617

**Comment by ducha-aiki** [comment]
>interpolation = 'nearest', align_corners = True for all cropping augmentations and functional. 
Agree

>align_corners = True for all augmentations (potentially some functional as well)
Don't agree. Not aligning corners for rotation and the rest of destructive works better for me. Although, not sure about how typical are my use-cases.

**Comment by edgarriba** [comment]
fixed in https://github.com/kornia/kornia/commit/cb3fc49b42323992cb41157859631d0785eb900e
