### ISSUE TITLE
[Bug] get_rotation_matrix_2d should still work isotropic scale factor

### ISSUE THREAD

**Issue by ivanzvonkov** [kornia/kornia#742]
## 🐛 Bug

https://github.com/kornia/kornia/pull/646 removed isotropic scale factor in favor of non-isotropic (x,y) scale factor

This is a breaking change for any library using `get_rotation_matrix_2d` (ie. [Lucent](https://github.com/greentfrapp/lucent))

## Expected behavior

I suggest allowing both isotropic and non-isotropic scale factors.

**Comment by shijianjian** [comment]
Could be added, but I think it shall be better if the low-level functions will only accept the more primitive parameters? @edgarriba

**Comment by edgarriba** [comment]
I agree with Jian. @ivanzvonkov for your specific case I believe that `kornia.rotate` can fix the issue: https://kornia.readthedocs.io/en/latest/geometry.transform.html?highlight=rotate#kornia.geometry.transform.rotate

**Comment by ivanzvonkov** [comment]
I generally agree that it makes sense for low-level functions to accept primitive parameters.

However, in this case (a breaking change to a low-level function), I'd recommend temporarily allowing both isotropic scale factors with some sort of deprecation warning. 

A warning will give owners of kornia dependent code bases some time to react to the change and will ensure that everything keeps functioning. I don't think it's good practice for people to find out about changes to dependencies because functionality stops working.

**Comment by ducha-aiki** [comment]
@ivanzvonkov I agree with you about warnings, we will adopt such policy

**Comment by edgarriba** [comment]
@ivanzvonkov can we close this or do you need us to help with anything else ?

**Comment by ivanzvonkov** [comment]
Sure this can be closed.
