### ISSUE TITLE
[Bug] get_affine_matrix2d output bug

### ISSUE THREAD

**Issue by RemonComputer** [kornia/kornia#745]
## 🐛 Bug

get_affine_matrix2d outputs (B, 3, 3) while documentation states that it should output (B, 2, 3) (This is the bug), But I noticed it because warp_affine expects (B, 2, 3)
## To Reproduce

1.use kornia.geometry.transform.get_affine_matrix2d

## Expected behavior

You should output (B, 2, 3) or make warp_affine use (B, 3, 3)

the output should be (B, 2, 3)
## Environment
I am using kornia 0.4.1

**Comment by shijianjian** [comment]
I think it might be the documentation error.

You may wrap using ```affine_matrix[:, :2, :]``` instead.

**Comment by edgarriba** [comment]
This a bug in here https://github.com/kornia/kornia/blob/023da9a7dbb7dab77a36c246b8244e91415decc6/kornia/geometry/transform/imgwarp.py#L483

Can be solved as @shijianjian suggests. Proper unit tests are needed here

**Comment by RemonComputer** [comment]
Thanks @edgarriba and @shijianjian , I can solve the problem but I am reporting it for fixing

**Comment by abhishekaich27** [comment]
Faced this error today. Hope it gets resolved.
