### ISSUE TITLE
I am getting an error while installing the package

### ISSUE THREAD

**Issue by Anit-G** [kornia/kornia#746]
Collecting kornia
  Using cached https://files.pythonhosted.org/packages/25/f6/9fb4cc2c67796680c8041fa6ffdee5f280e4cf65c86835768a700a324d59/kornia-0.4.1-py2.py3-none-any.whl
Requirement already satisfied: numpy in c:\users\kunal.laptop-7lv8bft8\anaconda3\lib\site-packages (from kornia) (1.16.5)
Collecting torch>=1.6.0 (from kornia)
  ERROR: Could not find a version that satisfies the requirement torch>=1.6.0 (from kornia) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.6.0 (from kornia)

**Comment by edgarriba** [comment]
@Anit-G how did you install torch ? I added a sanity test for the package for windows apparently you need to add the path where to download the stable version.
`pip install torch -f https://download.pytorch.org/whl/torch_stable.html`

See: https://github.com/kornia/kornia/pull/744/files#diff-590af81d93d54911b0c816409487daa7b3b2457b1b3d0722903b138893419e80
