### ISSUE TITLE
Even when I use ColorJitter with all 0's it changes the image tensor

### ISSUE THREAD

**Issue by tumble-weed** [kornia/kornia#749]
i tried:
fg_jitter2 = K.ColorJitter(0.,0.,0.,0.,return_transform=True)
out,T = fg_jitter2(image_tensor)
when i do:
(out - image_tensor).norm()
 i got a nonzero answer (284.7068 for my case)
i got this same issue with kornia 0.3.2 ( albeit with pytorch 1.7) and 0.4.1

i saw a similar issue mentioned elsewhere:
Even when I use ColorJitter with all 0's it changes the color of my images and totally fades them ! This is really unexpected behavior. 
I used : K.augmentation.ColorJitter(0., 0., 0., 0.)

Can anyone fix this?

_Originally posted by @bluesky314 in https://github.com/kornia/kornia/issues/565#issuecomment-641197628_

**Comment by FGeri** [comment]
I've checked it with the latest release and it seems fine.
@tumble-weed Could you check if image_tensor is between [0.,1.] ?

**Comment by tumble-weed** [comment]
yes i think the range was the problem. it seems to be working after renormalizing into 0-1. thank you
