### ISSUE TITLE
Possibly swapped dims at RandomResizedCrop

### ISSUE THREAD

**Issue by FGeri** [kornia/kornia#761]
## 🐛 Bug

Possible swapped height and width in `random_crop_size_generator`.
In code size[0] is used for width and size[1] for height
https://github.com/kornia/kornia/blob/c77e62ce242ecf91f987783f1957ef97885e8e7b/kornia/augmentation/random_generator/random_generator.py#L367

But in doc it's the other way around:
https://github.com/kornia/kornia/blob/c77e62ce242ecf91f987783f1957ef97885e8e7b/kornia/augmentation/augmentation.py#L756-L757

**Comment by shijianjian** [comment]
That is a typo. Thanks for reporting. Will fix that soon.
