### ISSUE TITLE
[BUG] Deprecated interpolation argument doesn't have an effect

### ISSUE THREAD

**Issue by FGeri** [kornia/kornia#763]
## 🐛 Bug

Deprecated interpolation argument doesn't have an effect since `self.resample` gets overwritten right after it gets set by interpolation

https://github.com/kornia/kornia/blob/c77e62ce242ecf91f987783f1957ef97885e8e7b/kornia/augmentation/augmentation.py#L612-L616

**Comment by edgarriba** [comment]
@shijianjian is this still happening ?

**Comment by shijianjian** [comment]
@edgarriba  Safe to be closed. The deprecation warning has been removed in the current master.
