### ISSUE TITLE
[Feature Request] Manual image selection in data augmentation.

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#765]
## 🚀 Feature

Say we have a batch of 8 images, while we want to augment the first 4 but not the last 4. We may need a feature to manually select which images to apply and which images shall not to.

I think we may pass a list to the param generator.

```python
class Augmentation:
    def generate_params(self, to_apply=[1, 1, 1, 1, 0, 0, 0, 0]):
           return get_params(to_apply)
    def forward(self, input, params=None, to_apply=None):
          ...
          return input
```

**Comment by edgarriba** [comment]
@shijianjian I think this outdated according to the current design. Close if no need more discussion.
