### ISSUE TITLE
[Bug] Wrong padding order used at RandomCrop

### ISSUE THREAD

**Issue by FGeri** [kornia/kornia#771]
## 🐛 Bug
According to the kornia docu  left/ right or left, top, right, bottom order is used for 2D
https://github.com/kornia/kornia/blob/87a0ead264ce5fc97997071acb9fe2286d6c425c/kornia/augmentation/augmentation.py#L645-L648

In pytorch docu (padding_left,padding_right) ,(padding_left,padding_right,padding_top,padding_bottom) orders are used

But in the code it's mixed up.
https://github.com/kornia/kornia/blob/87a0ead264ce5fc97997071acb9fe2286d6c425c/kornia/augmentation/augmentation.py#L717-L723

and here for 3D:
https://github.com/kornia/kornia/blob/87a0ead264ce5fc97997071acb9fe2286d6c425c/kornia/augmentation/augmentation3d.py#L676-L678

Also `pad_if_needed` adds twice the necessary padding.

**Comment by FGeri** [comment]
We might want to align the padding order with the pytorch way, to avoid such issues, and uncosistencies in the docu like:
https://github.com/kornia/kornia/blob/87a0ead264ce5fc97997071acb9fe2286d6c425c/kornia/augmentation/augmentation3d.py#L593-L594

**Comment by shijianjian** [comment]
Yes. You are right. Can you send a PR for this?

For 3D, I think we might accept 3 values (left/right, top/bottom, front/back) and 6 values (left, top, right, bottom, front, back) similar to TorchVision.

**Comment by FGeri** [comment]
Not sure, test refactoring take up quite some time. I just write these issues I bump into in the process so they don't get forgotten.

**Comment by edgarriba** [comment]
@FGeri @shijianjian is this still happenning ?

**Comment by shijianjian** [comment]
> @FGeri @shijianjian is this still happenning ?

Yes. Hasn't been fixed yet.
