### ISSUE TITLE
[Bug] RandomCrop returns padded image when p=0

### ISSUE THREAD

**Issue by FGeri** [kornia/kornia#772]
## 🐛 Bug

`RandomCrop` returns the padded image when p=0, Probably `RandomCrop3D` is also affected.

**Comment by shijianjian** [comment]
They are the same logic. So, the same error I think.

I am not sure how to fix this one since torch does not support ragged tensor. We cannot partially pad a tensor there. What solution are you suggesting?

**Comment by shijianjian** [comment]
I got one idea for this. I would suggest having some sort of ```unpad_if_nessary``` to remove the padding in the end.
```python
def forward(self, input):
    shape = input.shape
    input = self.pad_if_nessary(input)
    input = crop(input)
    input = self.unpad_if_nessary(input, shape)
    return input
```

**Comment by edgarriba** [comment]
or `crop_and_pad` with `keepshape` or `keepdim` flag

**Comment by edgarriba** [comment]
This also opens the question of the need for a more  specific image padding function like `make_border`
https://stackoverflow.com/questions/43391205/add-padding-to-images-to-get-them-into-the-same-shape

**Comment by edgarriba** [comment]
is this still relevant ?

**Comment by shijianjian** [comment]
> is this still relevant ?

Hasn't been fixed yet.
