### ISSUE TITLE
Some functional APIs need to be refactored

### ISSUE THREAD

**Issue by shijianjian** [kornia/kornia#791]
## 🚀 Feature

function APIs shall not instantiate any nn.Modules.

A list of operations need to be refactored to not init nn.Modules:

- kornia.filters.*
- kornia.geometry.warp.depth_warper
- kornia.geometry.transform.pyramid
- kornia.losses.ssim
- kornia.features.SIFTDescriptor
- kornia.features.nms

## Motivation

As function APIs, they shall not instantiate any nn.Modules whilst calling while several functional implementations failed to do so.

**Comment by edgarriba** [comment]
continue discussion in #774
