### ISSUE TITLE
[Feat] Video augmentations

### ISSUE THREAD

**Issue by jbohnslav** [kornia/kornia#802]
## 🚀 Feature
Video data in PyTorch comes in shape `N x C=3 x D x H x W` with D here being the time dimension.  While certain augmentations have been implemented in 3D (e.g. RandomCrop), these seem to be focused on volumetric data, e.g. from medical imaging. Many operations such as ColorJitter and RandomGrayscale could be applied to this standard video input format-- however, they are blocked by Kornia's input shape checks (for `B x 3 x H x W`). 

## Motivation
Working with video, e.g. video classification, interpolation, or temporal action detection, is a common use case for PyTorch. As CPUs continue to fall behind GPUs, high-performance augmentation on the GPU for video data would be valuable. 

## Pitch
Ideally, any augmentation that works in 2D (with shape `N x 3 x H x W`) could be applied in `N x 3 x D x H x W`. If this would be too drastic of a change, we could also make a new `kornia.augmentation.video` for these kinds of augmentations. 

Functionality to be replicated: 
* CenterCrop # (note: could use CenterCrop3D, but requires knowing the clip length ahead of time)
* ColorJitter
* RandomCrop # (note: could use RandomCrop3D, but requires knowing the clip length ahead of time)
* RandomErasing
* RandomGrayscale
* ~~RandomHorizontalFlip~~ covered by RandomHorizontalFlip3D
* ~~RandomVerticalFlip~~
* RandomPerspective
* RandomResizedCrop
* ~~RandomRotation~~
* RandomSolarize
* RandomPosterize
* RandomSharpness
* RandomEqualize
* RandomMixup (??) # not sure if this has been applied to video data before
* RandomCutMix (??) # not sure if this has been applied to video data before

## Alternatives
As this is for a PhD project, I considered just hacking it together using `kornia.color` and `kornia.enhance`. I'm mostly interested in ColorJitter and RandomGrayscale.

**Comment by shijianjian** [comment]
For video data, you may follow the pipeline as (B, C, T, H, W) => (B*T, C, H, W) => augmentation (Note: check if you need same_on_bath or not) => (B, C, T, H, W).

For something that might help, I think we may consider adding a function like "kornia.VideoToSpatial" and "kornia.SpatialToVideo". Then you could integrate it as :

```python
nn.Sequential(
    kornia.VideoToSpatial(),
    kornia.augmentation.ColorJitter(0.1, 0.1, 0.1, 0.1),
    kornia.SpatialToVideo(channel_num=3)
)
```

Personally, the video data is still 2D. In TorchVision, Video data is referred to as 2.5D. As long as you are not altering the temporal channel, I would say a tensor shape conversion and 2D augmentations will be enough for your projects.

We are always interested in interesting projects :). If you have some ideas that will do something on the temporal channel, we will be happy to discuss and assist.

\cc @edgarriba @ducha-aiki

**Comment by edgarriba** [comment]
@jbohnslav thanks for pointing this out. I think such feature could be very useful for the community.

@shijianjian  As for the API, I have a couple of questions:
- why do you assume B, C, T, H, W  and not B, T, C, H, W ?
- another good naming could be `VideoToFrame`.
- can we with this setup e.g apply a different transform to a video batch ?

**Comment by shijianjian** [comment]
> @shijianjian  As for the API, I have a couple of questions:
> 
> - why do you assume B, C, T, H, W  and not B, T, C, H, W ?

Yes. You are right. 

> - another good naming could be `VideoToFrame`.

Could be. 

> - can we with this setup e.g apply a different transform to a video batch ?

What do you mean here? Isn't it provided by same_on_batch?

**Comment by jbohnslav** [comment]
> For video data, you may follow the pipeline as (B, C, T, H, W) => (B*T, C, H, W) => augmentation (Note: check if you need same_on_bath or not) => (B, C, T, H, W).

**Comment by shijianjian** [comment]
I see. For the minimum implementation, a smarter param_generator is needed.

Say (B, C, T, H, W), we firstly generate params for [0, 1, ..., B]. Then repeat it as [0<sub>0</sub>, ..., 0<sub>T</sub>, 1<sub>0</sub>, ..., 1<sub>T</sub>, ..., B<sub>0</sub>, ..., B<sub>T</sub>].

Maybe adding another parameter like ```same_every_frame``` and ```same_every_frame=1``` for normal 2D image, ```same_every_frame=T```  for video data?

Also, we may let it accept list as well. ```same_every_frame=[3, 5, 7]``` to give the user more choices about what they are doing.

I am not an expert on videos. What do you think? @jbohnslav 

This can be fairly easy to do but might be beneficial to many people I think. @edgarriba

**Comment by edgarriba** [comment]
@shijianjian wouldn't be more elegant to have a more generic thing like `dim: List[int]` to specify in which axis of the inputs we want the augmentation to be applied ?

**Comment by shijianjian** [comment]
> @shijianjian wouldn't be more elegant to have a more generic thing like `dim: List[int]` to specify in which axis of the inputs we want the augmentation to be applied ?

I don't think so. All 2D inputs shall be assumed as BCHW, while all 3D inputs are BCDHW.

The user shall refactor the input accordingly. 

Also, having the dim param means we shall support 1D to nD augmentation as well, not only 2D and 3D.

**Comment by shijianjian** [comment]
Another idea is to have a replacement for """nn.Sequential""".

We can do it like
"""Python
aug = K.VideoAugmentor(
    K.ColorJitter(0.1, 0.1, 0.1),
    K.RandomAffine(360.),
same_on_channel=True)
aug(input)  # BCTHW directly
"""

I think this could be more intuitive to our users.

**Comment by shijianjian** [comment]
@jbohnslav Please checkout #817 and let me know if there is anything else you are in need.
