### ISSUE TITLE
Improve tutorial codes

### ISSUE THREAD

**Issue by TarunSharmaNT** [kornia/kornia#833]
## 📚 Documentation

there are some codes in which there is not plt.show() statement and should explicitly need to put so it is better to edit the tutorial codes for the better visualization.

**Comment by edgarriba** [comment]
@TarunSharmaNT the tutorials is under refactoring. If you feel that you can help, please send a PR with your suggestions.

**Comment by edgarriba** [comment]
@TarunSharmaNT are being moved in https://github.com/kornia/tutorials
