### ISSUE TITLE
[Feature request] StereoCamera model and OpenCV initializations

### ISSUE THREAD

**Issue by copaah** [kornia/kornia#836]
## 🚀 Feature
For Stereo Vision tasks it would be handy to have a `StereoCamera` model which can be initialized with two `kornia.geometry.camera.PinholeCamera` and the stereo calibration. The `StereoCamera` can have some handy methods such as `StereoCamera.get_disparity_from_depth` and `StereoCamera.get_depth_from_disparity` and other methods for working with disparity maps.

In addition to this, I propose a feature for both the `PinholeCamera` and proposed `StereoCamera` that would add a factory method to both, called something like `from_OpenCV_calibration`, such that we can easily initialize a `PinholeCamera` and `StereoCamera` from OpenCVs `calibrateCamera` and `stereoCalibrate`. OpenCVs calibration methods are the de facto standard in many stereo vision tasks.

## Motivation

This will help researchers and developers who work on Stereo Vision tasks and want to use the nice features of Kornia otherwise. A lot of research is being put into Stereo Vision and Disparity Map estimation and I think Kornia will be a valuable tool here.

## Additional context

I would be happy to contribute these proposed features.

**Comment by edgarriba** [comment]
@copaah this sounds like a really good contribution idea. Could you sketch a bit the shape of this API before implementing ? If I'm not wrong `calibrateCamera` and `stereoCalibrate` just return the estimated  intrinsics/extrinsics. Why then a method called `from_OpenCV_calibration` ? the API could just consume those tensor matrices I guess.

/cc @jatentaki was doing some work on that

**Comment by copaah** [comment]
@edgarriba Thank you for your response.

Upon more consideration I think you are  right that the API should just consume the `P1` and `P2` camera matrices from `stereoRectify`, which is documented in OpenCV [here](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#stereorectify):

![image](https://user-images.githubusercontent.com/6583837/104387620-5fba6c00-54ec-11eb-9dd7-fb3b41d4d6a0.png)

Initially this would support horizonal stereo.

This is akin to the ROS CameraMsg documented [here](http://docs.ros.org/en/melodic/api/sensor_msgs/html/msg/CameraInfo.html).

The proposed API would then look something like

```
class StereoCamera:
    def __init__(
            self,
            left_rectified_intrinsics: kornia.geometry.camera.PinholeCamera,
            right_rectified_intrinsics: kornia.geometry.camera.PinholeCamera
        ):
        self._check_stereo_camera(left_rectified_intrinsics, right_rectified_intrinsics)
        self.left_rectified_intrinsics = left_rectified_intrinsics
        self.right_rectified_intrinsics = right_rectified_intrinsics

    def _check_stereo_camera(self, cam1, cam2):
        pass

    def depth_from_disparity(self, disparity_map: torch.Tensor):
        """
        :param disparity_map: Disparity tensors of shape (B, H, W)
        :return: Depth map of shape (B, H, W)
        """
        pass

    def disparity_from_depth(self, depth_map: torch.Tensor):
        """
        :param depth_map: Depth map of shape (B, H, W)
        :return: Disparity map of shape (B, H, W)
        """
        pass

    def reproject_disparity_to_point_cloud(self, disparity_map):
        pass

    def reproject_depth_to_3D(self, depth_map):
        pass

    def reproject_point_cloud_to_pixels(self, point_cloud):
        pass
```

Any thoughts?

**Comment by edgarriba** [comment]
@copaah loks like a good plan. Just one thing to consider when you implement - make sure that the underlying routines for the class methods are proper functionals that can be placed somewhere in kornia geometry core, either to `depth`, `epipolar` or in case we need a standalone `stereo` submodule.

**Comment by copaah** [comment]
@edgarriba I will! Looking into it this weekend and hopefully have a first draft.

**Comment by copaah** [comment]
@edgarriba I am writing a tutorial for the `StereoCamera` class. Does it go in `examples` or `tutorials`? Also, is there a better place to ask these questions?

**Comment by edgarriba** [comment]
@copaah join our slack https://join.slack.com/t/kornia/shared_invite/zt-csobk21g-CnydWe5fmvkcktIeRFGCEQ
