### ISSUE TITLE
Confusion regarding Pinhole Camera docs

### ISSUE THREAD

**Issue by copaah** [kornia/kornia#838]
## 📚 Documentation

Looking at the documentation for the `PinholeCamera` the mathematical formulation and drawings shows a `3x3` intrinsic matrix and `3x4` extrinsic matrix:

![image](https://user-images.githubusercontent.com/6583837/104113373-05cc6300-52ae-11eb-9b4c-6846168e47fd.png)

The `PinholeCamera` object, however, accepts an intrinsic matrix of shape `4x4` and an extrinsic matrix of shape `4x4`. It is not clear from the documentation how to convert between these representations. Being somewhat familiar with the representations in OpenCV I am also personally unsure how to do this conversion. 

Some clarification would be great.

EDIT: Looking at the tests I guess the intrinsics should be:

```
torch.Tensor([
 [f_x, 0, u_0, 0],
 [0, f_y, u_1, 0], 
 [0, 0, 1, 0], 
 [0, 0, 0, 1]
])
```

And the extrensics

```
torch.Tensor([
 [r_11, r_12, r_13, tx],
 [r_21, r_22, r_23, ty], 
 [r_31, r_32, r_33, tz], 
 [0, 0, 0, 1]
])
```
Is this correctly understood? If that is the case, I think it would be beneficial if that was clear from the documentation.

**Comment by edgarriba** [comment]
@copaah you are right. We designed in this way for the convenience to later chain matrix multiplications. Feel free to send a PR with this update in the docs for the `PinholeCamera` constructor.

**Comment by copaah** [comment]
> @copaah you are right. We designed in this way for the convenience to later chain matrix multiplications. Feel free to send a PR with this update in the docs for the `PinholeCamera` constructor.

I'll do so!
