### ISSUE TITLE
What is the difference between homography_warp and warp_perspective?

### ISSUE THREAD

**Issue by darkAlert** [kornia/kornia#844]
I've trained a model that predicts homography (3x3 matrix). I used the homography_warp function to warp the input image with predicted homography. I then used this warped image to calculate the loss. Finaly, the model's learnt to predict homogrphy.

However, I thought I could use this predicted homography in the cv.warpPerspective (or in kornia.warp_perspective) but I was wrong, I guess...

Can someone explain to me what is the difference between the transformation matrix using in kornia.homography_warp and kornia.warp_perspective (cv.warpPerspective), please?

**Comment by edgarriba** [comment]
the first assumes a normalized homography and the second it's assumed to map in pixel space

**Comment by darkAlert** [comment]
@edgarriba 
Sorry, I don't understand. The first and second take an image and a 3x3 matrix as input and output the image as the result. Is there a way to convert the input matrix from the first to the second?

**Comment by darkAlert** [comment]
Because I can predict this matrix, but I don’t know how to project points using this matrix.

**Comment by darkAlert** [comment]
Or is there a way to project some points with this input matrix that I use in homography_warp?

**Comment by edgarriba** [comment]
@darkAlert  you can use this matrix to convert https://kornia.readthedocs.io/en/latest/geometry.warp.html?highlight=normal_transform_pixel#kornia.geometry.warp.normal_transform_pixel
