### ISSUE TITLE
X and Y of camera coordinate system mixed up in Pinhole Camera figure

### ISSUE THREAD

**Issue by MichaelMedek** [kornia/kornia#860]
## 🐛 Bug

In the Pinhole Camera figure the axes of the camera coordinate system are mislabeled (X and Y are swapped). X must go from left to right (parallel to u) and Y from top to bottom (parallel to v). 
Otherwise the camera projection equation would not match the image (think of having no rotation and translation, then obviously X has to be parallel to u and Y to v). And also right now the camera system would be a left-handed system, so it would be impossible to find a rotation matrix from the world coordinate system to the camera system.

**Comment by edgarriba** [comment]
@MichaelMedek you are right. This is related too https://github.com/kornia/kornia/issues/704

I need to find some time to update that figure.
