### ISSUE TITLE
get_affine_matrix2d angle arg

### ISSUE THREAD

**Issue by anthonytec2** [kornia/kornia#870]
## 📚 Documentation

I have been using get_affine_matrix2d for a few weeks now and realized in the source code there is an additional angle argument which is not shown in the docstring for the function signature. Is there a reason for this or is this an error in the documentation?

**Comment by edgarriba** [comment]
@anthonytec2 thanks for reporting ! this is an error in the documentation. I see that the same happens for the 3d function. Should be easy to add - Could you send a quick PR adding those missing parameters. /cc @shijianjian can you verify ?

**Comment by edgarriba** [comment]
@shijianjian can you verify this when you check kornia.geometry. transforms ?

**Comment by edgarriba** [comment]
The parameter is already there:
https://kornia.readthedocs.io/en/latest/geometry.transform.html?highlight=affine_matrix#kornia.geometry.transform.get_affine_matrix2d
