### ISSUE TITLE
Thin Plate Spline Warping

### ISSUE THREAD

**Issue by catalys1** [kornia/kornia#872]
## 🚀 Feature
Image warping using thin plate splines. Functionalilty to solve for the transformation given two sets of points, then warp the image according to the transform parameters.

## Motivation

The thin plate spline (TPS) is a really useful non-linear warping technique that has been used a fair bit recently as an augmentation technique to aid in learning things like correspondence or disentangled latent spaces. However, there doesn't seem to be any standard pytorch implementation out there. Kornia seems like the perfect library to have a robust TPS implementation that can be used off the shelf.

## Pitch

As I see it, there are two key peices:
- Given two sets of corresponding points, solve for the TPS parameters that warp one to the other
- Given an image and TPS parameters, warp the image according to the TPS

The TPS should be able to be built from existing differentiable peices.

**Comment by edgarriba** [comment]
@catalys1 this is absolutely a very good idea :)

I add this amazing tutorial with a detailed implementation.
https://khanhha.github.io/posts/Thin-Plate-Splines-Warping/

Whoever is taking this task should definitively try to replicate this blog post.

**Comment by catalys1** [comment]
I put some code together that does this in basic pytorch (see the [gist](https://gist.github.com/catalys1/3eef0b6ee5749b5d8851755a7ee0e6e1)). Could be a starting point. I'd be happy to work with someone on getting it integrated into Kornia, but I'd probably need some help---I haven't contributed before.

**Comment by edgarriba** [comment]
@catalys1 this is amazing ! Could you join our Slack to discuss the integration details ? https://join.slack.com/t/kornia/shared_invite/zt-csobk21g-CnydWe5fmvkcktIeRFGCEQ

**Comment by catalys1** [comment]
@edgarriba Sure, what channel do you want me to bring it up in?
