### ISSUE TITLE
perspective camera, camera instrinsics matrix shape

### ISSUE THREAD

**Issue by jkamalu** [kornia/kornia#912]
## 📚 Documentation

The perspective camera documentation states that the unproject_points function requires a 4x4 camera matrix, but in the code an error is raised if the function is not passed a 3x3 camera matrix.

See here https://kornia.readthedocs.io/en/latest/geometry.camera.perspective.html#perspective-camera

**Comment by hiyyg** [comment]
I guess it is a documetation mistake.

**Comment by jkamalu** [comment]
Nice, I'm new to camera geometry and was confused by the need for a 4x4 intrinsics matrix.

Also, if you don't mind me asking... why don't we need to include a skew parameter in the intrinsics camera matrix? only focal length and principal point parameters are used in the projection/unprojection code.

Thanks!

**Comment by hiyyg** [comment]
Maybe this can help you: https://blog.immenselyhappy.com/post/camera-axis-skew/

**Comment by jkamalu** [comment]
Much appreciated, thanks!

**Comment by edgarriba** [comment]
@jakubLangr I'll fix this in the docs
