### ISSUE TITLE
RandomAffine raises error

### ISSUE THREAD

**Issue by silviab92** [kornia/kornia#914]
## 🐛 Bug

`kornia.augmentation.RandomAffine()` raises an error if `translate=(a, b)` with a < b. According to documentation, a and b should not be related, since they refer to maximum absolute fraction for horizontal and vertical translations, respectively. 

It seems that kornia/augmentation/random_generator/random_generator.py at line 181 run `_joint_range_check(cast(torch.Tensor, translate), "translate")` instead of `singular_range_check`

## To Reproduce

Code to reproduce:

```python
import kornia.augmentation as k_augmenter

affine_transformation = k_augmenter.RandomAffine(0, translate=(.5, 0))

aff_params = affine_transformation.generate_parameters([3, 100, 100])
```
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "site-packages/kornia/augmentation/augmentation.py", line 487, in generate_parameters
    self.same_on_batch)
  File "site-packages/kornia/augmentation/random_generator/random_generator.py", line 181, in random_affine_generator
    _joint_range_check(cast(torch.Tensor, translate), "translate")
  File "site-packages/kornia/augmentation/utils/param_validation.py", line 45, in _joint_range_check
    raise ValueError(f"{name}[0] should be smaller than {name}[1] got {ranged_factor}")
ValueError: translate[0] should be smaller than translate[1] got tensor([0.5000, 0.0000])

## Environment
 - torch==1.7.0
 - kornia==0.4.1

**Comment by UnibsMatt** [comment]
It happens to me to. Look like that instead of _joint_singular_check it use the _joint_range_check..

**Comment by shijianjian** [comment]
This error has already been fixed in the master branch.

Please try install:
```base
pip install --upgrade git+https://github.com/kornia/kornia.git
```

**Comment by silviab92** [comment]
Still getting the same error even with

```
kornia.__version__
'0.4.2+d8fb7fd'
```

**Comment by UnibsMatt** [comment]
<img width="900" alt="dd" src="https://user-images.githubusercontent.com/25898671/111329768-a9037500-866f-11eb-8a5d-c496064872a5.PNG">

Not really..

**Comment by shijianjian** [comment]
Ahh. I see the problem. I will fix it tomorrow.
