### ISSUE TITLE
NaN gradients on backward pass with focal loss

### ISSUE THREAD

**Issue by marlinsiebert** [kornia/kornia#918]
## 🐛 Bug

When computing the binary focal loss I got `nan` gradients on backward pass when `torch.sig(prediction)` equals `1.` or `0.` and `0.<gamma<1.`.

This probably does also concern the focal loss implementation.

## To Reproduce

```python
import torch
from kornia.losses import binary_focal_loss_with_logits

prediction=torch.tensor([[-100.,-100.,100.,100.]], requires_grad=True)
target = torch.tensor([[0.,1.,0.,1.]])
loss = binary_focal_loss_with_logits(prediction, target, gamma=0.5, reduction='mean')
loss.backward()
print(prediction.grad)
```

> tensor([[nan, nan, nan, nan]])

## Expected behavior

Return reasonable gradients.

## Environment

 - PyTorch Version: 1.8.0
 - OS: Win10
 - How you installed PyTorch: `conda`
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.2
 - GPU: Nvidia RTX2060 Super
- Kornia Version: 0.5.0

## Additional context

`nan` occurs during computation of gradients with respect to `torch.pow()`.
Suggested quick fix - also include `eps` in `torch.pow()`:
```pyhton
loss_tmp = - alpha * torch.pow((1. - probs + eps), gamma) * target * torch.log(probs + eps) \
                   - (1 - alpha) * torch.pow(probs + eps, gamma) * (1. - target) * torch.log(1. - probs + eps)
```

**Comment by edgarriba** [comment]
@marlinsiebert thanks for pointing this out. I created this small colab to verify with the autograd anomaly detection and I found the following:

```python
import torch
from kornia.losses import binary_focal_loss_with_logits

prediction=torch.tensor([[-100.,-100.,100.,100.]], requires_grad=True)
target = torch.tensor([[0.,1.,0.,1.]])
with torch.autograd.detect_anomaly():
    loss = binary_focal_loss_with_logits(prediction, target, gamma=0.5, reduction='mean')
    loss.backward()
    print(prediction.grad)
```
`RuntimeError: Function 'PowBackward0' returned nan values in its 0th output.`

Colab: https://colab.research.google.com/drive/15FtME_528Sgqey-aSKua9JLB3b5UkJPd?usp=sharing

Definitely adding the epsilon values should fix the issue.

**Comment by adi1999** [comment]
@edgarriba Adding the eps value is fixing the issue, can I make a PR for the same.

**Comment by edgarriba** [comment]
@adi1999 yes please, go ahead
