### ISSUE TITLE
Usage of 'Resize' in 'VideoSequential'

### ISSUE THREAD

**Issue by YuhaoCheng** [kornia/kornia#923]
I use the 'Resize' object in the 'VideoSequential' in order to transform the whole video clip, however, I encounter the error:
`torch.nn.modules.module.ModuleAttributeError: 'Resize' object has no attribute 'forward_parameters'`. So I want to know how to solve it.

Thanks.

**Comment by shijianjian** [comment]
The VideoSequential is designed for ```kornia.augmentation``` only. Also, torch can natively resize the tensor. Just fix the temporal dimension as it is.

**Comment by YuhaoCheng** [comment]
> The VideoSequential is designed for `kornia.augmentation` only. Also, torch can natively resize the tensor. Just fix the temporal dimension as it is.

Thanks for your help. I got it.  But if I want to resize the spatial dimension of the video, what should I use? For example, I get an original video with the size of 1080x1920, however, the input of the network should be 384x288. 

Thanks again.

**Comment by shijianjian** [comment]
This shall do:
```python
input.shape = (B, C, T, 1080, 1920)
torch.nn.functional.interpolate(input, size=(T, 384, 288))
```
