### ISSUE TITLE
RandomResizedCrop - Kornia vs. Torchvision

### ISSUE THREAD

**Issue by deepneuralnetworks** [kornia/kornia#927]
Thanks for the code.

I'm using kornia 0.4.0 and found major difference between torchvision and kornia while using _randomresizedcrop_ in _augmentation_. 

In case of torchvision the window to crop is **computed with a input size** of the image but in case of kornia is a  **output size** of the image.

Just wanted to report because I have no idea whether it is intended to do so or not.

**Comment by shijianjian** [comment]
Thank you for reporting. We were expecting the similar outcome as TV, but we might not test enough on the random generators. We might need to come up a proper method to test the distribution from any random gens, @edgarriba, @anguelos.

@deepneuralnetworks, Are you willing to send a PR to fix this issue?

Best,
Jian
