### ISSUE TITLE
[Feat] Add rgb to grayscale interface with custom weights

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#931]
## 🚀 Feature

Add rgb to grayscale interface with custom weights or string to indicate other modes

**Comment by AnimeshMaheshwari22** [comment]
Hello. I would like to work on this. It would be great to receive some elucidation on the required functionality. Thank you!

**Comment by edgarriba** [comment]
merge in https://github.com/kornia/kornia/pull/944
