### ISSUE TITLE
[Feat] Add more draw utilities

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia#936]
## 🚀 Feature
Implement more drawing functions in `kornia.utils`:
- [ ] `draw_point`
- [ ] `draw_line`
- [ ] `draw_polyline` https://github.com/kornia/kornia/issues/278

Some resources:
- https://stackoverflow.com/questions/31638651/how-can-i-draw-lines-into-numpy-arrays

**Comment by dobosevych** [comment]
Can I help with this one?

**Comment by Abdelrhman-Hosny** [comment]
I've been dabbling with `draw_line` for a couple of days, and I finished writing the function for it using this [Line Drawing Algorithm](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm#Line_equation), at the time it is not optimized and not properly validated.

I've created a [kaggle notebook](https://www.kaggle.com/abdelrhmanhosny/test-draw-line)  to show how my function compares to opencv's function of draw line.

If this implementation is accepted, I can modify it to have proper validations, test cases and optimize it.

**Comment by dobosevych** [comment]
I think the goal was to do that on GPU. I am not sure whether numpy suits or under optimization you mean moving that to GPU?

**Comment by edgarriba** [comment]
@Abdelrhman-Hosny the implementation looks really cool and seems pretty straightforward to port it to pure torch operators and will cover already @dobosevych comments.

I think the ideal would be something like this:
```python
def draw_line(image: torch.Tensor, line: torch.Tensor) -> torch.Tensor:
  """Draw a tensor containing defined geometric 2d lines into an image.

  Args:
    image: the input image to where to draw the lines with shape (B,C,H,W).
    lines: the tensor containing the lines to draw with shape (B, N, 4) where lines are defined [x1 y1 x2 y2].

  Return:
     the image containing the lines.
"""
```
We can think also about adding other properties like colour, thickness, etc.

Any other thoughts @shijianjian @ducha-aiki @anguelos  ?

**Comment by edgarriba** [comment]
One more comment - we have `render_gaussian2d` that is meant to render 2d points in a differentiable way, but it's quite memory consuming and not really sure that's a good choice here. @anibali  thoughts ?
https://kornia.readthedocs.io/en/latest/geometry.subpix.html#kornia.geometry.subpix.render_gaussian2d

**Comment by edgarriba** [comment]
>     * is the cython part needed?
kornia only accepts torch as dependency

>     * The function above takes, B images and for each image there are N lines, is that correct ?
yeap :+1:

**Comment by Abdelrhman-Hosny** [comment]
I've started working, now I've added a color parameter to the line.

I've created 3 functions

```
def draw_pixel(
    image: torch.Tensor,
    x: int,
    y: int,
    color: torch.Tensor,
    ):
    r"""Draws a pixel into an image.

    Args:
        image: the input image to where to draw the lines with shape (C,H,W).
        x: the x coordinate of the pixel.
        y: the y coordinate of the pixel.
        color: the color of the pixel with shape (3).
    
    Return:
        Nothing is returned
"""
```
****

```
def draw_lines(
    images: torch.Tensor,
    lines: torch.Tensor,
    color: torch.Tensor,
    ) -> torch.Tensor:
    r"""Draw a tensor containing defined geometric 2d lines into an image.

    Args:
        images: the input image to where to draw the lines with shape (B,C,H,W).
        lines: the tensor containing the lines to draw with shape (B, N, 4) where lines are defined [x1 y1 x2 y2].

    Return:
        the images (B,C,H,W) containing the lines.
    """
```
****

```
def draw_line(
    image : torch.Tensor,
    p1 : torch.Tensor, p2 : torch.Tensor,
    color : torch.Tensor,
    ):
    r"""Draw a single line into an image.

    Args:
        image: the input image to where to draw the lines with shape (C,H,W).
        p1: the start point of the line with shape (2).
        p2: the end point of the line with shape (2).
        color: the color of the line with shape (3).

    Return:
        the image containing the line.
    """
```
****

I'm writing to give an update, also confirm the names and inputs of the functions, are these okay ?.

I would also like to ask whether all 3 functions should be added to the `kornia.utils` or whether I should only add `draw_lines` and the rest be put somewhere else ?

I tested these manually and got the results I wanted, I'm waiting for confirmation so I could write automatic tests.

**Comment by edgarriba** [comment]
I think having the three functions public it's good. One question - `draw_pixel` why returns `None`, is it supposed to happen inplace ? why not return the image ?

**Comment by Abdelrhman-Hosny** [comment]
My thought process was that `draw_pixel` only has one line that is executed `image[:, y, x] = color` and the rest of it is just will just be checks to make sure that the pixels are inside the image. 

So, it won't be used outside another function. should I change it to `_draw_pixel` instead ?

**Comment by edgarriba** [comment]
In that case, yes - keep it private
