### ISSUE TITLE
RandomCrop issue

### ISSUE THREAD

**Issue by delkov** [kornia/kornia#954]
RandomCrop works fine with padding_mode = 'consant'.
But with 'reflect' I got error:    
```
 assert len(pad) == 2, '3D tensors expect 2 values for padding'
AssertionError: 3D tensors expect 2 values for padding

```

```
crop_width=2014
crop_height= 758
random_crop = kornia.augmentation.RandomCrop(
        size=(crop_height, crop_width),
        pad_if_needed=1,
        padding_mode='constant', # 'reflect'
        p=1
)
kornia_transform = nn.Sequential(
    random_crop
)

    korn_img = kornia_transform(torch_arr)

```
torch_arr.shape is [1, 720, 1280]

Is there mirror-like pad function? So I want to pad it first ant then crop

**Comment by edgarriba** [comment]
@shijianjian is it a known issue ?

**Comment by edgarriba** [comment]
if think @anguelos implemented a pad_if_needed in torchvision

**Comment by shijianjian** [comment]
It is a partial bug here that the input shall be transformed into BCHW. It is not about the padding mode. Will fix that soon.
