### ISSUE TITLE
use scenarios

### ISSUE THREAD

**Issue by carr123** [kornia/kornia#961]
hello,  deep learning using pytorch, for example, cnn, can automatic extract features from an image, and perform classification task.
kornia seems to extract features from an image manually like opencv.
so, i wonder, what is the situation best for using kornia.  could you give me some use cases ？
thanks.

**Comment by shijianjian** [comment]
Have you checked those [tutorials](https://kornia.readthedocs.io/en/latest/tutorials/index.html)? I think you might find some use cases there. Meanwhile, you may also tell us that what you are actually looking for.
