### ISSUE TITLE
import kornia 0.2 ImportError: cannot import name 'BorderType'

### ISSUE THREAD

**Issue by mlizhardy** [kornia/kornia#991]
I need to use version >= 0.2.0 and <= 0.2.2 to match other dependencies.  I specifically need to use kornia.geometry for warping. 

When I import kornia I get the following error message:

```
from kornia.constants import Resample, BorderType, SamplePadding, pi
ImportError: cannot import name 'BorderType'
```

code to reproduce:

`import kornia`

torch==1.2.0, python==3.6

How can I solve this?

**Comment by edgarriba** [comment]
With which version of Kornia you get this import error ?

**Comment by shijianjian** [comment]
I think we are not supporting pytorch versions prior to 1.6.0. You might try:
```
pip install kornia --no-dependencies
```
to avoid lib overriding. However, I cannot guarantee if it is feasible for your use case.
